function outputs=build_summaries(project,T,C,caseInfo,predictorAudit,candidateAudit)
%BUILD_SUMMARIES Produce all registered quantitative summary tables.
cohorts=cohort_masks(T);
metrics=table();confusion=table();contribution=table();candidate=table();
for g=1:numel(cohorts)
    mask=cohorts(g).mask;
    for p=project.model_error.predictor_names
        metrics=[metrics;metric_row(T,C,mask,cohorts(g),p)]; %#ok<AGROW>
        confusion=[confusion;confusion_row(T,mask,cohorts(g),p)]; %#ok<AGROW>
        candidate=[candidate;candidate_row(C,T,mask,cohorts(g),p)]; %#ok<AGROW>
    end
    contribution=[contribution;contribution_row(T,mask,cohorts(g),project.model_error.predictor_names)]; %#ok<AGROW>
end
writetable(metrics,fullfile(project.dirs.summary,'predictor_metrics.csv'));
writetable(contribution,fullfile(project.dirs.summary,'error_source_contribution.csv'));
writetable(confusion,fullfile(project.dirs.summary,'constraint_confusion_by_predictor.csv'));
writetable(candidate,fullfile(project.dirs.summary,'predictor_candidate_comparison.csv'));

correlations=zhou_model_error.residual_correlations(T);
spectrum=zhou_model_error.residual_spectrum(project,T);
writetable(correlations,fullfile(project.dirs.summary,'residual_state_correlations.csv'));
writetable(spectrum,fullfile(project.dirs.summary,'residual_spectrum.csv'));
writetable(caseInfo,fullfile(project.dirs.summary,'case_classification.csv'));
repeatability=repeatability_table(project,predictorAudit,candidateAudit);
writetable(repeatability,fullfile(project.dirs.summary,'repeatability_check.csv'));
outputs=struct('predictor_metrics',metrics,'contribution',contribution,'confusion',confusion, ...
    'candidate',candidate,'correlations',correlations,'spectrum',spectrum, ...
    'repeatability',repeatability,'case_classification',caseInfo);
end

function cohorts=cohort_masks(T)
cohorts=struct('type',{},'name',{},'mask',{});
cohorts(end+1)=item("aggregate","REPRODUCTION_ALL",true(height(T),1));
cohorts(end+1)=item("aggregate","ENGINEERING_PRIMARY",T.range_class~="stress_test");
for value=unique(T.range_class).',cohorts(end+1)=item("range",value,T.range_class==value);end %#ok<AGROW>
for value=unique(T.case_category).',cohorts(end+1)=item("category",value,T.case_category==value);end %#ok<AGROW>
for value=unique(T.phase).',cohorts(end+1)=item("phase",value,T.phase==value);end %#ok<AGROW>
for value=unique(T.case_id,'stable').',cohorts(end+1)=item("case",value,T.case_id==value);end %#ok<AGROW>
end

function s=item(type,name,mask),s=struct('type',string(type),'name',string(name),'mask',logical(mask));end

function R=metric_row(T,C,mask,g,p)
ed=T.("ed_"+p);eq=T.("eq_"+p);valid=mask&isfinite(ed)&isfinite(eq);x=ed(valid);y=eq(valid);
predD=T.("Jd_"+p)<=(.16+1e-9);predQ=T.("Jq_"+p)<=(.16+1e-9);
actualD=T.Jd_actual<=(.16+1e-9);actualQ=T.Jq_actual<=(.16+1e-9);
fsD=predD&~actualD;fsQ=predQ&~actualQ;fs=T.("false_safe_"+p);fa=T.("false_alarm_"+p);
s2=valid&near_s2(T);steady=valid&T.phase=="steady";dynamic=valid&T.phase=="dynamic";
cm=candidate_mask(C,T,mask,p);CX=C(cm,:);
R=table(g.type,g.name,p,causality(p),nnz(mask),nnz(valid), ...
    avg(x),avg(y),rmsv(x),rmsv(y),rmsv(hypot(x,y)),peak(x),peak(y),peak(hypot(x,y)), ...
    nnz(fsD&valid),nnz(fsQ&valid),nnz(fs&valid),avg(double(fs(valid))),avg(double(fa(valid))), ...
    max_run_by_case(fs&valid,T.case_id),avg(double(predD(valid)&predQ(valid))),avg(double(actualD(valid)&actualQ(valid))), ...
    rmsv(hypot(ed(steady),eq(steady))),rmsv(hypot(ed(dynamic),eq(dynamic))),rmsv(hypot(ed(s2),eq(s2))), ...
    avg(double(CX.top1_flip_vs_P0)),avg(double(CX.mode_flip_vs_P0)),avg(double(CX.diagnostic_top1_voltage_changed)), ...
    'VariableNames',{'cohort_type','cohort','predictor','causality_class','registered_sample_count','valid_sample_count', ...
    'ed_mean_A','eq_mean_A','ed_rms_A','eq_rms_A','vector_rms_A','ed_peak_A','eq_peak_A','vector_peak_A', ...
    'false_safe_d_count','false_safe_q_count','false_safe_joint_count','false_safe_joint_rate','false_alarm_joint_rate', ...
    'maximum_consecutive_false_safe','predicted_joint_pass_rate','actual_joint_pass_rate', ...
    'steady_vector_rms_A','dynamic_vector_rms_A','S2_near_vector_rms_A', ...
    'top1_flip_vs_P0_rate','mode_flip_vs_P0_rate','diagnostic_top1_voltage_changed_rate'});
end

function R=confusion_row(T,mask,g,p)
valid=mask&isfinite(T.("id_pred_"+p));actual=T.actual_joint_pass;pred=T.("predicted_pass_"+p);
tp=nnz(valid&~actual&~pred);tn=nnz(valid&actual&pred);fs=nnz(valid&~actual&pred);fa=nnz(valid&actual&~pred);
R=table(g.type,g.name,p,causality(p),nnz(valid),tp,tn,fs,fa,safediv(fs,nnz(valid)),safediv(fa,nnz(valid)), ...
    safediv(tp,tp+fs),safediv(tn,tn+fa),max_run_by_case(valid&~actual&pred,T.case_id), ...
    'VariableNames',{'cohort_type','cohort','predictor','causality_class','sample_count', ...
    'true_violation_predicted_violation','true_safe_predicted_safe','false_safe_count','false_alarm_count', ...
    'false_safe_rate','false_alarm_rate','violation_recall','safe_specificity','maximum_consecutive_false_safe'});
end

function R=contribution_row(T,mask,g,names)
common=mask;
for p=names,common=common&isfinite(T.("ed_"+p))&isfinite(T.("eq_"+p));end
M=zeros(1,numel(names));for k=1:numel(names),M(k)=mean(T.("ed_"+names(k))(common).^2+T.("eq_"+names(k))(common).^2);end
ix=@(p)find(names==p,1);M0=M(ix("P0"));M1=M(ix("P1"));M2a=M(ix("P2a"));M2b=M(ix("P2b"));
M3a=M(ix("P3a"));M3b=M(ix("P3b"));M4=M(ix("P4"));M5=M(ix("P5"));
fCausal=M0-M2a;fInstant=M0-M2b;alpha=M0-M1;jCausal=M0-M3a;jInstant=M0-M3b;
interaction=M1+M2b-M0-M3b;factorial=M0-M2b-M1+M3b;
fSh=.5*((M0-M2b)+(M1-M3b));aSh=.5*((M0-M1)+(M2b-M3b));freeze=M3b-M4;disc=M4-M5;structure=M3b-M5;
explained=M0-M5;
R=table(g.type,g.name,nnz(mask),nnz(common),M0,M1,M2a,M2b,M(ix("P2c")),M3a,M3b,M(ix("P3c")),M4,M5, ...
    fCausal,fInstant,alpha,jCausal,jInstant,interaction,factorial,freeze,disc,structure,M5,fSh,aSh, ...
    safediv(fSh,explained),safediv(aSh,explained),safediv(structure,explained), ...
    fInstant>=.2*M0,alpha>=.2*M0,structure>=.2*M0, ...
    mean(T.false_safe_P0(mask)),mean(T.false_safe_P0(common)), ...
    'VariableNames',{'cohort_type','cohort','registered_sample_count','common_sample_count', ...
    'MSE_P0_A2','MSE_P1_A2','MSE_P2a_A2','MSE_P2b_A2','MSE_P2c_A2','MSE_P3a_A2','MSE_P3b_A2','MSE_P3c_A2','MSE_P4_A2','MSE_P5_A2', ...
    'Delta_F_causal_A2','Delta_F_instant_A2','Delta_alpha_A2','Delta_joint_causal_A2','Delta_joint_instant_A2', ...
    'Delta_F_alpha_interaction_excess_A2','factorial_interaction_MSE_A2','Delta_two_period_F_freezing_A2', ...
    'Delta_discretization_structure_A2','Delta_structure_total_A2','Delta_remaining_oracle_gap_A2', ...
    'F_shapley_contribution_A2','alpha_shapley_contribution_A2','F_share_of_explained','alpha_share_of_explained', ...
    'structure_share_of_explained','material_F','material_alpha','material_structure', ...
    'P0_false_safe_full_mask_rate','P0_false_safe_common_intersection_rate'});
end

function R=candidate_row(C,T,mask,g,p)
cm=candidate_mask(C,T,mask,p);X=C(cm,:);valid=X.predictor_valid;
if isempty(X),X=C([],:);valid=false(0,1);end
primary=valid&X.ranking_valid;eligible=primary&X.top1_recovery_eligible==1;modeEligible=primary&X.mode_recovery_eligible==1;
R=table(g.type,g.name,p,causality(p),all_or_false(X.ranking_valid),nnz(valid), ...
    "offline_diagnostic_candidate_bank_not_native_Zhou_candidates", ...
    avg(double(X.top1_flip_vs_P0(valid))),avg(double(X.top3_set_flip_vs_P0(valid))),avg(double(X.mode_flip_vs_P0(valid))), ...
    avg(double(X.feasibility_flip_vs_P0(valid))),avg(double(X.top1_agrees_with_P5(primary))), ...
    nnz(eligible),sum(X.top1_recovered(eligible),'omitnan'),safediv(sum(X.top1_recovered(eligible),'omitnan'),nnz(eligible)), ...
    sum(X.top1_new_error(primary),'omitnan'),nnz(modeEligible),sum(X.mode_recovered(modeEligible),'omitnan'), ...
    safediv(sum(X.mode_recovered(modeEligible),'omitnan'),nnz(modeEligible)),sum(X.mode_new_error(primary),'omitnan'), ...
    avg(X.top3_jaccard_vs_P5(primary)),avg(double(X.diagnostic_top1_voltage_changed(valid&X.S2_triggered))), ...
    avg(double(X.diagnostic_top1_voltage_changed(valid))), ...
    'VariableNames',{'cohort_type','cohort','predictor','causality_class','ranking_valid','sample_count', ...
    'candidate_bank_semantics','top1_flip_vs_P0_rate','top3_flip_vs_P0_rate','mode_flip_vs_P0_rate', ...
    'feasibility_flip_vs_P0_rate','top1_agreement_with_P5_rate','top1_recovery_eligible_count', ...
    'top1_recovered_count','top1_recovery_rate','top1_new_error_count','mode_recovery_eligible_count', ...
    'mode_recovered_count','mode_recovery_rate','mode_new_error_count','top3_jaccard_vs_P5', ...
    'S2_changed_command_rate','diagnostic_top1_voltage_changed_rate'});
end

function cm=candidate_mask(C,T,mask,p)
keys=T.case_id(mask)+"|"+string(T.sample_index(mask));cm=C.predictor==p&ismember(C.case_id+"|"+string(C.sample_index),keys);
end

function mask=near_s2(T)
mask=false(height(T),1);cases=unique(T.case_id,'stable');
for c=cases.',ix=find(T.case_id==c);hit=find(T.S2_triggered(ix));for h=hit.',mask(ix(max(1,h-2):min(numel(ix),h+2)))=true;end,end
end

function value=max_run_by_case(flag,cases)
value=0;for c=unique(cases,'stable').',x=flag(cases==c);d=diff([false;x(:);false]);starts=find(d==1);stops=find(d==-1);if ~isempty(starts),value=max(value,max(stops-starts));end,end
end

function T=repeatability_table(project,P,C)
baseline=readtable(fullfile(project.dirs.summary,'baseline_comparison.csv'),'TextType','string');b=baseline(baseline.check=="three_run_repeatability",:);
names=["baseline_three_run_numeric";"P0_formula_reproduction";"P5_exact_replay";"selected_applied_command_carry";"candidate_P5_step_convergence";"random_seed_frozen"];
observed=[b.observed(1);sprintf('max_gap_A=%.17g',max([P.P0_recompute_max_gap_A])); ...
    sprintf('max_gap_A=%.17g',max([P.P5_replay_max_gap_A]));sprintf('all_pass=%d',all([P.command_carry_pass])); ...
    sprintf('failures=%d checks=%d',sum([C.P5_convergence_failures]),sum([C.P5_convergence_checks])); ...
    "seed="+project.model_error.random_seed];
pass=[logical(b.pass(1));max([P.P0_recompute_max_gap_A])<=project.model_error.predictor_tolerance_A; ...
    max([P.P5_replay_max_gap_A])<=project.model_error.plant_replay_tolerance_A;all([P.command_carry_pass]); ...
    sum([C.P5_convergence_failures])==0;true];
requirement=["<=1e-12";"<=2e-10 A";"<=2e-9 A";"all true";"zero ranking flips";"fixed deterministic seed"];
T=table(names,pass,observed,requirement);assert(all(pass),'ZhouModelError:RepeatabilityGate');
end

function value=avg(x),x=x(isfinite(x));if isempty(x),value=NaN;else,value=mean(x);end,end
function value=rmsv(x),x=x(isfinite(x));if isempty(x),value=NaN;else,value=sqrt(mean(x.^2));end,end
function value=peak(x),x=x(isfinite(x));if isempty(x),value=NaN;else,value=max(abs(x));end,end
function value=safediv(a,b),if b==0,value=NaN;else,value=a/b;end,end
function value=all_or_false(x),if isempty(x),value=false;else,value=all(x);end,end
function value=causality(p)
if ismember(p,["P0","P1"]),value="causal_original";elseif ismember(p,["P2a","P3a"]),value="causal_previous_period_oracle";elseif ismember(p,["P2b","P3b","P4"]),value="offline_physical_parameter_oracle";elseif ismember(p,["P2c","P3c"]),value="noncausal_future_endpoint_oracle";else,value="offline_plant_replay_oracle";end
end
