function result=generate_documentation(project,T,S,decision,caseInfo,figureManifest)
%GENERATE_DOCUMENTATION Build the complete, data-backed audit handoff.
% The reports are generated only from the frozen project configuration,
% sample table, registered summary tables, decision table, case registry,
% figure manifest, and provenance CSVs. No controller is changed here.

arguments
    project (1,1) struct
    T table
    S (1,1) struct
    decision table
    caseInfo table
    figureManifest table
end

requiredSummaryFields=["predictor_metrics","contribution","confusion","candidate", ...
    "correlations","spectrum","repeatability","case_classification"];
for name=requiredSummaryFields
    assert(isfield(S,name),'ZhouModelError:DocumentationInput', ...
        'Missing summary table S.%s.',name);
end
assert(height(T)>0&&height(decision)==1&&height(caseInfo)>0, ...
    'ZhouModelError:DocumentationInput','Documentation inputs must be populated.');
assert(all(ismember(project.model_error.predictor_names,string(S.predictor_metrics.predictor))), ...
    'ZhouModelError:DocumentationInput','Predictor metrics do not cover P0--P5.');

C=build_context(project,T,S,decision,caseInfo,figureManifest);
rootFiles=["README.md","HANDOFF.md","CHANGELOG.md","RUN_AND_REPRODUCE.md"];
docFiles=["PROJECT_SCOPE.md","PREVIOUS_WORK_INVENTORY.md","DUPLICATE_WORK_CHECK.md", ...
    "SOURCE_PROJECT_INVENTORY.md","PATH_CONFLICT_REPORT.md","BASELINE_REPRODUCTION_REPORT.md", ...
    "ORIGINAL_PREDICTOR_DEFINITION.md","TIMING_ALIGNMENT_AUDIT.md", ...
    "ORACLE_PREDICTOR_DEFINITION.md","EXPERIMENT_PROTOCOL.md","METRIC_DEFINITIONS.md", ...
    "MODEL_ERROR_DECOMPOSITION_REPORT.md","DECISION_AND_NEXT_STEP.md", ...
    "KNOWN_LIMITATIONS.md","PROTOTYPE_GATE_REPORT.md"];

write_md(fullfile(project.root,'README.md'),readme_document(C));
write_md(fullfile(project.root,'HANDOFF.md'),handoff_document(C));
write_md(fullfile(project.root,'CHANGELOG.md'),changelog_document(C));
write_md(fullfile(project.root,'RUN_AND_REPRODUCE.md'),reproduce_document(C));
write_md(fullfile(project.dirs.docs,'PROJECT_SCOPE.md'),scope_document(C));
write_md(fullfile(project.dirs.docs,'PREVIOUS_WORK_INVENTORY.md'),previous_document(C));
write_md(fullfile(project.dirs.docs,'DUPLICATE_WORK_CHECK.md'),duplicate_document(C));
write_md(fullfile(project.dirs.docs,'SOURCE_PROJECT_INVENTORY.md'),source_document(C));
write_md(fullfile(project.dirs.docs,'ORIGINAL_PREDICTOR_DEFINITION.md'),original_document(C));
write_md(fullfile(project.dirs.docs,'TIMING_ALIGNMENT_AUDIT.md'),timing_document(C));
write_md(fullfile(project.dirs.docs,'ORACLE_PREDICTOR_DEFINITION.md'),oracle_document(C));
write_md(fullfile(project.dirs.docs,'EXPERIMENT_PROTOCOL.md'),protocol_document(C));
write_md(fullfile(project.dirs.docs,'METRIC_DEFINITIONS.md'),metrics_document(C));
write_md(fullfile(project.dirs.docs,'MODEL_ERROR_DECOMPOSITION_REPORT.md'),report_document(C));
write_md(fullfile(project.dirs.docs,'DECISION_AND_NEXT_STEP.md'),decision_document(C));
write_md(fullfile(project.dirs.docs,'KNOWN_LIMITATIONS.md'),limitations_document(C));
ensure_supporting_documents(C);

rootPaths=fullfile(project.root,rootFiles);docPaths=fullfile(project.dirs.docs,docFiles);
allPaths=[rootPaths,docPaths];
assert(all(isfile(allPaths)),'ZhouModelError:DocumentationMissing', ...
    'One or more registered handoff documents were not generated.');
result=struct('generated',true,'file_count',numel(allPaths), ...
    'root_documents',rootPaths,'docs_documents',docPaths, ...
    'case_count',C.case_count,'sample_count',C.sample_count, ...
    'decision_code',C.decision.decision_code(1), ...
    'upstream_changed_files_at_documentation',C.freeze.changed_files, ...
    'upstream_validation_status',C.freeze.status);
end

function C=build_context(project,T,S,decision,caseInfo,figureManifest)
C=struct();C.project=project;C.T=T;C.S=S;C.decision=decision;C.caseInfo=caseInfo;
C.figureManifest=figureManifest;C.generated_at=string(datetime('now','TimeZone','Asia/Shanghai', ...
    'Format','yyyy-MM-dd HH:mm:ss XXX'));
C.case_count=numel(unique(T.case_id,'stable'));C.sample_count=height(T);
C.common_sample_count=nnz(T.oracle_previous_valid);C.predictors=project.model_error.predictor_names;
C.metrics_all=one_cohort(S.predictor_metrics,"REPRODUCTION_ALL");
C.metrics_primary=one_cohort(S.predictor_metrics,"ENGINEERING_PRIMARY");
C.contribution_all=one_cohort(S.contribution,"REPRODUCTION_ALL");
C.contribution_primary=one_cohort(S.contribution,"ENGINEERING_PRIMARY");
C.confusion_primary=one_cohort(S.confusion,"ENGINEERING_PRIMARY");
C.candidate_primary=one_cohort(S.candidate,"ENGINEERING_PRIMARY");
C.baseline=safe_read(fullfile(project.dirs.summary,'baseline_comparison.csv'));
C.upstreams=safe_read(fullfile(project.root,'SOURCE_PROJECTS.csv'));
C.before=safe_read(fullfile(project.root,'SOURCE_SHA256_BEFORE.csv'));
C.provenance=safe_read(fullfile(project.root,'COPIED_FILE_PROVENANCE.csv'));
C.freeze=freeze_status(project,C.before);
C.prior=prior_sequence_evidence(project);
C.matlab_release=matlab_release();
C.raw_csv=fullfile(project.dirs.raw,'model_error_samples.csv');
C.summary_root=project.dirs.summary;C.figure_root=project.dirs.figures;
C.baseline_passed=sum(logical(C.baseline.pass));C.baseline_failed=height(C.baseline)-C.baseline_passed;
C.figure_count=sum(logical(figureManifest.generated));
C.figure_failed=height(figureManifest)-C.figure_count;
end

function L=readme_document(C)
D=C.decision;M=C.metrics_all;MP=C.metrics_primary;
L=["# Zhou ICF-MPC IPMSM 一阶超局部模型误差分解";""; ...
    "这是一个完全隔离的离线诊断工程。它冻结五个上游，只重放闭环数据并建立 P0--P5 预测器阶梯，用替换实验区分 `F` 估计、`alpha` 输入增益、两拍冻结/离散化及剩余对象结构误差；不修改原控制器。";""; ...
    "## 已完成结果";""; ...
    "- 工程：`"+C.project.root+"`"; ...
    "- 数据：`"+C.case_count+"` 个工况，`"+C.sample_count+"` 个有效 k→k+2 样本（上一周期 oracle 的公共交集 `"+C.common_sample_count+"`）。"; ...
    "- 基线：`"+C.baseline_passed+"/"+height(C.baseline)+"` 通过；Jd/Jq 上限均冻结为 `0.16 A^2`。"; ...
    "- 正式结论：**"+D.decision_code(1)+" — "+D.decision_label(1)+"**。"; ...
    "- 下一路线："+D.recommended_route(1)+"。该建议不会在本工程自动实现。"; ...
    "- 上游文档生成时校验：**"+C.freeze.status+"**，变化文件数 `"+num_or_na(C.freeze.changed_files)+"`。"; ...
    "- 图表：`"+C.figure_count+"/"+height(C.figureManifest)+"` 已生成。";""; ...
    "## 核心数值";""];
L=[L;predictor_metric_table(M,"全部 24 工况（含独立标记的 stress test）")];
L=[L;"";"A--F 门禁使用 `ENGINEERING_PRIMARY`（排除 stress test），其 P0 false-safe 为 **"+ ...
    rate_for(MP,"P0","false_safe_joint_rate")+"**；全量复现口径为 **"+ ...
    rate_for(M,"P0","false_safe_joint_rate")+"**。两个口径在所有报告中分开显示。";""; ...
    "## 一键运行";"";"```matlab";"cd('"+C.project.root+"')";"run_model_error_decomposition()";"```";""; ...
    "无参数等价于 `all`；还支持 `inventory`、`baseline`、`audit`、`prototype`。`prototype` 只记录禁止门禁。详见 [RUN_AND_REPRODUCE.md](RUN_AND_REPRODUCE.md)。";""; ...
    "## 证据入口";""; ...
    "- 逐样本主表：[`results/raw/model_error_samples.csv`](results/raw/model_error_samples.csv)"; ...
    "- 汇总目录：[`results/summary`](results/summary)"; ...
    "- 正式报告：[`docs/MODEL_ERROR_DECOMPOSITION_REPORT.md`](docs/MODEL_ERROR_DECOMPOSITION_REPORT.md)"; ...
    "- 决策：[`docs/DECISION_AND_NEXT_STEP.md`](docs/DECISION_AND_NEXT_STEP.md)"; ...
    "- 完整交接：[`HANDOFF.md`](HANDOFF.md)"; ...
    "- 15 类图：[`results/figures`](results/figures)";""; ...
    "## 解释边界";""; ...
    "P2c/P3c 使用当前周期未来端点，是非因果上界；P5 是对象重放下界；P2b/P3b/P4 需要真实对象参数。离线候选集是诊断 bank，不是 Zhou 连续几何候选空间，因此 ranking 只作次级证据。`di/dt=F+alpha*u` 还存在 gauge 不可辨识性，独立贡献只在本报告注册的物理拆分与 MSE/Shapley 口径内成立。"];
end

function L=handoff_document(C)
D=C.decision;P=C.project;M=C.metrics_all;MP=C.metrics_primary;O=C.contribution_primary;
L=["# HANDOFF — 完整工程交接";""; ...
    "生成时间：`"+C.generated_at+"`  "; ...
    "新工程：`"+P.root+"`";""; ...
    "## 1. 目标与边界";""; ...
    "本工程定量判断 Zhou ICF-MPC 移植到 IPMSM 后的独立电流约束误判，主要来自 F 估计、alpha 设置、两拍冻结/显式 Euler，还是剩余一阶模型结构。所有替换都发生在闭环之后的离线重放中。禁止修改控制器、重扫 608 个 Jd/Jq 点、重做 E1/E2、重做多矢量顺序研究，或实现 ESO/RLS/辨识器/高阶控制器。";""; ...
    "## 2. 前序研究链";""];
L=[L;upstream_table(C.upstreams,C.before,C.provenance);""; ...
    "前序已证明：平均电压与冻结 F 的逐段超局部预测差异占总残差约 `"+num_or_na(C.prior.sequence_ratio)+ ...
    "`，仅浮点量级；plant oracle 的模型项残差为 `"+num_or_na(C.prior.plant_model_rms_A)+ ...
    " A`；原平均预测 false-safe 为 `"+pct_or_na(C.prior.false_safe_rate)+ ...
    "`；平均预测到 plant oracle 的 top-1/模式翻转分别为 `"+pct_or_na(C.prior.top1_flip_rate)+ ...
    "` / `"+pct_or_na(C.prior.mode_flip_rate)+"`。因此 sequence 路线已经停止，本工程不重复它。";""; ...
    "## 3. 环境与入口";""; ...
    "- MATLAB：`"+C.matlab_release+"`。"; ...
    "- 依赖：MATLAB 基础运行时及当前工程 `src` 中逐字节复制的最小 Zhou/IPMSM/S2 runtime；不把任何兄弟工程加入路径。"; ...
    "- 主入口：`run_model_error_decomposition.m`。"; ...
    "- 一键命令：`cd('"+P.root+"'); run_model_error_decomposition();`"; ...
    "- 随机种子：`"+P.model_error.random_seed+"`；控制周期 `"+num_or_na(P.paper.Ts_s)+" s`；plant 重放步长 `"+num_or_na(P.model_error.integration_step_s)+" s`。";""; ...
    "## 4. P0--P5 定义与证据等级";""];
L=[L;predictor_definition_table();""; ...
    "时间因果并不等于可部署：P2a/P3a 要访问上一周期真实对象端点，P2b/P3b/P4 要知道真实参数，P1 也使用 oracle alpha。P2c/P3c 明确非因果，P5 是完全离线对象重放。任何 oracle 都没有反馈到闭环。";""; ...
    "## 5. 实际运行数据";""; ...
    "实际完成 `"+C.case_count+"` 个注册工况、`"+C.sample_count+"` 个样本；不是预计值，也不是从旧 CSV 复制的计数。工况含 9 个 core、5 个 dynamic、8 个 parameter、2 个 boundary/stress 条目；精确计数以表格为准。";""; ...
    case_table(C.caseInfo);""; ...
    "## 6. 主要结果";""];
L=[L;predictor_metric_table(M,"REPRODUCTION_ALL");""; ...
    "门禁主域 `ENGINEERING_PRIMARY` 排除明确 stress test。该主域的 F/alpha/结构有符号解释份额分别为 `"+ ...
    pct_or_na(O.F_share_of_explained)+"`、`"+pct_or_na(O.alpha_share_of_explained)+"`、`"+ ...
    pct_or_na(O.structure_share_of_explained)+"`；P0→P2b、P0→P1、P0→P3b 的 false-safe 绝对变化分别为 `"+ ...
    signed_pct(D.F_false_safe_drop)+"`、`"+signed_pct(D.alpha_false_safe_drop)+"`、`"+signed_pct(D.joint_false_safe_drop)+"`。";""; ...
    "候选诊断的 F、alpha、结构 top-1 恢复率分别为 `"+pct_or_na(D.F_top1_recovery_rate)+"`、`"+ ...
    pct_or_na(D.alpha_top1_recovery_rate)+"`、`"+pct_or_na(D.structure_top1_recovery_rate)+ ...
    "`；它们只用于确认误差是否可能跨越决策边界，不是主要归因证据。";""; ...
    "## 7. 正式结论与下一路线";""; ...
    "**"+D.decision_code(1)+" — "+D.decision_label(1)+"**。推荐："+D.recommended_route(1)+ ...
    "。当前工程到此停止，不实现建议算法。";""; ...
    "## 8. 核心产物";""; ...
    "- 逐样本：`"+C.raw_csv+"`"; ...
    "- 汇总：`"+C.summary_root+"`（8 个注册 CSV，另含 `final_decision.csv` 和审计表）。"; ...
    "- 图片：`"+C.figure_root+"`，已生成 `"+C.figure_count+"/"+height(C.figureManifest)+"`。"; ...
    "- 正式报告：`"+fullfile(P.dirs.docs,'MODEL_ERROR_DECOMPOSITION_REPORT.md')+"`"; ...
    "- 重现说明：`"+fullfile(P.root,'RUN_AND_REPRODUCE.md')+"`";""; ...
    "## 9. SHA256 与隔离";""; ...
    "文档生成时逐文件比较状态为 **"+C.freeze.status+"**：BEFORE `"+num_or_na(C.freeze.before_files)+ ...
    "` 个文件，AFTER `"+num_or_na(C.freeze.after_files)+"` 个文件，变化 `"+num_or_na(C.freeze.changed_files)+ ...
    "`。`all` 流程随后由 `finalize_freeze` 再次断言并写入 `FROZEN_UPSTREAM_VALIDATION.csv`。复制来源共 `"+ ...
    height(C.provenance)+"` 个最小依赖/证据文件，逐字节一致失败数 `"+copy_failures(C.provenance)+"`。";""; ...
    "## 10. 如何增加工况";""; ...
    "只在当前工程的本地 `config/sequence_scenarios.m` 增加一个具名、分类、带 `range_class` 的行；不要改上游。换过工况集合后必须更新注册样本计数或 audit version、清除对应本地 MAT cache、重新运行 `all`，并同时检查 baseline、P0/P5 对齐、频谱相干窗、决定门禁和 SHA256。压力点必须继续独立标记，不能主导工程结论。";""; ...
    "## 11. 未完成事项与禁止项";""; ...
    "未完成事项仅是结论所指向的下一独立项目；本工程的 P0--P5、汇总、15 类图和 A--F 决策已经完成。严禁修改五个冻结上游、将 P2c/P3c/P5 称为可部署控制器、把相关性当因果、把诊断候选 ranking 当原生控制器结果、无条件收紧 Jd/Jq，或在本目录加入新控制算法。";""; ...
    "主域 P0 false-safe：**"+rate_for(MP,"P0","false_safe_joint_rate")+"**；全量 P0 false-safe：**"+ ...
    rate_for(M,"P0","false_safe_joint_rate")+"**。所有最终数字应从 CSV 重读，不从本文手工转录。"];
end

function L=changelog_document(C)
L=["# CHANGELOG";""; ...
    "## "+C.generated_at+" — v"+C.project.model_error.version;""; ...
    "- 建立完全隔离的 `zhou_icf_mpc_model_error_decomposition_iter01`。"; ...
    "- 冻结并登记五个上游，生成 BEFORE/AFTER SHA256 和最小复制 provenance；文档生成时变化数为 `"+num_or_na(C.freeze.changed_files)+"`。"; ...
    "- 复现 `"+C.baseline_passed+"/"+height(C.baseline)+"` 项基线门禁。"; ...
    "- 对 `"+C.case_count+"` 个工况、`"+C.sample_count+"` 个样本完成 P0、P1、P2a/b/c、P3a/b/c、P4、P5 两拍预测。"; ...
    "- 加入 F/alpha gauge 审计字段、P0 公式复现、P5 对象复现、selected(k)=applied(k+1) 和候选 P5 步长收敛断言。"; ...
    "- 生成 8 个注册汇总 CSV、离线诊断候选比较、整数电气周期频谱、状态相关性与 15 类图片。"; ...
    "- 按预注册门禁给出结论 `"+C.decision.decision_code(1)+"`："+C.decision.decision_label(1)+"。"; ...
    "- prototype 保持关闭；未修改闭环控制器，也未加入 ESO/RLS/高阶或经验收紧方法。"];
end

function L=reproduce_document(C)
R=C.project.root;
L=["# Run and Reproduce";""; ...
    "## 环境";""; ...
    "已验证环境：`"+C.matlab_release+"`，Windows。入口会恢复 MATLAB 默认路径，清理 classes/functions/MEX，只添加当前工程的 `config`、`src`、`audit`、`tests`。不要提前把兄弟 Zhou 工程加入 `startup.m`。";""; ...
    "## 完整一键运行";"";"```matlab";"cd('"+R+"')";"outcome = run_model_error_decomposition();";"```";""; ...
    "等价显式写法：";"";"```matlab";"cd('"+R+"')";"outcome = run_model_error_decomposition('all');";"```";""; ...
    "`all` 顺序执行 inventory → baseline → audit → frozen-upstream finalization → prototype-disabled gate。它不修改控制器。";""; ...
    "## 分阶段命令";"";"```matlab";"cd('"+R+"')"; ...
    "run_model_error_decomposition('inventory'); % 上游盘点、BEFORE SHA、复制来源"; ...
    "run_model_error_decomposition('baseline');  % inventory + 10 项基线"; ...
    "run_model_error_decomposition('audit');     % 需要已经通过 baseline"; ...
    "run_model_error_decomposition('prototype'); % 只记录 BLOCKED_BY_SCOPE";"```";""; ...
    "## 确定性与 cache";""; ...
    "固定随机种子为 `"+C.project.model_error.random_seed+"`。每个场景的本地 checkpoint 位于 `results/raw/mat`，只有 `audit_version`、场景 id 和关键字段均匹配时才复用。要强制从零重放，可在确认路径是当前新工程后删除该目录内的 `*_model_error.mat`；绝对不要删除或覆盖上游结果。";""; ...
    "## 成功判据";""; ...
    "- `results/summary/baseline_comparison.csv` 的 `pass` 全为 1。"; ...
    "- `results/summary/repeatability_check.csv` 的 `pass` 全为 1。"; ...
    "- P0 recompute gap ≤ `"+num_or_na(C.project.model_error.predictor_tolerance_A)+" A`。"; ...
    "- P5 replay gap ≤ `"+num_or_na(C.project.model_error.plant_replay_tolerance_A)+" A`。"; ...
    "- `FROZEN_UPSTREAM_VALIDATION.csv` 的 `status` 全为 `unchanged`。"; ...
    "- `results/figures/figure_manifest.csv` 的 `generated` 全为 1。";""; ...
    "本次完成值：baseline `"+C.baseline_passed+"/"+height(C.baseline)+"`，工况 `"+C.case_count+ ...
    "`，样本 `"+C.sample_count+"`，图片 `"+C.figure_count+"/"+height(C.figureManifest)+"`，结论 `"+C.decision.decision_code(1)+"`。"];
end

function L=scope_document(C)
L=["# Project Scope";""; ...
    "## 研究问题";""; ...
    "在相同闭环轨迹和相同 k→k+2 电压命令下，通过 P0--P5 逐级替换，判断独立 d/q 电流约束 false-safe 主要来自 F 估计、alpha 输入增益、两拍 F/状态冻结与显式 Euler，还是对象重放之外的实现问题。";""; ...
    "## 范围内";""; ...
    "- 五个冻结上游的只读盘点、逐文件 SHA256 和最小依赖复制。"; ...
    "- `"+C.case_count+"` 个具名工况、`"+C.sample_count+"` 个两拍对齐样本。"; ...
    "- P0/P1/P2a/P2b/P2c/P3a/P3b/P3c/P4/P5 离线预测、约束混淆、候选诊断、相关性和相干频谱。"; ...
    "- A--F 预注册门禁，只建议下一项目。";""; ...
    "## 明确排除";""; ...
    "- 不重扫 Jd/Jq；固定 `Jd_limit = Jq_limit = 0.16 A^2`。"; ...
    "- 不重新证明平均电压与逐段冻结-F 超局部预测的等价性。"; ...
    "- 不重新实现 E1/E2，不无条件收紧电流约束。"; ...
    "- 不修改原 Zhou 控制器，不在闭环中切换预测器。"; ...
    "- 不实现 ESO、RLS、在线参数辨识、神经网络、高阶或扩展仿射控制器。"; ...
    "- 不把 oracle 结果包装成部署方案。";""; ...
    "## 完成定义";""; ...
    "基线全过、P0/P5 对齐断言全过、注册 CSV 与 15 类图齐全、正式结论唯一、冻结上游变化为零。当前数据给出的唯一结论为 **"+ ...
    C.decision.decision_code(1)+" — "+C.decision.decision_label(1)+"**。"];
end

function L=previous_document(C)
L=["# Previous Work Inventory";""; ...
    "本表盘点的是冻结证据，不把旧结果冒充本工程新实验。五个上游均保持只读。";""; ...
    upstream_table(C.upstreams,C.before,C.provenance);""; ...
    "## 已经建立的先验";""; ...
    "1. IPMSM 基础工程给出可运行 Zhou 控制器、对象、指标和已接受基线。"; ...
    "2. S2 工程已经完成矩形--六边形求交、S2 触发和非法作用时间门禁，本工程只复用最终命令。"; ...
    "3. robust residual 工程已经定义 k→k+2 残差对齐、场景分组和历史残差数据；本工程不重复 E1/E2 边界。"; ...
    "4. sequence decomposition 已经证明冻结同一 F/alpha 时，平均电压预测与逐段等效电压预测的差异仅为浮点量级；sequence/total 比为 `"+ ...
    num_or_na(C.prior.sequence_ratio)+"`，model/total 比为 `"+num_or_na(C.prior.model_ratio)+"`。"; ...
    "5. sequence decomposition 的 plant oracle 模型残差为 `"+num_or_na(C.prior.plant_model_rms_A)+ ...
    " A`，原预测 false-safe `"+pct_or_na(C.prior.false_safe_rate)+"`，平均→plant top-1/模式翻转 `"+ ...
    pct_or_na(C.prior.top1_flip_rate)+"` / `"+pct_or_na(C.prior.mode_flip_rate)+"`。"; ...
    "6. Jd/Jq audit 的 608 点扫描已经完成；本工程不再次运行。";""; ...
    "## 可直接复用";""; ...
    "场景定义、控制器/plant/S2 最小 runtime、时间对齐约定、候选诊断 bank 语义、上游报告和既有 sequence baseline 可直接作为冻结输入或门禁证据。";""; ...
    "## 必须重新仿真的字段";""; ...
    "P0--P5 的逐样本预测、匹配 alpha gauge 的上一周期/当前周期 F oracle、P4 刷新斜率、P5 两段对象重放、每个预测器的 Jd/Jq/confusion、候选重排序、相关性和频谱均须由本工程本地轨迹产生。本次实际生成 `"+ ...
    C.sample_count+"` 行，而非从 sequence CSV 拼接。";""; ...
    "## 为什么不重复 sequence 工程";""; ...
    "sequence 工程回答的是“多矢量执行顺序/平均化是否造成误差”；答案是否定的。当前工程回答的是在该等价性成立后，`F+alpha*u` 内部哪一部分以及 Euler/冻结假设造成对象差异。研究问题、预测器阶梯、输出字段和 A--F 门禁均不同。"];
end

function L=duplicate_document(C)
L=["# Duplicate Work Check";""; ...
    "## 结论";""; ...
    "**未发现上游已经完整实现本项目。允许且已经完成新增开发。**";""; ...
    "## 检查范围";""; ...
    "检查五个上游的 README/HANDOFF/正式报告、sequence 的 sample/candidate/residual CSV、robust residual 数据定义、S2 报告、场景配置和复制到 `reference/upstream_snapshots` 的证据。BEFORE 快照覆盖 `"+ ...
    height(C.before)+"` 个文件。";""; ...
    "## 已存在但不重复的内容";""; ...
    "- k/k+1/k+2、selected(k)=applied(k+1)、电角度和两周期命令对齐已有先验，本工程把它们作为断言复核。"; ...
    "- average vs piecewise frozen-F ultralocal 的 sequence 项已证明为 `"+num_or_na(C.prior.sequence_ratio)+"` 量级，本工程不再把它列为误差源。"; ...
    "- plant oracle 曾证明可复现 actual；本工程 P5 只作为每个新样本的对齐下界再次断言。"; ...
    "- 旧 24 场景定义可复用，但 P0--P5 字段必须本地重新生成。";""; ...
    "## 上游缺口";""; ...
    "上游没有同时提供：P1 oracle alpha、P2a/b/c 三类 F、P3a/b/c 匹配 gauge 的联合替换、P4 刷新物理斜率、逐级 MSE/Shapley 归因、同一诊断候选 bank 的 P0--P5 重排，以及基于这些量的 A--F 门禁。因此本工程不是 sequence_decomposition_iter01 的复制。";""; ...
    "## 防回退门禁";""; ...
    "若未来上游出现同版本、同公式、同样本键、同汇总和同决定表的完整 P0--P5 工程，应停止再次实现，只做逐字节与数值复核。当前本地输出结论为 `"+ ...
    C.decision.decision_code(1)+"`，对应本工程首次注册的内部归因。"];
end

function L=source_document(C)
L=["# Source Project Inventory";""; ...
    "## 冻结上游";"";upstream_table(C.upstreams,C.before,C.provenance);""; ...
    "## SHA256 状态";""; ...
    "- BEFORE 文件：`"+num_or_na(C.freeze.before_files)+"`。"; ...
    "- AFTER 文件：`"+num_or_na(C.freeze.after_files)+"`。"; ...
    "- 新增/删除/修改总数：`"+num_or_na(C.freeze.changed_files)+"`。"; ...
    "- 文档生成时判断：**"+C.freeze.status+"**。"; ...
    "- 比较说明："+C.freeze.detail;""; ...
    "`all` 模式在文档之后仍执行 `finalize_freeze` 强断言，并生成 `SOURCE_SHA256_AFTER.csv` 和 `FROZEN_UPSTREAM_VALIDATION.csv`。任何非零变化都会使运行失败。";""; ...
    "## 最小复制闭包";""; ...
    "COPIED_FILE_PROVENANCE 共 `"+height(C.provenance)+"` 行，逐字节一致失败 `"+copy_failures(C.provenance)+"`。运行代码仅包含本项目需要的 `+zhou_ipmsm`、`+zhou_feasibility`、`+zhou_iter11_ref`、一个 robust case runner、sequence 参考分解器、配置及冻结报告快照。复制文件的原路径、相对路径、大小、时间、SHA256、目标路径和用途均在根目录 CSV 中。";""; ...
    "## 路径原则";""; ...
    "所有 MATLAB 查询必须解析到 `"+C.project.root+"` 内。上游绝对路径只用于只读 inventory/hash；运行时不 `addpath` 上游。详见 `PATH_CONFLICT_REPORT.md` 与 `audit/path_resolution.csv`。"];
end

function L=original_document(C)
T=C.T;L=["# Original Predictor Definition (P0)";""; ...
    "## 连续模型与离散式";""; ...
    "原 Zhou 一阶超局部模型逐轴为 `di_d/dt = F_d + alpha_d u_d`、`di_q/dt = F_q + alpha_q u_q`。在控制行 k：";""; ...
    "```text"; ...
    "i_hat(k+1|k) = i_meas(k) + Ts [Fhat(k) + alpha_original .* u_pending_eq(k)]"; ...
    "i_hat(k+2|k) = i_hat(k+1|k) + Ts [Fhat(k) + alpha_original .* u_selected_eq(k)]"; ...
    "Jd = [id_ref(k) - id_hat(k+2|k)]^2"; ...
    "Jq = [iq_ref(k) - iq_hat(k+2|k)]^2";"```";""; ...
    "`Ts = "+num_or_na(C.project.paper.Ts_s)+" s`；Fhat 和 alpha 在两次 Euler 更新中均冻结。P0 的本地重算与控制器记录最大差见 `predictor_assertion_audit.csv`，必须 ≤ `"+ ...
    num_or_na(C.project.model_error.predictor_tolerance_A)+" A`。";""; ...
    "## Fhat";""; ...
    "Fhat(k) 是 trailing-history 的 Fliess--Join algebraic integral；窗口为 `"+C.project.assumptions.estimator_window_samples+ ...
    "` 个完整电压区间（6 个电流端点），电流作分段线性积分、电压作 ZOH。它使用截至 k 的历史，因此是当前行可用的因果估计，但不是简单的“上一周期差分 F”。代码没有额外 IIR 低通。启动时按冻结初值处理，`F_estimator_warmup` 单独标记。";""; ...
    "## alpha";""; ...
    "原 alpha 来自 controller/paper 参数，两个轴真正独立。本批样本的 `alpha_d_original` 范围为 `"+ ...
    range_text(T.alpha_d_original)+"`，`alpha_q_original` 为 `"+range_text(T.alpha_q_original)+ ...
    "`；真实对象的 `1/Ld_actual`、`1/Lq_actual` 范围分别为 `"+range_text(T.alpha_d_oracle)+"`、`"+ ...
    range_text(T.alpha_q_oracle)+"`。原 alpha 不随 plant mismatch 自动改变。";""; ...
    "## 电压与角度";""; ...
    "P0 不把 S2 输出压成单一静止电压再忽略转角，而是对实际 pending(k) 和最终 selected(k) 命令，按每个执行段的中点电角度变换到 dq 并求周期等效电压。pending 使用 delay=0；selected 使用 delay=1。几何选择使用冻结实现的 execution-segment-midpoint 约定。";""; ...
    "## 参数失配位置";""; ...
    "参数场景只缩放 plant 的 Ld/Lq；controller 参数仍为冻结 nominal。因此 P06/P07 的“controller high/low”是相对真实对象而言，不是同时修改两侧。Rs、psi、测量噪声、角度误差、dead time 在本轮主归因中不注入。";""; ...
    "## 约束拍点";""; ...
    "约束用 ref(k) 对比 `k+2|k` 预测。实际标签用同一 ref(k) 对比 trace 的 actual(k+2)。因此 false-safe 不是 k+1 与 k+2 混用。"];
end

function L=timing_document(C)
A=safe_read(fullfile(C.project.dirs.summary,'predictor_assertion_audit.csv'));
L=["# Timing Alignment Audit";""; ...
    "## 注册时间线";""; ...
    "| 位置 | 状态/命令 | 用途 |";"|---|---|---|"; ...
    "| row k | actual/measured i(k), theta(k), omega(k), Fhat(k), ref(k) | 所有预测的共同起点 |"; ...
    "| k→k+1 | `applied_sequence(k)`，也称 pending(k) | 第一拍；delay=0 的段中点 dq 电压 |"; ...
    "| row k+1 | actual i(k+1) | P2c/P3c 未来端点；P4 只使用自己 Euler 得到的 i1 |"; ...
    "| k+1→k+2 | `selected_sequence(k)`，并断言等于 `applied_sequence(k+1)` | 第二拍；delay=1 |"; ...
    "| row k+2 | actual i(k+2) | 残差与真实 Jd/Jq 标签 |";""; ...
    "## 对齐断言";""];
if ~isempty(A)
    L=[L;assertion_table(A);""];
else
    L=[L;"`predictor_assertion_audit.csv` 不存在；这在正式 audit 输出中视为失败。";""];
end
L=[L; ...
    "- measured(k)=actual(k) 且 controller theta(k)=plant theta(k)，主归因排除测量/坐标污染。"; ...
    "- `selected(k)=applied(k+1)` 对每个样本逐命令、逐作用时间核对。"; ...
    "- P0 公式重算对齐控制器记录；P5 从 actual state(k) 连续执行 pending 和 selected 并对齐 actual(k+2)。"; ...
    "- 上一周期平均 F 使用 i(k)-i(k-1) 与 applied(k-1)；当前非因果平均 F 使用 i(k+1)-i(k) 与 pending(k)。"; ...
    "- P2c/P3c 的当前平均 F 只冻结到两拍预测，绝不反算 i(k+2)，所以它使第一拍闭合但不会把第二拍结果人为设成真值。";""; ...
    "## 已有 sequence 先验与本轮复核";""; ...
    "前序平均-vs-逐段 frozen-ultralocal 的 sequence/total 比为 `"+num_or_na(C.prior.sequence_ratio)+ ...
    "`。本轮不重新把执行顺序列为候选误差源，只用 P0 formula、command carry 和 P5 replay 三组独立断言防止时序回归。若 P5 不能在 `"+ ...
    num_or_na(C.project.model_error.plant_replay_tolerance_A)+" A` 内复现 actual，A--D 一律无效并应判 E。"];
end

function L=oracle_document(~)
L=["# Oracle Predictor Definition";""; ...
    "所有 oracle 仅离线计算，闭环始终执行 P0 已选择的命令。";""; ...
    predictor_definition_table();""; ...
    "## F oracle 公式";""; ...
    "```text"; ...
    "F_prev^(alpha)(k-1) = [i(k)-i(k-1)]/Ts - alpha .* u_applied_eq(k-1)"; ...
    "F_inst(k) = f_IPMSM(i(k), omega(k), Rs_actual, Ld_actual, Lq_actual, psi_actual)"; ...
    "F_current^(alpha)(k) = [i(k+1)-i(k)]/Ts - alpha .* u_pending_eq(k)";"```";""; ...
    "P2a/P3a 分别在 original/oracle alpha 的 gauge 下重算上一周期平均 F；P2c/P3c 同理在各自 alpha 下重算当前周期平均 F。P3a/P3c 不直接把 original-gauge F 和 oracle alpha 拼接为主要证据；`*_fixed_gauge` 字段只审计这种混搭会产生的差异。";""; ...
    "## gauge 不可辨识性";""; ...
    "从输入输出数据单独观察 `di/dt = F + alpha*u` 时，任取 `delta_alpha`，令 `alpha' = alpha + delta_alpha`、`F' = F - delta_alpha*u`，在该输入点可以保持同一斜率。因此“F 误差”和“alpha 误差”不是无条件可辨识的物理量。本文注册一个 canonical gauge：alpha oracle 固定为真实 `1/Ld,1/Lq`，F_inst 固定为 IPMSM 无输入漂移项；上一/当前平均 F 必须与所用 alpha 成对反算。F/alpha Shapley 贡献只在该 gauge 和本场景输入覆盖内解释。";""; ...
    "## 因果/部署分类";""; ...
    "- P0：实际可运行基线。"; ...
    "- P1：公式时间因果，但 oracle alpha 需要真实参数；是离线干预。"; ...
    "- P2a/P3a：只用上一完整周期，时间因果；仍依赖真实对象端点/参数定义，不等于现成 estimator。"; ...
    "- P2b/P3b/P4：不使用未来电流反算，但需要真实 plant 状态和参数，是机理 oracle。"; ...
    "- P2c/P3c：使用 i(k+1)，**非因果、不可部署**，只给当前平均 F 完美时的上界。"; ...
    "- P5：与对象相同的方程、参数、分段命令和 RK4 重放，**不可部署**，仅作记录/对齐下界。"];
end

function L=protocol_document(C)
L=["# Experiment Protocol";""; ...
    "## 注册设计";""; ...
    "闭环对每个场景只运行原 Zhou+S2 控制器；随后在相同 state(k)、pending(k)、selected(k)、ref(k) 上离线计算十个预测器。仿真时长 `"+ ...
    num_or_na(C.project.model_error.simulation_time_s)+" s`，steady 起点 `"+num_or_na(C.project.model_error.steady_window_start_s)+ ...
    " s`，控制周期 `"+num_or_na(C.project.paper.Ts_s)+" s`，对象重放子步 `"+num_or_na(C.project.model_error.integration_step_s)+" s`。";""; ...
    "## 实际场景";"";case_table(C.caseInfo);""; ...
    "共 `"+C.case_count+"` 个场景、`"+C.sample_count+"` 个 k→k+2 样本。提前触发保护的轨迹保留其有效动态样本并标记 truncated；stress test 不进入 A--F 主域。";""; ...
    "## 替换与比较";""; ...
    "在全部样本上计算 residual/J/confusion；涉及 P2a/P3a 的 MSE 分解使用所有预测器均有限的公共交集。F 收益比较 P0→P2a/P2b，alpha 收益比较 P0→P1，联合比较 P0→P3a/P3b，冻结/离散链比较 P3b→P4→P5。P2c/P3c 只报告上界，不参与主要结论门禁和有效候选 ranking。";""; ...
    "## 候选诊断";""; ...
    "每个样本的 bank 含闭环 final selected、pre-S2 core、V0、六个满幅有功矢量和六个扇区三矢量中心，按命令 signature 去重。十个预测器在同一 bank 上按归一化 Jd+Jq 稳定排序。这个 bank 不是原 Zhou 连续矩形--六边形几何搜索，因此 top-1/top-3/mode 只回答“预测误差能否改变一个固定诊断选择”，不作为 A--F 主证据。P2c/P3c ranking 标为 invalid。P5 10-us 候选积分用抽样的 2-us 重排一致性检查。";""; ...
    "## 频谱";""; ...
    "只用 steady、定速、参考变化率近零且至少 3 个完整电气周期的尾部相干窗；矩形窗恰好包含整数周期，检查 1x/6x/12x 并记录前三主峰。无法形成整数周期或基波过小的行标 invalid，不用补零或泄漏窗口强行解释。";""; ...
    "## 重复性";"";repeatability_table(C.S.repeatability);""; ...
    "所有替换均为离线分析；没有任何 P1--P5 输出改变原轨迹、S2 触发或最终电压。"];
end

function L=metrics_document(C)
L=["# Metric Definitions";""; ...
    "## 预测残差与独立约束";""; ...
    "对预测器 p：`e_p,d = id_actual(k+2)-id_pred_p(k+2|k)`，`e_p,q` 同理；`Jd_p=[id_ref(k)-id_pred_p]^2`，`Jq_p` 同理。actual J 使用同一 ref(k) 与 actual(k+2)。预测 joint pass 当且仅当 Jd、Jq 均 ≤ `0.16 A^2`。";""; ...
    "- false-safe：预测 joint pass，actual joint fail。"; ...
    "- false-alarm：预测 joint fail，actual joint pass。"; ...
    "- RMS：`sqrt(mean(ed^2+eq^2))`；MSE 表中为 `mean(ed^2+eq^2)`。"; ...
    "- 最大连续 false-safe：逐 case 计算连续 true run，再取最大。"; ...
    "- S2-near：S2 触发行前后各 2 个样本。";""; ...
    "## 注册贡献量（有符号 MSE 差）";""; ...
    "```text"; ...
    "Delta_F_causal   = MSE(P0) - MSE(P2a)"; ...
    "Delta_F_instant  = MSE(P0) - MSE(P2b)"; ...
    "Delta_alpha      = MSE(P0) - MSE(P1)"; ...
    "Delta_joint      = MSE(P0) - MSE(P3b)"; ...
    "interaction      = MSE(P1)+MSE(P2b)-MSE(P0)-MSE(P3b)"; ...
    "F_Shapley        = 0.5*[(MSE(P0)-MSE(P2b))+(MSE(P1)-MSE(P3b))]"; ...
    "alpha_Shapley    = 0.5*[(MSE(P0)-MSE(P1))+(MSE(P2b)-MSE(P3b))]"; ...
    "two-period freeze= MSE(P3b)-MSE(P4)"; ...
    "Euler/segments   = MSE(P4)-MSE(P5)"; ...
    "structure total  = MSE(P3b)-MSE(P5)"; ...
    "remaining gap    = MSE(P5)";"```";""; ...
    "差值允许为负，负值表示该替换在注册数据上恶化，不能截断后再宣称收益。由于 F/alpha gauge，Shapley 是本 canonical physical split 下的对称归因，不是参数的普适可辨识证明。";""; ...
    "## 候选指标";""; ...
    "top-1/top-3/mode flip 均相对 P0；agreement/recovery 相对 P5。recovery 分母只包括 P0 与 P5 原本不同的 eligible 样本，new error 则记录 P0 原本与 P5 相同却被替换破坏的样本。P2c/P3c 因未来条件不进入有效 ranking。";""; ...
    "## 相关性与频谱";""; ...
    "Pearson/Spearman 和线性斜率只作描述；±10 样本互相关仅对 F/alpha 误差变量执行，其余变量显示 N/A（not evaluated）。因果判断必须来自 P0--P5 替换。频谱幅值为去均值残差的一侧 RMS，使用整数电气周期；1x 太小、参考变化、非定速或周期不足均标无效。";""; ...
    "## 汇总口径";""; ...
    "`REPRODUCTION_ALL` 包含全部 `"+C.sample_count+"` 样本；`ENGINEERING_PRIMARY` 排除 `range_class=stress_test`，用于 A--F 门禁；P2a/P3a 归因另使用所有预测器有限的公共交集 `"+C.common_sample_count+"`。三者不可混报。"];
end

function L=report_document(C)
D=C.decision;O=C.contribution_primary;
L=["# Model Error Decomposition Report";""; ...
    "## 摘要";""; ...
    "实际分析 `"+C.case_count+"` 个场景、`"+C.sample_count+"` 个样本。正式主域排除预先标记的 stress test；结论为 **"+ ...
    D.decision_code(1)+" — "+D.decision_label(1)+"**。";""; ...
    "前序 sequence 项已是浮点量级（sequence/total `"+num_or_na(C.prior.sequence_ratio)+"`），因此本报告只分解 F、alpha 与 P3b→P4→P5 的冻结/离散链。";""; ...
    "## 全量预测器表现";""];
L=[L;predictor_metric_table(C.metrics_all,"REPRODUCTION_ALL");""; ...
    "## 工程主域预测器表现";"";predictor_metric_table(C.metrics_primary,"ENGINEERING_PRIMARY");""; ...
    "## 主域 MSE 归因";"";contribution_table(O,C.predictors);""; ...
    "F、alpha、结构对 P0→P5 explained MSE 的有符号份额为 `"+pct_or_na(O.F_share_of_explained)+"`、`"+ ...
    pct_or_na(O.alpha_share_of_explained)+"`、`"+pct_or_na(O.structure_share_of_explained)+ ...
    "`。这是替换实验结果；相关性表只帮助定位工况，不承担因果结论。";""; ...
    "## 约束混淆（工程主域）";"";confusion_table(C.confusion_primary,C.predictors);""; ...
    "## 候选诊断（次级证据）";"";candidate_table(C.candidate_primary,C.predictors);""; ...
    "候选 bank 明确不是原生 Zhou candidates；P2c/P3c 的 ranking_valid=false。候选恢复只用于判断 RMSE 改善是否跨越诊断边界，不能单独决定 A--F。";""; ...
    "## 残差关联（描述性）";"";correlation_table(C.S.correlations);""; ...
    "上述相关性不得解释为因果。F 与 alpha 的 causal attribution 来自预测器替换，并受 gauge 约束。";""; ...
    "## 相干频谱";"";spectrum_table(C.S.spectrum);""; ...
    "无效窗口保留在 `residual_spectrum.csv` 并说明原因；没有用短窗谱峰填补证据。";""; ...
    "## 工况分类";"";case_table(C.caseInfo);""; ...
    "## 图表清单";"";figure_table(C.figureManifest);""; ...
    "## 证据分级";""; ...
    "- 可部署证据：只有 P0 基线本身和闭环真实轨迹；本工程没有部署新方法。"; ...
    "- 时间因果诊断：P2a/P3a（上一周期）以及公式层面的 P1，但仍含 oracle 参数/对象端点。"; ...
    "- 物理 oracle：P2b/P3b/P4，用真实对象参数，不是在线方案。"; ...
    "- 非因果上界：P2c/P3c。"; ...
    "- 理论重放下界：P5。"; ...
    "- 尚未验证推断：任何 ESO、预测型 F、在线 alpha、扩展仿射或高阶模型的实际闭环收益。"];
end

function L=decision_document(C)
D=C.decision;L=["# Decision and Next Step";""; ...
    "## 唯一正式结论";""; ...
    "# "+D.decision_code(1)+" — "+D.decision_label(1);""; ...
    "推荐下一路线：**"+D.recommended_route(1)+"**。这是下一独立项目建议，本工程不自动实现。";""; ...
    "## A--F 门禁";"";decision_gate_table(D);""; ...
    "## 决策量";""; ...
    "- 主域注册/公共样本：`"+D.registered_sample_count+"` / `"+D.common_sample_count+"`。"; ...
    "- F/alpha/structure 份额：`"+pct_or_na(D.F_share)+"` / `"+pct_or_na(D.alpha_share)+"` / `"+pct_or_na(D.structure_share)+"`。"; ...
    "- 多工况 material fraction：`"+pct_or_na(D.material_F_case_fraction)+"` / `"+pct_or_na(D.material_alpha_case_fraction)+"` / `"+pct_or_na(D.material_structure_case_fraction)+"`。"; ...
    "- P0→P2b/P1/P3b false-safe 绝对下降：`"+signed_pct(D.F_false_safe_drop)+"` / `"+signed_pct(D.alpha_false_safe_drop)+"` / `"+signed_pct(D.joint_false_safe_drop)+"`。"; ...
    "- F/alpha/structure top-1 recovery：`"+pct_or_na(D.F_top1_recovery_rate)+"` / `"+pct_or_na(D.alpha_top1_recovery_rate)+"` / `"+pct_or_na(D.structure_top1_recovery_rate)+"`（次级诊断）。"; ...
    "- stress false-safe event fraction：`"+pct_or_na(D.stress_false_safe_event_fraction)+"`。";""; ...
    "## 解释纪律";""; ...
    "决定主要依赖工程主域的替换 MSE、false-safe 和跨工况稳定性；候选 ranking 次之；Pearson/Spearman 不参与因果门禁。P2c/P3c 不进入主要门禁。若未来改变 gauge、候选 bank、工况主域或 Jd/Jq，上述决定必须重新注册和运行。";""; ...
    "## 下一项目映射";""; ...
    "A→F estimator bandwidth/predictive F/ESO；B→在线或调度 alpha_d/alpha_q；C→受计算量约束的扩展仿射；D→高阶/更精确离散；稳定 6x/12x→单独周期扰动审计；E→先修实现；F→停止超局部鲁棒改进。只有当前实际命中的 `"+ ...
    D.decision_code(1)+"` 路线被推荐，其他条目保留为审计映射。"];
end

function L=limitations_document(C)
truncated=sum(logical(C.caseInfo.truncated));eligible=sum(logical(C.caseInfo.steady_spectrum_eligible));
L=["# Known Limitations";""; ...
    "1. **F/alpha gauge 不可辨识。** `F+alpha*u` 可在单一输入点重新参数化；独立份额只在真实 `1/L` + 物理漂移的 canonical gauge、当前输入覆盖和注册 Shapley 口径内成立。"; ...
    "2. **P2c/P3c 非因果。** 它们用 i(k+1) 反算当前平均 F，只是第一拍完美闭合的理论上界，不能部署，候选 ranking 也标 invalid。"; ...
    "3. **P1/P2a/P2b/P3a/P3b/P4 也不是现成控制器。** 它们需要真实参数、真实对象端点或物理状态，时间因果性不等于工程可实现性。"; ...
    "4. **P5 是同模型重放。** 它验证记录、积分和时间对齐，不证明现实电机未建模效应可以被 oracle 消除。"; ...
    "5. **候选 bank 非原生。** 离线 bank 是固定诊断集合，不等价于 Zhou 的连续矩形--六边形几何选择；top-1/mode 恢复不是主要 A--F 证据。"; ...
    "6. **相关性不等于因果。** 状态/残差、delta_F、alpha mismatch、S2、模式等相关表仅描述联合变化。"; ...
    "7. **频谱有效域有限。** 只有 `"+eligible+"/"+height(C.caseInfo)+"` 个 case 被 case-level 标记为 steady-spectrum eligible；整数周期不足、基波过小或动态参考均不作谱结论。"; ...
    "8. **提前终止。** `"+truncated+"` 个场景只贡献终止前有效动态样本，不能假装有完整 steady window。"; ...
    "9. **简化对象。** 本轮主证据为定速、理想角度/测量、无 dead time/压降/噪声；torque ramp/step 是 dq current reference 映射，不是独立机械外环。"; ...
    "10. **参数覆盖有限。** Ld/Lq ±10%、组合与代表性 ±20% 是机理工况，不含无依据的剧烈随机跳变，也未建工作点饱和映射。"; ...
    "11. **固定约束与时域。** 结论只对 `Jd=Jq=0.16 A^2`、本次 `"+C.case_count+"` 场景和 `"+C.sample_count+"` 样本成立；没有重扫 Jd/Jq。"; ...
    "12. **下一算法未验证。** 结论映射出的 ESO/在线 alpha/高阶模型仍是假设，必须另建隔离工程再验证。"];
end

function ensure_supporting_documents(C)
pathFile=fullfile(C.project.dirs.docs,'PATH_CONFLICT_REPORT.md');
if ~isfile(pathFile)
    L=["# MATLAB Path Conflict Report";""; ...
        "状态：**FAIL — 缺少 path_audit 输出**。正式入口必须先运行 `zhou_model_error.path_audit` 并生成 `audit/path_resolution.csv`。"; ...
        "本工程要求所有 Zhou 查询只解析到 `"+C.project.root+"`，任何兄弟 `zhou_*` 路径均应终止运行。"];
    write_md(pathFile,L);
end
baselineFile=fullfile(C.project.dirs.docs,'BASELINE_REPRODUCTION_REPORT.md');
if ~isfile(baselineFile)
    L=["# Baseline Reproduction Report";""; ...
        "结果：**"+C.baseline_passed+"/"+height(C.baseline)+" 通过**；Jd/Jq 均为 `0.16 A^2`。";""; ...
        baseline_table(C.baseline)];
    write_md(baselineFile,L);
end
prototypeFile=fullfile(C.project.dirs.docs,'PROTOTYPE_GATE_REPORT.md');
if ~isfile(prototypeFile)
    L=["# Prototype Gate Report";""; ...
        "状态：**DISABLED_BY_DEFAULT**  ";"Prototype allowed: **false**";""; ...
        "本项目仅归因。结论 `"+C.decision.decision_code(1)+"` 可以建议下一独立研究，但不授权在此目录创建、调参或运行 ESO、RLS、辨识器、高阶/扩展仿射控制器。`prototype` 模式只记录 BLOCKED_BY_SCOPE。"];
    write_md(prototypeFile,L);
end
end

function L=predictor_definition_table()
L=["| 预测器 | F | alpha | 离散/对象 | 分类 |";"|---|---|---|---|---|"; ...
    "| P0 | 原 5 区间 algebraic Fhat，跨两拍冻结 | 原 alpha_d/q | 两拍 Euler、等效 pending/selected 电压 | 实际闭环基线 |"; ...
    "| P1 | 同 P0 Fhat | 1/Ld_actual, 1/Lq_actual | 同 P0 | oracle-alpha 离线干预 |"; ...
    "| P2a | 上一完整周期平均 F，original-alpha gauge | 原 alpha | 两拍冻结 F | 时间因果 oracle |"; ...
    "| P2b | k 时刻 IPMSM 物理漂移 F | 原 alpha | 两拍冻结 F | 当前物理 oracle |"; ...
    "| P2c | 用 i(k+1) 反算当前 pending 周期平均 F，original-alpha gauge | 原 alpha | 两拍冻结 F | **非因果上界** |"; ...
    "| P3a | 上一周期平均 F，按 oracle-alpha gauge 重算 | oracle alpha | 两拍冻结 F | 时间因果联合 oracle |"; ...
    "| P3b | k 时刻 IPMSM 物理漂移 F | oracle alpha | 两拍冻结 F | 当前物理联合 oracle |"; ...
    "| P3c | 当前 pending 周期平均 F，按 oracle-alpha gauge 重算 | oracle alpha | 两拍冻结 F | **非因果联合上界** |"; ...
    "| P4 | k 物理 F；第一拍预测后在 i1 重新计算 F | oracle alpha | 每拍显式 Euler | 刷新局部物理模型 |"; ...
    "| P5 | plant 方程隐含的连续漂移 | actual plant | 逐段命令、同对象 RK4 | 离线对象重放下界 |"]; 
end

function L=predictor_metric_table(M,label)
L=["口径：**"+label+"**";""; ...
    "| Predictor | Causality | valid n | vector RMS (A) | peak (A) | false-safe | false-alarm | max FS run | top-1 flip vs P0 | mode flip vs P0 |"; ...
    "|---|---|---:|---:|---:|---:|---:|---:|---:|---:|"];
if isempty(M),L=[L;"| unavailable | unavailable | 0 | N/A | N/A | N/A | N/A | 0 | N/A | N/A |"];return,end
names=unique(M.predictor,'stable').';
for p=names
    r=M(find(M.predictor==p,1),:);
    L(end+1)="| "+esc(p)+" | "+esc(r.causality_class)+" | "+r.valid_sample_count+" | "+ ...
        num_or_na(r.vector_rms_A)+" | "+num_or_na(r.vector_peak_A)+" | "+ ...
        pct_or_na(r.false_safe_joint_rate)+" | "+pct_or_na(r.false_alarm_joint_rate)+" | "+ ...
        num_or_na(r.maximum_consecutive_false_safe)+" | "+pct_or_na(r.top1_flip_vs_P0_rate)+" | "+ ...
        pct_or_na(r.mode_flip_vs_P0_rate)+" |"; %#ok<AGROW>
end
end

function L=contribution_table(O,names)
L=["| Predictor | vector MSE (A^2) |";"|---|---:|"];
for p=names
    field="MSE_"+p+"_A2";L(end+1)="| "+p+" | "+num_or_na(O.(field))+" |"; %#ok<AGROW>
end
L=[L;"";"| Registered delta | A^2 |";"|---|---:|"; ...
    "| F causal: P0-P2a | "+num_or_na(O.Delta_F_causal_A2)+" |"; ...
    "| F instant: P0-P2b | "+num_or_na(O.Delta_F_instant_A2)+" |"; ...
    "| alpha: P0-P1 | "+num_or_na(O.Delta_alpha_A2)+" |"; ...
    "| joint instant: P0-P3b | "+num_or_na(O.Delta_joint_instant_A2)+" |"; ...
    "| F-alpha interaction | "+num_or_na(O.Delta_F_alpha_interaction_excess_A2)+" |"; ...
    "| two-period F freezing: P3b-P4 | "+num_or_na(O.Delta_two_period_F_freezing_A2)+" |"; ...
    "| discretization/segments: P4-P5 | "+num_or_na(O.Delta_discretization_structure_A2)+" |"; ...
    "| structure total: P3b-P5 | "+num_or_na(O.Delta_structure_total_A2)+" |"; ...
    "| remaining oracle gap: P5 | "+num_or_na(O.Delta_remaining_oracle_gap_A2)+" |"]; 
end

function L=confusion_table(Q,names)
L=["| Predictor | n | false-safe count/rate | false-alarm count/rate | violation recall | safe specificity |"; ...
    "|---|---:|---:|---:|---:|---:|"];
for p=names
    r=Q(find(Q.predictor==p,1),:);
    if isempty(r),continue,end
    L(end+1)="| "+p+" | "+r.sample_count+" | "+r.false_safe_count+" / "+pct_or_na(r.false_safe_rate)+ ...
        " | "+r.false_alarm_count+" / "+pct_or_na(r.false_alarm_rate)+" | "+pct_or_na(r.violation_recall)+ ...
        " | "+pct_or_na(r.safe_specificity)+" |"; %#ok<AGROW>
end
end

function L=candidate_table(Q,names)
L=["| Predictor | valid n | top-1 flip | mode flip | P5 agreement | top-1 recovered/eligible | mode recovered/eligible | new top-1 errors |"; ...
    "|---|---:|---:|---:|---:|---:|---:|---:|"];
for p=names
    r=Q(find(Q.predictor==p,1),:);if isempty(r),continue,end
    L(end+1)="| "+p+" | "+r.sample_count+" | "+pct_or_na(r.top1_flip_vs_P0_rate)+" | "+ ...
        pct_or_na(r.mode_flip_vs_P0_rate)+" | "+pct_or_na(r.top1_agreement_with_P5_rate)+" | "+ ...
        num_or_na(r.top1_recovered_count)+" / "+num_or_na(r.top1_recovery_eligible_count)+" | "+ ...
        num_or_na(r.mode_recovered_count)+" / "+num_or_na(r.mode_recovery_eligible_count)+" | "+ ...
        num_or_na(r.top1_new_error_count)+" |"; %#ok<AGROW>
end
end

function L=case_table(Q)
L=["| Case | Category | Range | rpm | id* | iq* | Vdc | samples | S2 | P0 FS | P5 max gap (A) | Notes |"; ...
    "|---|---|---|---:|---:|---:|---:|---:|---:|---:|---:|---|"];
for k=1:height(Q)
    L(end+1)="| "+esc(Q.case_id(k))+" | "+esc(Q.case_category(k))+" | "+esc(Q.range_class(k))+ ...
        " | "+num_or_na(Q.speed_rpm(k))+" | "+num_or_na(Q.id_ref_A(k))+" | "+num_or_na(Q.iq_ref_A(k))+ ...
        " | "+num_or_na(Q.dc_bus_V(k))+" | "+Q.effective_samples(k)+" | "+Q.S2_cycles(k)+" | "+ ...
        pct_or_na(Q.P0_false_safe_rate(k))+" | "+num_or_na(Q.P5_replay_max_gap_A(k))+" | "+esc(Q.notes(k))+" |"; %#ok<AGROW>
end
end

function L=upstream_table(U,B,P)
L=["| Upstream | Absolute path | Evidence | hashed files | copied files |";"|---|---|---|---:|---:|"];
for k=1:height(U)
    name=U.upstream_project(k);nHash=count_equal(B,'upstream_project',name);nCopy=count_equal(P,'upstream_project',name);
    L(end+1)="| "+esc(name)+" | `"+U.absolute_path(k)+"` | "+esc(U.content_evidence(k))+" | "+nHash+" | "+nCopy+" |"; %#ok<AGROW>
end
end

function L=assertion_table(A)
L=["| Case | n | P0 max gap (A) | P5 max gap (A) | prev-F closure | acausal-F closure | P4 identity | carry pass |"; ...
    "|---|---:|---:|---:|---:|---:|---:|---:|"];
for k=1:height(A)
    L(end+1)="| "+esc(A.case_id(k))+" | "+A.sample_count(k)+" | "+num_or_na(A.P0_recompute_max_gap_A(k))+ ...
        " | "+num_or_na(A.P5_replay_max_gap_A(k))+" | "+num_or_na(A.previous_F_closure_max_A(k))+ ...
        " | "+num_or_na(A.acausal_F_closure_max_A(k))+" | "+num_or_na(A.P4_identity_max_gap_A(k))+ ...
        " | "+logical_text(A.command_carry_pass(k))+" |"; %#ok<AGROW>
end
end

function L=repeatability_table(R)
L=["| Check | Pass | Observation | Requirement |";"|---|---:|---|---|"];
for k=1:height(R)
    L(end+1)="| "+esc(R.names(k))+" | "+logical_text(R.pass(k))+" | "+esc(R.observed(k))+" | "+esc(R.requirement(k))+" |"; %#ok<AGROW>
end
end

function L=baseline_table(B)
L=["| Check | Pass | Observation | Requirement |";"|---|---:|---|---|"];
for k=1:height(B)
    L(end+1)="| "+esc(B.check(k))+" | "+logical_text(B.pass(k))+" | "+esc(B.observed(k))+" | "+esc(B.requirement(k))+" |"; %#ok<AGROW>
end
end

function L=correlation_table(R)
Q=R(R.cohort=="ALL"&R.window_type=="all"&R.variable_type=="numeric"&R.valid,:);
if isempty(Q),L="No valid aggregate numeric correlation rows.";return,end
[~,ix]=sort(abs(Q.pearson_r),'descend');Q=Q(ix(1:min(12,height(Q))),:);
L=["| Axis | Variable | n | Pearson r | Spearman r | best |xcorr| | lag |";"|---|---|---:|---:|---:|---:|---:|"];
for k=1:height(Q)
    L(end+1)="| "+Q.axis(k)+" | "+esc(Q.explanatory_variable(k))+" | "+Q.sample_count(k)+" | "+ ...
        num_or_na(Q.pearson_r(k))+" | "+num_or_na(Q.spearman_r(k))+" | "+ ...
        num_or_na(Q.best_abs_cross_correlation(k))+" | "+num_or_na(Q.best_lag_samples(k))+" |"; %#ok<AGROW>
end
end

function L=spectrum_table(R)
Q=R(R.predictor=="P0"&R.spectrum_valid,:);
if isempty(Q),L="No P0 spectrum row met the coherent-window validity gate.";return,end
L=["| Case | Axis | cycles | n | 1x RMS | 6x RMS | 12x RMS | dominant order/amplitude |"; ...
    "|---|---|---:|---:|---:|---:|---:|---:|"];
for k=1:height(Q)
    L(end+1)="| "+esc(Q.case_id(k))+" | "+Q.axis(k)+" | "+num_or_na(Q.electrical_cycle_count(k))+ ...
        " | "+Q.sample_count(k)+" | "+num_or_na(Q.order1_rms_A(k))+" | "+num_or_na(Q.order6_rms_A(k))+ ...
        " | "+num_or_na(Q.order12_rms_A(k))+" | "+num_or_na(Q.dominant_order_1(k))+" / "+ ...
        num_or_na(Q.dominant_amplitude_1_A(k))+" |"; %#ok<AGROW>
end
end

function L=figure_table(F)
L=["| # | File | Generated | Message |";"|---:|---|---:|---|"];
for k=1:height(F)
    figureNumber=num_or_na(F.figure_number(k));
    fileName=string(F.file_name(k));
    message=string(F.message(k));
    L(end+1)="| "+figureNumber+" | [`"+esc(fileName)+"`](../results/figures/"+fileName+ ...
        ") | "+logical_text(F.generated(k))+" | "+esc(message)+" |"; %#ok<AGROW>
end
end

function L=decision_gate_table(D)
L=["| Gate | Passed | Meaning |";"|---|---:|---|"; ...
    "| A | "+logical_text(D.gate_A)+" | F estimation primary |"; ...
    "| B | "+logical_text(D.gate_B)+" | alpha input gain primary |"; ...
    "| C | "+logical_text(D.gate_C)+" | F and alpha jointly dominate |"; ...
    "| D | "+logical_text(D.gate_D)+" | freezing/discretization/first-order structure |"; ...
    "| E | "+logical_text(D.gate_E)+" | implementation/timing/metric defect |"; ...
    "| F | "+logical_text(D.gate_F)+" | no engineering-value route under gates |"]; 
end

function F=freeze_status(project,before)
F=struct('status',"UNAVAILABLE",'before_files',height(before),'after_files',NaN, ...
    'changed_files',NaN,'detail',"No comparable SHA256 snapshots were available.");
after=safe_read(fullfile(project.root,'SOURCE_SHA256_AFTER.csv'));
if isempty(after)&&~isempty(before)
    try
        after=zhou_model_error.snapshot_upstreams(project,"AFTER");
    catch ME
        F.status="HASH_FAILED";F.detail="AFTER snapshot failed: "+string(ME.message);return
    end
end
F.after_files=height(after);if isempty(before)||isempty(after),return,end
kb=before.upstream_project+"|"+before.relative_path;ka=after.upstream_project+"|"+after.relative_path;
[inAfter,locA]=ismember(kb,ka);changed=nnz(~inAfter);matched=find(inAfter);
if ~isempty(matched),changed=changed+nnz(before.sha256(matched)~=after.sha256(locA(matched)));end
changed=changed+nnz(~ismember(ka,kb));F.changed_files=changed;
if changed==0
    F.status="PASS";F.detail="Documentation-time BEFORE/AFTER key and SHA256 comparison found zero added, deleted, or modified upstream files.";
else
    F.status="FAIL";F.detail="Documentation-time comparison found "+changed+" added, deleted, or modified upstream files.";
end
end

function P=prior_sequence_evidence(project)
P=struct('sequence_ratio',NaN,'model_ratio',NaN,'plant_model_rms_A',NaN, ...
    'false_safe_rate',NaN,'top1_flip_rate',NaN,'mode_flip_rate',NaN);
base=fullfile(project.root,'reference','upstream_snapshots','sequence_decomposition');
D=safe_read(fullfile(base,'final_decision.csv'));
if ~isempty(D)
    P.sequence_ratio=value_if_present(D,'sequence_ul_to_total_ratio',P.sequence_ratio);
    P.model_ratio=value_if_present(D,'model_ul_to_total_ratio',P.model_ratio);
    P.false_safe_rate=value_if_present(D,'avg_false_safe_rate',P.false_safe_rate);
    P.top1_flip_rate=value_if_present(D,'top1_avg_plant_flip_rate',P.top1_flip_rate);
end
R=safe_read(fullfile(base,'residual_decomposition.csv'));
if ~isempty(R)
    q=R.case_id=="ALL";
    if any(q)
        P.sequence_ratio=R.sequence_ul_to_total_ratio(find(q,1));
        P.model_ratio=R.model_ul_to_total_ratio(find(q,1));
        P.plant_model_rms_A=R.model_plant_vector_rms_A(find(q,1));
    end
end
Q=safe_read(fullfile(base,'candidate_decision_comparison.csv'));
if ~isempty(Q)
    w=Q.sample_count;P.top1_flip_rate=weighted(Q.avg_plant_top1_flip_rate,w);
    P.mode_flip_rate=weighted(Q.avg_plant_mode_flip_rate,w);
end
end

function T=one_cohort(T,name)
T=T(T.cohort==name,:);
end

function T=safe_read(path)
if isfile(path)
    % Force CSV delimiter: automatic detection can mistake Windows path
    % backslashes in SOURCE_PROJECTS.csv for delimiters.
    T=readtable(path,'TextType','string','Delimiter',',','VariableNamingRule','preserve');
else
    T=table();
end
end

function v=value_if_present(T,name,default)
name=string(name);
if ismember(name,string(T.Properties.VariableNames)),v=T.(name)(1);else,v=default;end
end

function n=count_equal(T,field,value)
field=string(field);
if isempty(T)||~ismember(field,string(T.Properties.VariableNames)),n=0;else,n=nnz(T.(field)==value);end
end

function n=copy_failures(P)
if isempty(P)||~ismember("byte_identical",string(P.Properties.VariableNames)),n=NaN;else,n=nnz(~logical(P.byte_identical));end
end

function s=rate_for(M,p,field)
q=M.predictor==p;if any(q),s=pct_or_na(M.(field)(find(q,1)));else,s="N/A";end
end

function s=range_text(x)
x=x(isfinite(x));if isempty(x),s="N/A";else,s=num_or_na(min(x))+" .. "+num_or_na(max(x));end
end

function v=weighted(x,w)
keep=isfinite(x)&isfinite(w)&w>0;if any(keep),v=sum(x(keep).*w(keep))/sum(w(keep));else,v=NaN;end
end

function s=num_or_na(x)
if isempty(x)||~isscalar(x)||~isfinite(double(x)),s="N/A";else,s=string(sprintf('%.12g',double(x)));end
end

function s=pct_or_na(x)
if isempty(x)||~isscalar(x)||~isfinite(double(x)),s="N/A";else,s=string(sprintf('%.6f%%',100*double(x)));end
end

function s=signed_pct(x)
if isempty(x)||~isscalar(x)||~isfinite(double(x)),s="N/A";else,s=string(sprintf('%+.6f percentage points',100*double(x)));end
end

function s=logical_text(x)
if logical(x),s="PASS";else,s="FAIL";end
end

function s=esc(x)
s=string(x);s=replace(s,newline," ");s=replace(s,"|","\|");s=replace(s,"`","'");
end

function s=matlab_release()
try
    s="MATLAB "+string(version)+" ("+string(version('-release'))+")";
catch
    s="MATLAB "+string(version);
end
end

function write_md(path,lines)
lines=string(lines(:));writelines(lines,path,'Encoding','UTF-8');
assert(isfile(path),'ZhouModelError:DocumentationWrite','Failed to write %s.',path);
end
