function [audit,summary]=audit_original_illegal_cycles(project,simulation)
%AUDIT_ORIGINAL_ILLEGAL_CYCLES Set-only audit before closed-loop modification.

T=simulation.trace;rows=find(~logical(T.original_legal));
assert(~isempty(rows),'ZhouFeasibility:NoOriginalIllegalCycle', ...
    'The frozen A0 trace contains no illegal original command.');
n=numel(rows);records=cell(n,1);
for j=1:n
    k=rows(j);r=T(k,:);
    rect=zhou_ipmsm.geometry.build_rectangle(r.Vd,r.Vq, ...
        simulation.scenario.Jd_limit_A2,simulation.scenario.Jq_limit_A2, ...
        r.alpha_d,r.alpha_q,project.base.Ts_s,r.geometry_theta_rad, ...
        project.assumptions.geometry_tolerance);
    intersection=zhou_feasibility.rectangle_hexagon_intersection( ...
        rect,simulation.vectors,project.assumptions.voltage_tolerance_V);
    reference=[r.original_reference_alpha_V,r.original_reference_beta_V];
    vf=zhou_feasibility.voltage_feasibility(reference,simulation.vectors,struct(), ...
        project.assumptions.duty_tolerance);
    radial_ab=vf.radial_boundary_ab_V;
    radial_dq=zhou_ipmsm.math.park(radial_ab,rect.theta);
    radial_z=(radial_dq-rect.center_dq)./rect.half_dq;
    radial_inside_R=all(abs(radial_z)<=1+project.assumptions.voltage_tolerance_V);
    if intersection.nonempty
        nearest=zhou_feasibility.nearest_point_in_rectangle_hexagon_intersection( ...
            rect,simulation.vectors,project.assumptions.voltage_tolerance_V);
        near_ab=nearest.point_ab;near_dq=nearest.point_dq;
        ratios=((near_dq-rect.center_dq)./rect.half_dq).^2;
        command=zhou_feasibility.synthesize_feasible_three_vector_command( ...
            near_ab,project.base.Ts_s,simulation.vectors,project.assumptions);
        duties=command.duties;near_inside_R=nearest.inside_rectangle;
        near_inside_H=nearest.inside_hexagon;offset=norm(near_ab-reference);
    else
        near_ab=[NaN NaN];near_dq=[NaN;NaN];ratios=[NaN;NaN];
        duties=[NaN NaN NaN];near_inside_R=false;near_inside_H=false;offset=NaN;
    end
    radial_ratios=radial_z.^2;
    records{j}=table(string(project.run_id),r.t_s,r.dc_bus_V,r.voltage_vector_scale, ...
        r.active_vector_magnitude_V,r.reference_ramp_s,r.sampling_period_s,r.motor_model, ...
        r.Ld_H,r.Lq_H,r.alpha_mode,r.F_estimator,intersection.nonempty, ...
        intersection.area_V2,reference(1),reference(2),near_ab(1),near_ab(2), ...
        radial_ab(1),radial_ab(2),near_inside_R,near_inside_H,radial_inside_R, ...
        ratios(1)*simulation.scenario.Jd_limit_A2,ratios(2)*simulation.scenario.Jq_limit_A2, ...
        radial_ratios(1)*simulation.scenario.Jd_limit_A2, ...
        radial_ratios(2)*simulation.scenario.Jq_limit_A2,duties(1),duties(2),duties(3), ...
        min(duties),sum(duties),offset,norm(radial_ab-reference), ...
        'VariableNames',{'run_id','t_s','dc_bus_V','voltage_vector_scale', ...
        'active_vector_magnitude_V','reference_ramp_s','sampling_period_s','motor_model', ...
        'Ld_H','Lq_H','alpha_mode','F_estimator','intersection_nonempty', ...
        'intersection_area_V2','original_center_alpha_V','original_center_beta_V', ...
        'nearest_alpha_V','nearest_beta_V','radial_alpha_V','radial_beta_V', ...
        'nearest_inside_rectangle','nearest_inside_hexagon','radial_inside_rectangle', ...
        'nearest_Jd_A2','nearest_Jq_A2','radial_Jd_A2','radial_Jq_A2', ...
        'nearest_d0','nearest_d1','nearest_d2','nearest_minimum_duty','nearest_duty_sum', ...
        'nearest_offset_V','radial_offset_V'});
end
audit=vertcat(records{:});
preservable=audit.intersection_nonempty & audit.nearest_inside_rectangle & ...
    audit.nearest_inside_hexagon & audit.nearest_Jd_A2<=simulation.scenario.Jd_limit_A2+1e-12 & ...
    audit.nearest_Jq_A2<=simulation.scenario.Jq_limit_A2+1e-12 & audit.nearest_minimum_duty>=-1e-12;
summary=table(string(project.run_id),height(audit),nnz(preservable),mean(preservable), ...
    mean(audit.radial_inside_rectangle),min(audit.intersection_area_V2), ...
    'VariableNames',{'run_id','original_illegal_cycles','S2_preservable_cycles', ...
    'S2_preservable_fraction','radial_inside_rectangle_fraction','minimum_intersection_area_V2'});
end
