function [metrics, trace] = run_probe_case(cfg)
%RUN_PROBE_CASE Deterministic fixed-speed IPMSM current-loop simulation.
validate_probe_config(cfg);
n = cfg.steps;
omega_e = cfg.speed_rpm*2*pi/60*cfg.motor.pole_pairs;
current = zeros(2,1);
previous_current = current;
last_voltage_dq = zeros(2,1);
final_reference_dq = zhou_ipmsm.controller.build_current_reference(cfg.id_ref,cfg.iq_ref);

current_log = zeros(2,n);
reference_log = zeros(2,n);
torque = zeros(n,1);
magnet_torque = zeros(n,1);
reluctance_torque = zeros(n,1);
legal = false(n,1);
selected_legal = false(n,1);
negative_count = zeros(n,1);
selected_negative_count = zeros(n,1);
switching = zeros(n,1);
case_id = zeros(n,1);
selected_case_id = zeros(n,1);
constraint_d_ok = false(n,1);
constraint_q_ok = false(n,1);
geometry_inside = false(n,1);
saturation_used = false(n,1);
selected_saturation_used = false(n,1);
projection_error_V = zeros(n,1);
selected_projection_error_V = zeros(n,1);
vectors = zhou_ipmsm.inverter.voltage_vectors(cfg.Vdc);
pending_command = zhou_ipmsm.modulation.generate_case_sequence([0 0],cfg.Ts,vectors);

for sample = 1:n
    theta_e = mod((sample-1)*cfg.Ts*omega_e,2*pi);
    ramp = min(1,(sample-1)*cfg.Ts/max(cfg.reference_ramp_s,eps));
    reference_dq = final_reference_dq*ramp;
    control = zhou_ipmsm.controller.icf_mpc_step(current,previous_current, ...
        last_voltage_dq,pending_command,reference_dq,theta_e,omega_e,cfg,sample>1);
    applied_voltage_dq = zhou_ipmsm.controller.sequence_equivalent_dq_voltage( ...
        pending_command,vectors,theta_e,omega_e,0,cfg.Ts,cfg.assumptions.frame_mode);
    components = zhou_ipmsm.model.calculate_torque_components(current,cfg.motor);
    current_log(:,sample) = current;
    reference_log(:,sample) = reference_dq;
    torque(sample) = components.total;
    magnet_torque(sample) = components.magnet;
    reluctance_torque(sample) = components.reluctance;
    legal(sample) = pending_command.legal;
    selected_legal(sample) = control.command.legal;
    negative_count(sample) = nnz(pending_command.sequence_durations_s<0);
    selected_negative_count(sample) = nnz(control.command.sequence_durations_s<0);
    positive_duration = pending_command.sequence_durations_s>max(100*eps(cfg.Ts),1e-15);
    switching(sample) = zhou_ipmsm.inverter.count_switching_actions( ...
        pending_command.sequence_states(positive_duration,:));
    case_id(sample) = pending_command.case_id;
    selected_case_id(sample) = control.command.case_id;
    constraint_d_ok(sample) = control.constraint_satisfied_d;
    constraint_q_ok(sample) = control.constraint_satisfied_q;
    geometry_inside(sample) = control.geometry.synthesized_reference_inside_rectangle;
    saturation_used(sample) = pending_command.saturation_used;
    selected_saturation_used(sample) = control.command.saturation_used;
    projection_error_V(sample) = pending_command.projection_error_V;
    selected_projection_error_V(sample) = control.command.projection_error_V;

    previous_current = current;
    current = zhou_ipmsm.model.integrate_ipmsm_sequence_rk4(current, ...
        pending_command,vectors,theta_e,omega_e,cfg.motor,cfg.Ts);
    last_voltage_dq = applied_voltage_dq;
    pending_command = control.command;
end

tracking = zhou_ipmsm.metrics.calculate_tracking_metrics(current_log, ...
    reference_log);
switching_metrics = zhou_ipmsm.metrics.calculate_switching_metrics(switching,n);
time_s = (0:n-1)'*cfg.Ts;
theta_log = omega_e*time_s;
phase_a = cos(theta_log).*current_log(1,:)' - sin(theta_log).*current_log(2,:)';

metrics = table(tracking.rmse_d,tracking.rmse_q,mean(torque),std(torque), ...
    mean(magnet_torque),mean(reluctance_torque), ...
    nnz(~legal)+nnz(~selected_legal),sum(negative_count)+sum(selected_negative_count), ...
    nnz(~legal),nnz(~selected_legal),sum(negative_count),sum(selected_negative_count), ...
    nnz(~constraint_d_ok),nnz(~constraint_q_ok), ...
    nnz(~geometry_inside),nnz(saturation_used)+nnz(selected_saturation_used), ...
    max([projection_error_V;selected_projection_error_V]), ...
    nnz(case_id==1),nnz(case_id==2),nnz(case_id==3), ...
    switching_metrics.total_actions,switching_metrics.actions_per_step, ...
    zhou_ipmsm.metrics.calculate_thd(phase_a), ...
    'VariableNames',{'rmse_d_A','rmse_q_A','mean_torque_Nm','torque_std_Nm', ...
    'mean_magnet_torque_Nm','mean_reluctance_torque_Nm','illegal_commands', ...
    'negative_durations','applied_illegal_commands','selected_illegal_commands', ...
    'applied_negative_durations','selected_negative_durations', ...
    'constraint_d_violations','constraint_q_violations', ...
    'geometry_reference_outside','saturated_commands','max_projection_error_V', ...
    'case1_count','case2_count','case3_count', ...
    'switching_actions','switching_actions_per_step','phase_a_thd'});
trace = struct('time_s',time_s,'current',current_log,'reference_dq',reference_log, ...
    'torque',torque,'magnet_torque',magnet_torque, ...
    'reluctance_torque',reluctance_torque,'legal',legal,'case_id',case_id, ...
    'selected_case_id',selected_case_id, ...
    'constraint_d_ok',constraint_d_ok,'constraint_q_ok',constraint_q_ok);
end

function validate_probe_config(cfg)
assert(isfinite(cfg.Vdc) && cfg.Vdc>0 && isfinite(cfg.Ts) && cfg.Ts>0, ...
    'ZhouIPMSM:InvalidElectricalConfiguration','Vdc and Ts must be positive.');
assert(isscalar(cfg.steps) && isfinite(cfg.steps) && cfg.steps>=4 && ...
    cfg.steps==round(cfg.steps), ...
    'ZhouIPMSM:InvalidSimulationLength','steps must be an integer of at least four.');
motor_values = [cfg.motor.Ld cfg.motor.Lq cfg.motor.Rs cfg.motor.psi_f];
assert(all(isfinite(motor_values)) && all(motor_values>0), ...
    'ZhouIPMSM:InvalidMotorParameters','Motor parameters must be positive.');
assert(isfinite(cfg.motor.pole_pairs) && cfg.motor.pole_pairs>0 && ...
    cfg.motor.pole_pairs==round(cfg.motor.pole_pairs), ...
    'ZhouIPMSM:InvalidPolePairs','Motor pole-pair count must be a positive integer.');
assert(ismember(string(cfg.alpha_mode),["axis_specific" "common_Ls"]), ...
    'ZhouIPMSM:InvalidAlphaMode','Unknown alpha mode: %s',string(cfg.alpha_mode));
assert(ismember(string(cfg.assumptions.frame_mode), ...
    ["execution_segment_midpoint" "legacy_selection_angle"]), ...
    'ZhouIPMSM:InvalidFrameMode','Unknown frame mode: %s',string(cfg.assumptions.frame_mode));
probe_values = [cfg.Jd_limit cfg.Jq_limit cfg.reference_ramp_s ...
    cfg.speed_rpm cfg.id_ref cfg.iq_ref];
assert(all(isfinite(probe_values)) && all([cfg.Jd_limit cfg.Jq_limit]>=0) && ...
    cfg.reference_ramp_s>=0 && cfg.speed_rpm>=0, ...
    'ZhouIPMSM:InvalidProbeLimits','Cost limits and ramp time must be nonnegative.');
end
