function data=case_statistics_table(run_id,experiment,simulation)
log=simulation.log; s=simulation.scenario;
steady=log.time_s>=s.steady_window_start_s;
counts=[nnz(log.case_selected(steady)==1);nnz(log.case_selected(steady)==2); ...
    nnz(log.case_selected(steady)==3)];
data=table(repmat(string(run_id),3,1),repmat(string(experiment),3,1), ...
    repmat(simulation.method,3,1),repmat(string(s.name),3,1),(1:3).',counts, ...
    counts/nnz(steady),'VariableNames',{'run_id','experiment','method', ...
    'scenario','case_id','count','proportion'});
end

