function data=constraint_violations_table(run_id,experiment,simulation,summary,project)
log=simulation.log;s=simulation.scenario;a=project.assumptions;
steady=log.time_s>=s.steady_window_start_s;
idx=find(steady & (1:height(log)).'<=height(log)-2);
actual_ed2=(log.id_ref_A(idx)-log.id_A(idx+2)).^2;
actual_eq2=(log.iq_ref_A(idx)-log.iq_A(idx+2)).^2;
pred_d_excess=log.Jd(steady)-s.Jd_limit_A2;
pred_q_excess=log.Jq(steady)-s.Jq_limit_A2;
axes=["d_pred";"q_pred";"d_actual_k2";"q_actual_k2"];
checked=[nnz(steady);nnz(steady);numel(idx);numel(idx)];
violations=[nnz(pred_d_excess>a.constraint_tolerance_A2); ...
    nnz(pred_q_excess>a.constraint_tolerance_A2); ...
    nnz(actual_ed2-s.Jd_limit_A2>a.constraint_tolerance_A2); ...
    nnz(actual_eq2-s.Jq_limit_A2>a.constraint_tolerance_A2)];
max_excess=[max([0;pred_d_excess]);max([0;pred_q_excess]); ...
    summary.actual_k2_d_max_excess_A2;summary.actual_k2_q_max_excess_A2];
data=table(repmat(string(run_id),4,1),repmat(string(experiment),4,1), ...
    repmat(simulation.method,4,1),repmat(string(s.name),4,1),axes,checked, ...
    violations,violations./checked,max_excess,repmat(a.constraint_tolerance_A2,4,1), ...
    'VariableNames',{'run_id','experiment','method','scenario','axis', ...
    'checked_cycles','violations','violation_rate','max_excess','tolerance'});
end

