function trace = enrich_simulation_trace(simulation,project)
%ENRICH_SIMULATION_TRACE Add aligned oracle, transition, and audit fields.

L=simulation.log;
n=height(L);
Ts=project.base.Ts_s;
scenario=simulation.scenario;
alpha=[simulation.controller_motor.alpha_d;simulation.controller_motor.alpha_q];
plant=simulation.plant_motor;

cycle_index=(1:n).';
sample_sector=sector_from_angle(L.theta_e_rad);
geometry_sector=sector_from_angle(L.geometry_theta_rad);
plant_id_k1=[L.id_A(2:end);NaN];
plant_iq_k1=[L.iq_A(2:end);NaN];
plant_id_k2=[L.id_A(3:end);NaN;NaN];
plant_iq_k2=[L.iq_A(3:end);NaN;NaN];

F_interval_d=NaN(n,1); F_interval_q=NaN(n,1);
valid=(1:n-2).';
F_interval_d(valid)=(L.id_A(valid+2)-L.id_A(valid+1))/Ts-alpha(1)*L.U4d_V(valid);
F_interval_q(valid)=(L.iq_A(valid+2)-L.iq_A(valid+1))/Ts-alpha(2)*L.U4q_V(valid);

prediction_error_d=L.id_pred_k2-plant_id_k2;
prediction_error_q=L.iq_pred_k2-plant_iq_k2;
predicted_margin_d_A=sqrt(scenario.Jd_limit_A2)-abs(L.id_ref_A-L.id_pred_k2);
predicted_margin_q_A=sqrt(scenario.Jq_limit_A2)-abs(L.iq_ref_A-L.iq_pred_k2);
actual_exceedance_d_A=max(0,abs(L.id_ref_A-plant_id_k2)-sqrt(scenario.Jd_limit_A2));
actual_exceedance_q_A=max(0,abs(L.iq_ref_A-plant_iq_k2)-sqrt(scenario.Jq_limit_A2));
voltage_utilization=hypot(L.U4d_V,L.U4q_V)/ ...
    max(project.assumptions.voltage_vector_scale*project.assumptions.dc_bus_V,eps);
saturation_flag=voltage_utilization>=0.98;
command_transition=[false;L.sequence_vector_ids(2:end)~=L.sequence_vector_ids(1:end-1) | ...
    L.sequence_durations_s(2:end)~=L.sequence_durations_s(1:end-1)];
sector_transition=[false;geometry_sector(2:end)~=geometry_sector(1:end-1)];
case_transition=[false;L.case_selected(2:end)~=L.case_selected(1:end-1)];
components=zhou_ipmsm.model.torque_components([L.id_A L.iq_A],plant);

trace=table(cycle_index,L.time_s,L.theta_e_rad,L.geometry_theta_rad, ...
    sample_sector,geometry_sector,L.case_selected,L.case_applied, ...
    L.sequence_vector_ids,L.applied_sequence_vector_ids, ...
    L.sequence_durations_s,L.applied_sequence_durations_s, ...
    L.U3d_V,L.U3q_V,L.U4d_V,L.U4q_V,L.id_A,L.iq_A,L.id_ref_A,L.iq_ref_A, ...
    L.id_pred_k1,L.iq_pred_k1,L.id_pred_k2,L.iq_pred_k2, ...
    plant_id_k1,plant_iq_k1,plant_id_k2,plant_iq_k2,L.Fhat_d,L.Fhat_q, ...
    F_interval_d,F_interval_q,prediction_error_d,prediction_error_q, ...
    predicted_margin_d_A,predicted_margin_q_A,actual_exceedance_d_A, ...
    actual_exceedance_q_A,repmat(alpha(1),n,1),repmat(alpha(2),n,1), ...
    voltage_utilization,saturation_flag,command_transition,sector_transition, ...
    case_transition,L.illegal_selected|L.illegal_applied, ...
    L.selected_min_duration_s,L.applied_min_duration_s,L.switching_actions_applied, ...
    components.total_Nm,components.magnet_Nm,components.reluctance_Nm, ...
    'VariableNames',{'cycle_index','time_s','theta_rad','geometry_theta_rad', ...
    'sample_sector','geometry_sector','case_selected','case_applied', ...
    'selected_vectors','applied_vectors','selected_durations_s','applied_durations_s', ...
    'U3d_V','U3q_V','U4d_V','U4q_V','id_A','iq_A','id_ref_A','iq_ref_A', ...
    'id_pred_k1_A','iq_pred_k1_A','id_pred_k2_A','iq_pred_k2_A', ...
    'plant_id_k1_A','plant_iq_k1_A','plant_id_k2_A','plant_iq_k2_A', ...
    'Fd_estimated','Fq_estimated','Fd_interval_oracle','Fq_interval_oracle', ...
    'prediction_error_d_A','prediction_error_q_A','predicted_margin_d_A', ...
    'predicted_margin_q_A','actual_exceedance_d_A','actual_exceedance_q_A', ...
    'alpha_d','alpha_q','voltage_utilization','saturation_flag', ...
    'command_transition','sector_transition','case_transition','illegal_command', ...
    'selected_min_duration_s','applied_min_duration_s','switching_actions', ...
    'torque_Nm','magnet_torque_Nm','reluctance_torque_Nm'});
end

function sector=sector_from_angle(theta)
sector=floor(mod(theta,2*pi)/(pi/3))+1;
sector(sector>6)=6;
end
