function A = aggregate_metrics(M,grouping)
%AGGREGATE_METRICS Weighted method or method-by-cohort summaries.
grouping=string(grouping);
if grouping=="method"
    keys=unique(M.method,'stable');labels=repmat("ENGINEERING_PRIMARY",numel(keys),1);
else
    pairs=unique(M(:,{'method','category'}),'rows','stable');keys=pairs.method+"|"+pairs.category;labels=pairs.category;
end
rows=cell(numel(keys),1);
for k=1:numel(keys)
    if grouping=="method",q=M.method==keys(k)&M.range_class~="stress_test";method=keys(k);
    else,parts=split(keys(k),'|');method=parts(1);q=M.method==method&M.category==parts(2)&M.range_class~="stress_test";end
    X=M(q,:);w=max(0,X.trace_rows-2);W=max(sum(w),1);
    thd=X.phase_thd(X.thd_valid);torque=X.torque_ripple_Nm(isfinite(X.torque_ripple_Nm));
    rows{k}=table(method,labels(k),sum(w),sum(w.*X.false_safe_rate)/W, ...
        sum(w.*X.false_alarm_rate)/W,sqrt(sum(w.*X.vector_rms_A.^2)/W), ...
        mean(thd,'omitnan'),mean(torque,'omitnan'),mean(X.id_tracking_rms_A,'omitnan'), ...
        mean(X.iq_tracking_rms_A,'omitnan'),mean(X.alpha_boundary_hit_rate,'omitnan'), ...
        mean(X.alpha_update_rate,'omitnan'),mean(X.gate_freeze_rate,'omitnan'), ...
        mean(X.decision_gate_rate,'omitnan'),mean(X.s2_gate_rate,'omitnan'), ...
        mean(X.execution_mean_us,'omitnan'),all(X.completed|X.illegal), ...
        all(X.estimator_finite),sum(X.S2_count),sum(X.illegal_duration_count), ...
        'VariableNames',{'method','cohort','sample_count','false_safe_rate', ...
        'false_alarm_rate','vector_rms_A','phase_thd','torque_ripple_Nm', ...
        'id_tracking_rms_A','iq_tracking_rms_A','alpha_boundary_hit_rate', ...
        'alpha_update_rate','gate_freeze_rate','decision_gate_rate','s2_gate_rate', ...
        'execution_mean_us','termination_semantics_pass','estimator_finite','S2_count', ...
        'illegal_duration_count'});
end
A=vertcat(rows{:});
end
