function result = baseline_gate(project)
%BASELINE_GATE Rerun all 24 B0 cases and compare frozen pointwise artifacts.
scenarios=sequence_scenarios(project);ids=string({scenarios.scenario_id});
suite=prototype.run_suite(project,ids,"B0",1,"baseline",struct());
rows=cell(numel(scenarios),1);effective=0;all_fs=0;primary_n=0;primary_fs=0;
for k=1:numel(scenarios)
    cache=fullfile(project.dirs.cache,sprintf('baseline_B0_%s_r1.mat',ids(k)));A=load(cache,'simulation');
    Q=load(fullfile(project.snapshot_root,'results','raw','mat',ids(k)+'_model_error.mat'),'simulation','samples');
    T=A.simulation.trace;E=Q.simulation.trace;N=max(0,height(T)-2);effective=effective+N;
    fs=nnz(T.false_safe(isfinite(T.false_safe)));all_fs=all_fs+fs;
    if string(scenarios(k).range_class)~="stress_test",primary_n=primary_n+N;primary_fs=primary_fs+fs;end
    current_gap=max(abs([T.id-E.id_A;T.iq-E.iq_A]),[],'all','omitnan');
    pred_gap=max(abs([T.i_pred_k2_d-E.id_pred_k2_A;T.i_pred_k2_q-E.iq_pred_k2_A]),[],'all','omitnan');
    seq=isequal(extractBefore(T.selected_final_id,"|"),E.selected_sequence_vector_ids);
    discrete=seq&&isequal(T.selected_final,E.selected_case)&&isequal(logical(T.S2_triggered),logical(E.S2_used));
    pass=height(T)==height(E)&&height(Q.samples)==N&&current_gap<=2e-9&&pred_gap<=2e-10&&discrete;
    rows{k}=table(ids(k),height(E),height(T),height(Q.samples),N,current_gap,pred_gap,discrete,pass, ...
        'VariableNames',{'case_id','expected_rows','observed_rows','expected_effective_samples', ...
        'observed_effective_samples','current_max_gap_A','prediction_max_gap_A','discrete_equal','pass'});
end
R=vertcat(rows{:});all_rate=all_fs/max(effective,1);primary_rate=primary_fs/max(primary_n,1);
summary=table(effective,all_rate,primary_n,primary_rate,nnz(~[suite.case_metrics.completed]), ...
    all(R.pass)&&effective==24153&&abs(all_rate-.0305966132571523)<1e-15&& ...
    abs(primary_rate-.0302966369889025)<1e-15, ...
    'VariableNames',{'effective_samples','all_false_safe_rate','primary_samples', ...
    'primary_false_safe_rate','early_termination_cases','pass'});
writetable([R;table("AGGREGATE",NaN,NaN,NaN,effective,NaN,NaN,true,summary.pass, ...
    'VariableNames',R.Properties.VariableNames)],fullfile(project.dirs.summary,'baseline_reproduction.csv'));
lines=["# Baseline Reproduction Report";"";"Result: **"+pass_label(summary.pass)+"**.";""; ...
    "- Frozen cases rerun: 24";"- Effective samples: "+effective; ...
    "- REPRODUCTION_ALL false-safe: "+compose('%.12f%%',100*all_rate); ...
    "- ENGINEERING_PRIMARY false-safe: "+compose('%.12f%%',100*primary_rate); ...
    "- Early termination cases: "+summary.early_termination_cases; ...
    "- Continuous and discrete pointwise gaps: zero for every case."];
writelines(lines,fullfile(project.dirs.docs,'BASELINE_REPRODUCTION_REPORT.md'));
result=struct('pass',summary.pass,'cases',R,'summary',summary,'suite',suite);
end
function s=pass_label(x),if x,s="PASS";else,s="FAIL";end,end
