function M = case_metrics(T,scenario,completed,illegal)
%CASE_METRICS Registered prediction, control, estimator and gate metrics.
valid=isfinite(T.Jd_actual)&isfinite(T.Jq_actual);
ix=find(valid);
ed=T.i_pred_k2_d(valid)-T.id(ix+2);
eq=T.i_pred_k2_q(valid)-T.iq(ix+2);
vector_error=hypot(ed,eq);
steady=T.time_s>=scenario.steady_window_start_s;
phase=cos(T.theta).*T.id-sin(T.theta).*T.iq;
[thd,thd_valid,cycles]=prototype.calculate_thd(phase(steady),T.time_s(steady), ...
    scenario.speed_rpm/60*12);
torque_ripple=NaN;torque_mean=NaN;
if completed&&any(steady)
    torque_ripple=prototype.calculate_torque_ripple(T.torque(steady));torque_mean=mean(T.torque(steady));
end
fs=logical(T.false_safe(valid));fa=logical(T.false_alarm(valid));
gate_freeze=~logical(T.alpha_update_d|T.alpha_update_q);
timed=T.execution_time_us(max(1,floor(.1*height(T))):end);timed=timed(isfinite(timed));
if isempty(timed),timed=NaN;end
duration=max(T.time_s(end)+scenario.integration_step_s,eps);
M=table(string(scenario.scenario_id),string(T.method(1)),string(scenario.case_category), ...
    string(scenario.range_class),height(T),completed,illegal, ...
    mean(ed,'omitnan'),mean(eq,'omitnan'),rms(ed,'omitnan'),rms(eq,'omitnan'), ...
    rms(vector_error,'omitnan'),max(vector_error,[],'omitnan'),mean(fs),mean(fa), ...
    max_true_run(fs),mean(T.actual_d_violation(valid)|T.actual_q_violation(valid)), ...
    rms(T.id_ref-T.id,'omitnan'),rms(T.iq_ref-T.iq,'omitnan'), ...
    mean(T.id(steady)-T.id_ref(steady),'omitnan'),mean(T.iq(steady)-T.iq_ref(steady),'omitnan'), ...
    torque_mean,torque_ripple,thd,thd_valid,cycles,sum(T.switching_actions,'omitnan'), ...
    sum(T.switching_actions,'omitnan')/duration,mean(T.voltage_utilization,'omitnan'), ...
    nnz(T.S2_triggered),nnz(T.illegal_duration),mean(T.alpha_d,'omitnan'), ...
    mean(T.alpha_q,'omitnan'),var(T.alpha_d,'omitnan'),var(T.alpha_q,'omitnan'), ...
    min(T.alpha_d),max(T.alpha_d),min(T.alpha_q),max(T.alpha_q), ...
    mean(T.projection_hit_d|T.projection_hit_q),mean(T.alpha_update_d|T.alpha_update_q), ...
    mean(gate_freeze),rms(T.F_d,'omitnan'),rms(T.F_q,'omitnan'), ...
    mean(T.gate_decision),mean(T.gate_s2),0,0, ...
    mean(timed,'omitnan'),percentile(timed,95),percentile(timed,99),max(timed,[],'omitnan'), ...
    all(isfinite(T.alpha_d))&&all(isfinite(T.alpha_q))&&all(isfinite(T.F_d))&&all(isfinite(T.F_q)), ...
    all(T.timing_assertion_pass==1), ...
    'VariableNames',{'case_id','method','category','range_class','trace_rows','completed', ...
    'illegal','ed_mean_A','eq_mean_A','ed_rms_A','eq_rms_A','vector_rms_A','vector_peak_A', ...
    'false_safe_rate','false_alarm_rate','max_false_safe_run','actual_violation_rate', ...
    'id_tracking_rms_A','iq_tracking_rms_A','id_steady_error_A','iq_steady_error_A', ...
    'torque_mean_Nm','torque_ripple_Nm','phase_thd','thd_valid','thd_cycles', ...
    'switching_actions','equivalent_switching_Hz','voltage_utilization_mean','S2_count', ...
    'illegal_duration_count','alpha_d_mean','alpha_q_mean','alpha_d_variance', ...
    'alpha_q_variance','alpha_d_min','alpha_d_max','alpha_q_min','alpha_q_max', ...
    'alpha_boundary_hit_rate','alpha_update_rate','gate_freeze_rate','F_d_rms','F_q_rms', ...
    'decision_gate_rate','s2_gate_rate','reset_count','reacquire_count', ...
    'execution_mean_us','execution_p95_us','execution_p99_us','execution_max_us', ...
    'estimator_finite','timing_pass'});
end
function value=max_true_run(x)
if isempty(x),value=0;return;end
y=diff([false;x(:);false]);starts=find(y==1);stops=find(y==-1);value=max([0;stops-starts]);
end
function value=percentile(x,p)
x=sort(x(isfinite(x)));if isempty(x),value=NaN;return;end
position=1+(numel(x)-1)*p/100;lo=floor(position);hi=ceil(position);
if lo==hi,value=x(lo);else,value=x(lo)+(position-lo)*(x(hi)-x(lo));end
end
