function result=finalize_audit(project)
%FINALIZE_AUDIT Produce a gate-faithful failure handoff and verify upstreams.
M=readtable(fullfile(project.dirs.summary,'minimal_method_metrics.csv'),'TextType','string');
C=readtable(fullfile(project.dirs.summary,'minimal_case_metrics.csv'),'TextType','string');
H=readtable(fullfile(project.dirs.summary,'minimal_cohort_metrics.csv'),'TextType','string');
R=readtable(fullfile(project.dirs.summary,'minimal_repeatability.csv'),'TextType','string');
G=readtable(fullfile(project.dirs.summary,'prototype_gate_results.csv'),'TextType','string');
assert(~all(logical(G.pass)),'Prototype:UnexpectedGateState','This finalizer is for the observed failed minimal gate.');
scope=repmat("MINIMAL_GATE_ONLY",height(M),1);M=addvars(M,scope,'After','cohort','NewVariableNames','evidence_scope');
writetable(M,fullfile(project.dirs.summary,'method_metrics.csv'));
writetable(C,fullfile(project.dirs.summary,'case_metrics.csv'));
writetable(H,fullfile(project.dirs.summary,'cohort_metrics.csv'));
writetable(R,fullfile(project.dirs.summary,'repeatability.csv'));
write_summary_tables(project,M,C);
write_skipped_outputs(project);
B=M(M.method=="B0",:);P=M(M.method=="P",:);
reduction=1-P.false_safe_rate/B.false_safe_rate;
decision=table("C","dual_timescale_primary_mechanism_failed_minimal_gate", ...
    "MINIMAL_GATE_ONLY",false,false,false,reduction,P.false_safe_rate,B.false_safe_rate, ...
    P.false_alarm_rate,P.vector_rms_A,B.vector_rms_A, ...
    "P worsened aggregate false-safe, exceeded 150% RMS, and changed C07 termination from row 31 to row 6", ...
    'VariableNames',{'decision_code','decision_label','evidence_scope','minimal_gate_pass', ...
    'full_24_executed','final_algorithm_formed','P_false_safe_reduction_vs_B0', ...
    'P_false_safe_rate','B0_false_safe_rate','P_false_alarm_rate','P_vector_rms_A', ...
    'B0_vector_rms_A','reason'});
writetable(decision,fullfile(project.dirs.summary,'final_decision.csv'));
prototype.generate_minimal_figures(project);
write_documents(project,M,C,H,R,G,decision);
after=prototype.inventory_audit(project,"after");
assert(after.changed==0&&after.added==0&&after.removed==0,'Prototype:UpstreamMutation');
result=struct('decision',decision,'upstream_validation',after.validation, ...
    'final_algorithm_formed',false,'full_24_executed',false);
end

function write_summary_tables(project,M,C)
control_names=intersect(M.Properties.VariableNames,{'method','evidence_scope','id_tracking_rms_A', ...
    'iq_tracking_rms_A','phase_thd','torque_ripple_Nm','S2_count','illegal_duration_count'},'stable');
writetable(M(:,control_names),fullfile(project.dirs.summary,'control_performance.csv'));
est_names=intersect(M.Properties.VariableNames,{'method','evidence_scope','alpha_boundary_hit_rate', ...
    'alpha_update_rate','gate_freeze_rate','decision_gate_rate','s2_gate_rate'},'stable');
writetable(M(:,est_names),fullfile(project.dirs.summary,'estimator_statistics.csv'));
writetable(M(:,intersect(M.Properties.VariableNames,{'method','evidence_scope','gate_freeze_rate', ...
    'decision_gate_rate','s2_gate_rate'},'stable')),fullfile(project.dirs.summary,'gate_statistics.csv'));
n=M.sample_count;fs=round(n.*M.false_safe_rate);fa=round(n.*M.false_alarm_rate);
confusion=table(M.method,n,fs,fa,M.false_safe_rate,M.false_alarm_rate, ...
    repmat("MINIMAL_GATE_ONLY",height(M),1),'VariableNames',{'method','samples','false_safe_count', ...
    'false_alarm_count','false_safe_rate','false_alarm_rate','scope'});
writetable(confusion,fullfile(project.dirs.summary,'constraint_confusion.csv'));
raw=readtable(fullfile(project.dirs.raw,'closed_loop_samples_P.csv'),'TextType','string');
gate_names=intersect(raw.Properties.VariableNames,{'case_id','method','sample_index','time_s','gate_exc_d', ...
    'gate_exc_q','gate_s2','gate_decision','alpha_update_d','alpha_update_q', ...
    'freeze_reason_d','freeze_reason_q','estimator_state_d','estimator_state_q'},'stable');
writetable(raw(:,gate_names),fullfile(project.dirs.raw,'estimator_gate_log.csv'));
reasons=[raw.freeze_reason_d;raw.freeze_reason_q];[g,names]=findgroups(reasons);counts=splitapply(@numel,reasons,g);
writetable(table(names,counts,'VariableNames',{'freeze_reason','count'}), ...
    fullfile(project.dirs.summary,'freeze_reason_counts.csv'));
end

function write_skipped_outputs(project)
reason="SKIPPED: preregistered five-case minimal gate failed; running this phase would violate the hard-gate order";
writetable(table("NOT_RUN",reason,'VariableNames',{'ablation','status'}),fullfile(project.dirs.summary,'ablation_metrics.csv'));
writetable(table("NOT_RUN",reason,'VariableNames',{'parameter','status'}),fullfile(project.dirs.summary,'parameter_sensitivity.csv'));
writetable(table("NOT_RUN",reason,'VariableNames',{'method','status'}),fullfile(project.dirs.summary,'execution_time_metrics.csv'));
design_ops=readtable(fullfile(fileparts(project.root),'zhou_icf_mpc_dual_timescale_design_iter01', ...
    'results','summary','operation_count.csv'),'TextType','string');
writetable(design_ops,fullfile(project.dirs.summary,'operation_count.csv'));
end

function write_documents(project,M,C,H,R,G,D)
write_scope(project);write_compliance(project);write_path_report(project);
skipped="This phase was **NOT RUN** because the preregistered five-case gate failed. No metric or conclusion for this phase is imputed from the gate cases.";
writelines(["# Full 24-Case Report";"";skipped],fullfile(project.dirs.docs,'FULL_24_CASE_REPORT.md'));
writelines(["# Ablation Report";"";skipped;"";"The design requires ablation only after P completes all 24 cases."],fullfile(project.dirs.docs,'ABLATION_REPORT.md'));
writelines(["# Parameter Sensitivity Report";"";skipped],fullfile(project.dirs.docs,'PARAMETER_SENSITIVITY_REPORT.md'));
writelines(["# Realtime Computation Report";"";skipped;""; ...
    "Parallel campaign wall-clock observations are not reported as controller WCET. MATLAB microbenchmark, DSP inference and hardware validation therefore remain unavailable."], ...
    fullfile(project.dirs.docs,'REALTIME_COMPUTATION_REPORT.md'));
B=M(M.method=="B0",:);P=M(M.method=="P",:);reduction=1-P.false_safe_rate/B.false_safe_rate;
report=["# Final Prototype Report";"";"## Outcome";""; ...
    "**C — dual-timescale primary mechanism failed the preregistered minimal gate.**";""; ...
    "This is a five-case gate conclusion, not a fabricated 24-case result. P increased aggregate false-safe from "+pct(B.false_safe_rate)+" to "+pct(P.false_safe_rate)+ ...
    " (relative reduction "+pct(reduction)+", negative means worse) and increased prediction vector RMS from "+num(B.vector_rms_A)+" A to "+num(P.vector_rms_A)+" A."; ...
    "P also terminated C07 at row 6 rather than the frozen row 31. False-alarm remained "+pct(P.false_alarm_rate)+"; alpha updates were finite and nonzero, so the failure is not a NaN-only artifact.";""; ...
    "## Gate discipline";"";"Full 24-case validation, ablation, sensitivity and final timing were not run. This is the required stop behavior after a failed minimal hard gate.";""; ...
    "## Final algorithm";"";"No final algorithm was formed; `FINAL_ALGORITHM_SPEC.md`, pseudocode, flow, parameters and final SHA files were intentionally not created."];
writelines(report,fullfile(project.dirs.docs,'FINAL_PROTOTYPE_REPORT.md'));
writelines(["# Decision and Next Step";"";"Decision: **C**.";""; ...
    "Stop this route in iter01. Do not start an unrestricted retuning loop. Any future work requires a separately authorized, preregistered structural investigation rather than reusing the five gate cases for parameter selection."], ...
    fullfile(project.dirs.docs,'DECISION_AND_NEXT_STEP.md'));
writelines(["# Known Limitations";"";"- Evidence stops at the five-case gate; no full-campaign claim is made."; ...
    "- No ablation, local sensitivity, MATLAB timing microbenchmark, DSP WCET or HIL test was authorized after the failure."; ...
    "- The frozen Zhou interface does not expose a runner-up mode cost; the prototype logs `abs(Jd-Jq)` as the native cost-gap adapter and records this in the compliance matrix."; ...
    "- Simulation uses the frozen idealized plant and inherited limitations."],fullfile(project.dirs.docs,'KNOWN_LIMITATIONS.md'));
write_root_docs(project,M,C,H,R,G,D);
end

function write_scope(project)
writelines(["# Project Scope";"";"Isolated implementation and gate validation of the frozen S2-aware dual-timescale ultralocal predictor."; ...
    "The prototype may change only predictor/estimator state and predicted current. Plant, Ts=100 us, Jd/Jq=0.16 A^2, candidate generation, modes, S2 and termination semantics are frozen byte-identical copies."; ...
    "The campaign stops after the failed five-case gate."],fullfile(project.dirs.docs,'PROJECT_SCOPE.md'));
end

function write_compliance(project)
rows={ ...
"causal derivative and historical u_app","src/+prototype/estimator_step.m","estimator_step","function [state,d] = estimator_step",true,"none"; ...
"post-S2 segment reconstruction","src/+prototype/s2_input_quality_gate.m","s2_input_quality_gate","function q = s2_input_quality_gate",true,"none"; ...
"20-row projected alpha","src/+prototype/alpha_update.m","alpha_update","function [alpha,hit] = alpha_update",true,"none"; ...
"posterior-alpha fast F","src/+prototype/F_update.m","F_update","function [Fpost,Fpred] = F_update",true,"none"; ...
"one-row latched trend","src/+prototype/F_update.m","F_update","Fpred=Fpost+p.rho_F",true,"one indexing defect found and fixed before final gate"; ...
"two exact Ts predictions","src/+prototype/dual_timescale_predictor.m","dual_timescale_predictor","function [k1,k2] = dual_timescale_predictor",true,"none"; ...
"unchanged Zhou geometry and S2","src/+prototype/icf_mpc_step.m","icf_mpc_step","function output = icf_mpc_step",true,"copied packages SHA-equal"; ...
"decision margin and native gap","src/+prototype/decision_margin_gate.m","decision_margin_gate","function [gate,mJ] = decision_margin_gate",false,"upstream exposes no runner-up mode cost; abs(Jd-Jq) adapter logged"; ...
"constrained two-parameter RLS","src/+prototype/constrained_rls_update.m","constrained_rls_update","function [state,diag] = constrained_rls_update",true,"comparison only"; ...
"hard gate order","run_dual_timescale_prototype.m","run_dual_timescale_prototype","function outcome = run_dual_timescale_prototype",true,"later phases skipped"};
L=["# Design Spec Compliance Matrix";"";"| Requirement | File | Function | Line | Complete | Deviation / impact |";"|---|---|---|---:|---:|---|"];
for k=1:size(rows,1)
    file=fullfile(project.root,rows{k,2});line=find_line(file,rows{k,4});
    L(end+1)="| "+rows{k,1}+" | `"+rows{k,2}+"` | `"+rows{k,3}+"` | "+line+" | "+string(rows{k,5})+" | "+rows{k,6}+" |"; %#ok<AGROW>
end
writelines(L,fullfile(project.dirs.docs,'DESIGN_SPEC_COMPLIANCE_MATRIX.md'));
end

function write_path_report(project)
T=readtable(fullfile(project.dirs.summary,'path_resolution_table.csv'),'TextType','string');
P=readtable(fullfile(project.dirs.audit,'SOURCE_PROJECT_STATUS.csv'),'TextType','string','Delimiter',',');
L=["# Path Conflict Report";"";"Critical MATLAB symbols resolving outside the prototype: **"+nnz(~T.inside_project)+"**."; ...
    "Empty specified upstream stubs: **"+nnz(P.status=="FOUND_EMPTY_STUB")+"**."; ...
    "Executable model-error source was restored from Git commit `"+strtrim(fileread(fullfile(project.dirs.audit,'MODEL_ERROR_GIT_COMMIT.txt')))+"` inside the prototype reference snapshot."];
writelines(L,fullfile(project.dirs.docs,'PATH_CONFLICT_REPORT.md'));
end

function write_root_docs(project,M,C,H,R,G,D)
B=M(M.method=="B0",:);P=M(M.method=="P",:);
readme=["# Zhou ICF-MPC Dual-Timescale Prototype iter01";""; ...
    "Outcome: **C — failed the preregistered five-case gate**. B0 wiring and 24-case baseline reproduction passed; P did not earn authorization for the full comparison campaign.";""; ...
    "Run `run_dual_timescale_prototype('all')` in MATLAB R2024b. The workflow is isolated, cacheable and gate-aware; with the frozen evidence it stops after minimal and regenerates the C handoff.";""; ...
    "Key evidence: `results/summary/final_decision.csv`, `docs/FINAL_PROTOTYPE_REPORT.md`, `results/summary/prototype_gate_results.csv`. No final algorithm files exist by design."];
writelines(readme,fullfile(project.root,'README.md'));
run=["# Run and Reproduce";"";"```matlab";"cd('"+string(project.root)+"')";"run_dual_timescale_prototype('all')";"```";""; ...
    "Individual modes are inventory, wiring, baseline, smoke, calibration, minimal, full, ablation, sensitivity, timing and audit. `full`, `ablation`, `sensitivity` and `timing` refuse to run while the minimal gate is failed."; ...
    "To force computation rather than cache reuse, remove only this project's `results/cache` directory after verifying its absolute path. Never remove an upstream directory."; ...
    "MATLAB startup restores the default path and adds only root, config and src inside this prototype."];
writelines(run,fullfile(project.root,'RUN_AND_REPRODUCE.md'));
change=["# Changelog";"";"## iter01";"";"- Restored the 256-file model-error Git snapshot without changing the empty upstream stub."; ...
    "- Copied 113 executable source files with SHA256 provenance.";"- Added B0/B1/B2/P/RLS predictor and estimator paths."; ...
    "- Fixed two pre-conclusion defects: illegal-command termination was one row early; trend used k-2 rather than k-1."; ...
    "- Passed wiring and 24-case B0 reproduction; failed five-case P gate; skipped later phases.";"- Final decision C; no final algorithm freeze."];
writelines(change,fullfile(project.root,'CHANGELOG.md'));
handoff=["# Handoff";"";"1. Goal: implement the frozen S2-aware dual-timescale predictor in the Zhou IPMSM closed loop."; ...
    "2. Research chain: constraint/probe/feasibility/robust → sequence → model-error → design → this prototype."; ...
    "3. Design conclusion was permission to prototype, not proof of performance.";"4. Project: `"+string(project.root)+"`."; ...
    "5. Executable source: Git commit `"+strtrim(fileread(fullfile(project.dirs.audit,'MODEL_ERROR_GIT_COMMIT.txt')))+"`, restored under `reference/upstream_snapshots`."; ...
    "6. Frozen upstreams: seven paths in `audit/SOURCE_PROJECTS.csv`; five are empty stubs."; ...
    "7. Methods: B0 original; B1 slow alpha only; B2 slow alpha+fast F; P adds decision trend; RLS is a constrained comparator."; ...
    "8. P formula and parameters are in `config/FROZEN_PROTOTYPE_PARAMETERS.m`."; ...
    "9. Timing: pending(k) executes k→k+1; selected_final(k) executes k+1→k+2; both predictions use one Ts."; ...
    "10. Applied voltage is reconstructed from final post-S2 vector IDs/durations, Vdc and segment-midpoint Park angles."; ...
    "11. Gates: excitation, S2 input quality, and next-row latched decision margin."; ...
    "12. Calibration used only C01, P08 and D03 and retained the corrected design default."; ...
    "13. Frozen parameter SHA is in `audit/PARAMETER_FREEZE_SHA256.txt`."; ...
    "14. Minimal result: FAIL; see `results/summary/minimal_case_metrics.csv`."; ...
    "15. Full 24-method campaign: NOT RUN by hard-gate rule."; ...
    "16. ENGINEERING_PRIMARY method metrics in `method_metrics.csv` are explicitly MINIMAL_GATE_ONLY."; ...
    "17. Ablation: NOT RUN.";"18. Sensitivity: NOT RUN.";"19. Final timing/DSP audit: NOT RUN; no hardware timing claim."; ...
    "20. Final conclusion: C.";"21. Final algorithm formed: no.";"22. Retained modules: none were frozen as a final algorithm."; ...
    "23. Deleted modules: none; the route stopped before a valid ablation decision."; ...
    "24. CSVs are under `results/summary`; five gate figures are under `results/figures/minimal`."; ...
    "25. One-command reproduction is documented in `RUN_AND_REPRODUCE.md`."; ...
    "26. Upstream after/before result is `audit/FROZEN_UPSTREAM_VALIDATION.csv` and must remain zero-change."; ...
    "27. Known limitations are in `docs/KNOWN_LIMITATIONS.md`."; ...
    "28. HIL/hardware validation remains necessary for any future algorithm, but this iter01 is not a hardware candidate.";""; ...
    "Key numbers: B0/P false-safe "+pct(B.false_safe_rate)+" / "+pct(P.false_safe_rate)+"; B0/P vector RMS "+num(B.vector_rms_A)+" / "+num(P.vector_rms_A)+" A."];
writelines(handoff,fullfile(project.root,'HANDOFF.md'));
end

function line=find_line(file,pattern)
if ~isfile(file),line="n/a";return;end
L=readlines(file);q=find(contains(L,string(pattern)),1);if isempty(q),line="n/a";else,line=string(q);end
end
function s=pct(x),s=compose('%.6f%%',100*x);end
function s=num(x),s=compose('%.6g',x);end
