function output = icf_mpc_step(input,cfg,estimator)
%ICF_MPC_STEP Frozen Zhou geometry/candidates driven by the new predictor.
alpha=estimator.alpha(:);Fpred=estimator.F_pred(:);
pending_voltage=zhou_ipmsm.controller.sequence_equivalent_dq_voltage( ...
    input.pending_command,cfg.vectors,input.theta_e,input.omega_e,0, ...
    cfg.paper.Ts_s,cfg.assumptions.candidate_voltage_frame_mode);
predicted_k1=input.current_dq(:)+cfg.paper.Ts_s*(Fpred+alpha.*pending_voltage);
V=zhou_ipmsm.controller.compute_V_terms(input.reference_dq,predicted_k1,Fpred,cfg.paper.Ts_s);
geometry_theta=input.theta_e;
if cfg.assumptions.candidate_voltage_frame_mode=="execution_segment_midpoint"
    geometry_theta=mod(input.theta_e+1.5*input.omega_e*cfg.paper.Ts_s,2*pi);
end
rect=zhou_ipmsm.geometry.build_rectangle(V(1),V(2),cfg.Jd_limit,cfg.Jq_limit, ...
    alpha(1),alpha(2),cfg.paper.Ts_s,geometry_theta,cfg.assumptions.geometry_tolerance);
geometry=zhou_ipmsm.geometry.analyze_rectangle(rect,cfg.vectors, ...
    cfg.assumptions.voltage_tolerance_V,cfg.assumptions.sector_angle_tolerance_rad, ...
    cfg.assumptions.duty_tolerance);
command=geometry.command;
command.reference_dq_at_selection=zhou_ipmsm.math.park(command.reference_ab_V,input.theta_e);
command.theta_at_selection=input.theta_e;
command.reference_dq_execution=zhou_ipmsm.controller.sequence_equivalent_dq_voltage( ...
    command,cfg.vectors,input.theta_e,input.omega_e,1,cfg.paper.Ts_s, ...
    cfg.assumptions.candidate_voltage_frame_mode);
[~,predicted_k2]=prototype.dual_timescale_predictor(input.current_dq,Fpred,alpha, ...
    pending_voltage,command.reference_dq_execution,cfg.paper.Ts_s);
[Jd,Jq]=zhou_ipmsm.controller.independent_costs(input.reference_dq,predicted_k2);
output=struct('command',command,'Fhat_dq',estimator.F(:), ...
    'Fpred_dq',Fpred,'alpha_dq',alpha,'predicted_k1_dq',predicted_k1, ...
    'predicted_k2_dq',predicted_k2,'V_dq',V,'Jd',Jd,'Jq',Jq, ...
    'constraint_satisfied_d',Jd<=cfg.Jd_limit+cfg.assumptions.constraint_tolerance, ...
    'constraint_satisfied_q',Jq<=cfg.Jq_limit+cfg.assumptions.constraint_tolerance, ...
    'geometry',geometry,'cost_crosscheck_error',0, ...
    'pending_voltage_dq_used',pending_voltage, ...
    'selected_voltage_dq_used',command.reference_dq_execution, ...
    'geometry_theta',geometry_theta,'native_mode_gap_A2',abs(Jd-Jq));
end
