function T = path_audit(project)
%PATH_AUDIT Resolve every critical symbol after default-path isolation.
symbols=["run_dual_timescale_prototype","prototype.icf_mpc_step", ...
    "zhou_ipmsm.controller.icf_mpc_step","prototype.dual_timescale_predictor", ...
    "prototype.alpha_update","prototype.F_update","prototype.excitation_gate", ...
    "prototype.s2_input_quality_gate","prototype.decision_margin_gate", ...
    "zhou_feasibility.apply_feasibility_layer", ...
    "zhou_ipmsm.controller.sequence_equivalent_dq_voltage", ...
    "prototype.plant_update","prototype.case_metrics","prototype.calculate_thd", ...
    "prototype.calculate_torque_ripple"];
rows=cell(numel(symbols),1);
for k=1:numel(symbols)
    resolved=string(which(symbols(k),'-all'));
    if isempty(resolved),path="";count=0;inside=false;else,path=strjoin(resolved," | ");count=numel(resolved);inside=all(startsWith(resolved,string(project.root),'IgnoreCase',true));end
    rows{k}=table(symbols(k),path,count,inside,'VariableNames',{'symbol','resolved_path','resolution_count','inside_project'});
end
T=vertcat(rows{:});writetable(T,fullfile(project.dirs.summary,'path_resolution_table.csv'));
end
