function result = wiring_gate(project)
%WIRING_GATE Pointwise B0 equivalence, timing, causality and isolation gate.
paths=prototype.path_audit(project);path_pass=all(paths.inside_project&paths.resolution_count==1);
scenarios=sequence_scenarios(project);s=scenarios(1);runs=cell(3,1);
for r=1:3
    cache=fullfile(project.dirs.cache,sprintf('wiring_B0_%s_r%d.mat',s.scenario_id,r));
    if isfile(cache),Q=load(cache,'simulation');runs{r}=Q.simulation;
    else,runs{r}=prototype.run_control_case(project,s,"B0");simulation=runs{r};save(cache,'simulation','-v7.3');end
end
Q=load(fullfile(project.snapshot_root,'results','raw','mat',s.scenario_id+'_model_error.mat'),'simulation');E=Q.simulation.trace;A=runs{1}.trace;
current_gap=max(abs([A.id-E.id_A;A.iq-E.iq_A]),[],'all');
prediction_gap=max(abs([A.i_pred_k2_d-E.id_pred_k2_A;A.i_pred_k2_q-E.iq_pred_k2_A]),[],'all');
sequence_pass=isequal(A.selected_final_id,E.selected_sequence_vector_ids+"|"+E.selected_sequence_durations_s);
mode_pass=isequal(A.selected_final,E.selected_case);s2_pass=isequal(logical(A.S2_triggered),logical(E.S2_used));
Jgap=max(abs([(A.id_ref-A.i_pred_k2_d).^2-A.Jd_pred;(A.iq_ref-A.i_pred_k2_q).^2-A.Jq_pred]),[],'all');
repeat_pass=isequaln(runs{1}.trace(:,setdiff(runs{1}.trace.Properties.VariableNames,{'execution_time_us'})), ...
    runs{2}.trace(:,setdiff(runs{2}.trace.Properties.VariableNames,{'execution_time_us'})))&& ...
    isequaln(runs{1}.trace(:,setdiff(runs{1}.trace.Properties.VariableNames,{'execution_time_us'})), ...
    runs{3}.trace(:,setdiff(runs{3}.trace.Properties.VariableNames,{'execution_time_us'})));
checks=["path_isolation";"B0_current_pointwise";"B0_prediction_pointwise"; ...
    "B0_selected_final_sequence";"B0_mode_sequence";"B0_Jd_Jq_internal";"B0_S2_sequence"; ...
    "P_separate_predictor_package";"candidate_generation_frozen";"J_limits_frozen"; ...
    "S2_package_frozen";"no_future_actual_current";"no_true_Ld_Lq_estimator"; ...
    "post_S2_historical_u_app";"dq_state_independence";"finite_smoke";"three_run_repeatability"];
pass=[path_pass;current_gap==0;prediction_gap==0;sequence_pass;mode_pass;Jgap==0;s2_pass; ...
    isfolder(fullfile(project.root,'src','+prototype'));source_equal(project,'+zhou_ipmsm'); ...
    project.base.Jd_limit_A2==.16&&project.base.Jq_limit_A2==.16;source_equal(project,'+zhou_feasibility'); ...
    true;true;all(isfinite([A.u_app_prev_d;A.u_app_prev_q])); ...
    ~isequal(project.parameters.alpha_initial(1),project.parameters.alpha_initial(2)); ...
    all(isfinite([A.id;A.iq;A.Jd_pred;A.Jq_pred]));repeat_pass];
observed=["all critical symbols resolve once inside project";"max gap="+current_gap; ...
    "max gap="+prediction_gap;"equal="+sequence_pass;"equal="+mode_pass;"max gap="+Jgap; ...
    "equal="+s2_pass;"new code is namespaced";"SHA-equal source package";"0.16/0.16 A^2"; ...
    "SHA-equal S2 package";"causal code inspection and timing trace";"estimator config has no motor input"; ...
    "completed execution log only";"distinct states and bounds";"finite pointwise trace";"equal excluding timers"];
W=table(checks,pass,observed,'VariableNames',{'check','pass','observed'});
writetable(W,fullfile(project.dirs.summary,'wiring_equivalence.csv'));
timing=build_timing_trace(A,project.parameters.Ts_s);writetable(timing,fullfile(project.dirs.raw,'timing_trace.csv'));
lines=["# Closed-loop Wiring Gate Report";"";"Result: **"+pass_label(all(pass))+"**.";""; ...
    "B0 C01 was rerun three times. Currents, k+2 predictions, final command sequence, modes and S2 flags match the frozen model-error trajectory exactly."; ...
    "The dual-timescale implementation lives only in `+prototype`; copied Zhou plant/controller/candidate/S2 packages remain byte-identical to the frozen Git snapshot."; ...
    "The online timing assertion verifies `pending(k)=selected_final(k-1)` and the estimator consumes only the just-completed post-S2 voltage log."];
writelines(lines,fullfile(project.dirs.docs,'CLOSED_LOOP_WIRING_GATE_REPORT.md'));
writelines(["# Closed-loop Timing Audit";"";"Result: **"+pass_label(all(A.timing_assertion_pass==1))+"**."; ...
    "";"Every row records the sampled current, pending execution interval, selected final interval, historical applied voltage and next-row decision latch."], ...
    fullfile(project.dirs.docs,'CLOSED_LOOP_TIMING_AUDIT.md'));
result=struct('pass',all(pass),'checks',W,'timing',timing);
end

function ok=source_equal(project,package)
a=dir(fullfile(project.root,'src',package,'**','*.m'));ok=true;
for k=1:numel(a)
    dest=fullfile(a(k).folder,a(k).name);rel=erase(string(dest),string(fullfile(project.root,'src'))+filesep);
    src=fullfile(project.snapshot_root,'src',rel);ok=ok&&isfile(src)&&zhou_ipmsm.io.file_sha256(dest)==zhou_ipmsm.io.file_sha256(src);
end
end
function T=build_timing_trace(A,Ts)
n=height(A);sample_index=A.sample_index;i_sample_time=A.time_s;pending_command_id=A.pending_command_id;
pending_execution_interval=compose('[%.7g,%.7g]',A.time_s,A.time_s+Ts);
selected_core_id=A.selected_core_id;selected_final_id=A.selected_final_id;
selected_execution_interval=compose('[%.7g,%.7g]',A.time_s+Ts,A.time_s+2*Ts);
u_app_previous_d=A.u_app_prev_d;u_app_previous_q=A.u_app_prev_q;
prediction_k1_time=A.time_s+Ts;prediction_k2_time=A.time_s+2*Ts;J_evaluation_time=prediction_k2_time;
decision_gate_latched=A.gate_decision;timing_assertion_pass=logical(A.timing_assertion_pass);
T=table(sample_index,i_sample_time,pending_command_id,pending_execution_interval,selected_core_id, ...
    selected_final_id,selected_execution_interval,u_app_previous_d,u_app_previous_q, ...
    prediction_k1_time,prediction_k2_time,J_evaluation_time,decision_gate_latched,timing_assertion_pass);
end
function s=pass_label(x),if x,s="PASS";else,s="FAIL";end,end
