function s=control_scenario(project)
%CONTROL_SCENARIO Canonical P1, 500 rpm, 20 A, 48 V, 5 ms case.
b=project.base;
s=struct('name',"500rpm_20A_P1",'speed_rpm',500,'theta0_rad',0.17, ...
    'id0_A',0,'iq0_A',0,'id_ref_A',0,'iq_ref_A',20, ...
    'reference_ramp_s',b.reference_ramp_s,'reference_profile',"ramp", ...
    'simulation_time_s',b.simulation_time_s,'steady_window_start_s',b.steady_window_start_s, ...
    'Jd_limit_A2',b.Jd_limit_A2,'Jq_limit_A2',b.Jq_limit_A2, ...
    'alpha_mode',"axis_specific",'F_estimator',"algebraic_iter11", ...
    'integration_step_s',b.integration_step_s,'motor_model',"P1", ...
    'dc_bus_V',b.dc_bus_V,'voltage_vector_scale',b.voltage_vector_scale, ...
    'plant_Ld_scale',1,'plant_Lq_scale',1,'plant_Rs_scale',1,'plant_psi_f_scale',1);
end
