function data=summary_to_long_table(run_id,experiment,summary)
%SUMMARY_TO_LONG_TABLE Normalize one summary struct into results/metrics.csv.

definitions={ ...
 'id_rmse_A','A';'iq_rmse_A','A';'total_current_rmse_A','A'; ...
 'phase_current_thd_percent','percent'; ...
 'phase_current_thd_cycle_boundary_percent','percent'; ...
 'phase_current_thd_40_harmonic_percent','percent'; ...
 'phase_current_wideband_distortion_percent','percent'; ...
 'phase_current_fundamental_rms_A','A'; ...
 'phase_current_distortion_rms_A','A'; ...
 'torque_mean_Nm','N*m'; ...
 'torque_peak_to_peak_Nm','N*m';'average_switching_frequency_Hz','Hz'; ...
 'controller_time_mean_s','s';'controller_time_worst_s','s'; ...
 'iq_ripple_factor','ratio';'Cf','percent*kHz';'rectangle_area_mean_V2','V^2'; ...
 'Jd_mean','A^2';'Jq_mean','A^2';'Jd_max','A^2';'Jq_max','A^2'; ...
 'predicted_d_violation_rate','ratio';'predicted_q_violation_rate','ratio'; ...
 'actual_k2_d_violation_rate','ratio';'actual_k2_q_violation_rate','ratio'; ...
 'case1_ratio','ratio';'case2_ratio','ratio';'case3_ratio','ratio'; ...
 'table_I_correction_rate','ratio';'table_I_fallback_rate','ratio'; ...
 'table_II_mismatch_rate','ratio';'phase_feasibility_flip_rate','ratio'; ...
 'degenerate_single_point_rate','ratio';'illegal_command_count','count'; ...
 'numeric_negative_dwell_count','count'; ...
 'waveform_endpoint_max_residual_A','A'; ...
 'waveform_sample_period_s','s'; ...
 'deadtime_delta_voltage_rms_V','V'; ...
 'deadtime_delta_voltage_max_V','V'; ...
 'deadtime_adverse_events_mean','count/cycle'};
n=size(definitions,1);
metric=string(definitions(:,1)); unit=string(definitions(:,2)); value=zeros(n,1);
for k=1:n
    value(k)=summary.(metric(k));
end
data=table(repmat(string(run_id),n,1),repmat(string(experiment),n,1), ...
    repmat(string(summary.method),n,1),repmat(string(summary.scenario),n,1), ...
    metric,value,unit,repmat(summary.steady_start_s,n,1), ...
    repmat(summary.steady_end_s,n,1),repmat("PASS",n,1), ...
    'VariableNames',{'run_id','experiment','method','scenario','metric','value', ...
    'unit','window_start_s','window_end_s','status'});
end
