function [comparison,summary] = compare_pointwise_runs(reference,new_run,scenario,project)
%COMPARE_POINTWISE_RUNS Strict cycle-aligned comparison of two closed loops.

R=reference.log; N=new_run.log;
assert(height(R)==height(N),'ZhouValidation:P0Length', ...
    'Closed-loop traces have different cycle counts.');
n=height(R); cycle_index=(1:n).';
[duration_error,duration_structure_match]=duration_compare( ...
    R.sequence_durations_s,N.sequence_durations_s,project.thresholds.numeric_tolerance);
[applied_duration_error,applied_duration_structure_match]=duration_compare( ...
    R.applied_sequence_durations_s,N.applied_sequence_durations_s, ...
    project.thresholds.numeric_tolerance);
case_match=R.case_selected==N.case_selected & R.case_applied==N.case_applied;
vector_match=R.sequence_vector_ids==N.sequence_vector_ids & ...
    R.applied_sequence_vector_ids==N.applied_sequence_vector_ids;
duration_structure_match=duration_structure_match & applied_duration_structure_match;

id_error_A=N.id_A-R.id_A; iq_error_A=N.iq_A-R.iq_A;
Fd_error=N.Fhat_d-R.Fhat_d; Fq_error=N.Fhat_q-R.Fhat_q;
id_pred_k1_error_A=N.id_pred_k1-R.id_pred_k1;
iq_pred_k1_error_A=N.iq_pred_k1-R.iq_pred_k1;
id_pred_k2_error_A=N.id_pred_k2-R.id_pred_k2;
iq_pred_k2_error_A=N.iq_pred_k2-R.iq_pred_k2;
U3d_error_V=N.U3d_V-R.U3d_V; U3q_error_V=N.U3q_V-R.U3q_V;
U4d_error_V=N.U4d_V-R.U4d_V; U4q_error_V=N.U4q_V-R.U4q_V;
torque_error_Nm=N.torque_Nm-R.torque_Nm;
predicted_margin_d_error_A2=(scenario.Jd_limit_A2-N.Jd)- ...
    (scenario.Jd_limit_A2-R.Jd);
predicted_margin_q_error_A2=(scenario.Jq_limit_A2-N.Jq)- ...
    (scenario.Jq_limit_A2-R.Jq);
[ref_exceed_d,ref_exceed_q]=actual_exceedance(R,scenario);
[new_exceed_d,new_exceed_q]=actual_exceedance(N,scenario);
actual_exceedance_d_error_A=new_exceed_d-ref_exceed_d;
actual_exceedance_q_error_A=new_exceed_q-ref_exceed_q;
switching_action_match=R.switching_actions_applied==N.switching_actions_applied;

comparison=table(repmat(string(scenario.name),n,1),cycle_index,R.time_s, ...
    R.id_A,N.id_A,id_error_A,R.iq_A,N.iq_A,iq_error_A,Fd_error,Fq_error, ...
    id_pred_k1_error_A,iq_pred_k1_error_A,id_pred_k2_error_A, ...
    iq_pred_k2_error_A,R.case_selected,N.case_selected,R.case_applied, ...
    N.case_applied,case_match,R.sequence_vector_ids,N.sequence_vector_ids, ...
    R.applied_sequence_vector_ids,N.applied_sequence_vector_ids,vector_match, ...
    duration_structure_match,duration_error,applied_duration_error, ...
    U3d_error_V,U3q_error_V,U4d_error_V,U4q_error_V, ...
    predicted_margin_d_error_A2,predicted_margin_q_error_A2, ...
    actual_exceedance_d_error_A,actual_exceedance_q_error_A, ...
    switching_action_match,torque_error_Nm, ...
    'VariableNames',{'scenario','cycle_index','time_s','id_ref_impl_A', ...
    'id_ipmsm_impl_A','id_error_A','iq_ref_impl_A','iq_ipmsm_impl_A', ...
    'iq_error_A','Fd_error','Fq_error','id_pred_k1_error_A', ...
    'iq_pred_k1_error_A','id_pred_k2_error_A','iq_pred_k2_error_A', ...
    'case_selected_ref','case_selected_new','case_applied_ref','case_applied_new', ...
    'case_match','selected_vectors_ref','selected_vectors_new', ...
    'applied_vectors_ref','applied_vectors_new','vector_match', ...
    'duration_structure_match','selected_duration_max_error_s', ...
    'applied_duration_max_error_s','U3d_error_V','U3q_error_V','U4d_error_V', ...
    'U4q_error_V','predicted_margin_d_error_A2','predicted_margin_q_error_A2', ...
    'actual_exceedance_d_error_A','actual_exceedance_q_error_A', ...
    'switching_action_match','torque_error_Nm'});

max_current=max(abs([id_error_A;iq_error_A]));
max_U3=max(abs([U3d_error_V;U3q_error_V]));
max_duration=max([duration_error;applied_duration_error]);
summary_relative=max(relative_error_vector(R,N));
illegal=nnz(R.illegal_selected|R.illegal_applied|N.illegal_selected|N.illegal_applied);
negative=nnz([R.selected_min_duration_s;R.applied_min_duration_s; ...
    N.selected_min_duration_s;N.applied_min_duration_s] < -project.thresholds.numeric_tolerance);
passed=all(case_match) && all(vector_match) && all(duration_structure_match) && ...
    max_duration<project.thresholds.p0_duration_max_abs_s && ...
    max_current<project.thresholds.p0_current_max_abs_A && ...
    max_U3<project.thresholds.p0_U3_max_abs_V && illegal==0 && negative==0 && ...
    summary_relative<project.thresholds.p0_summary_relative;
summary=table(string(project.run_id),string(project.timestamp), ...
    string(scenario.name),mean(case_match),mean(vector_match), ...
    mean(duration_structure_match),max_duration,max_current,max_U3, ...
    max(abs([U4d_error_V;U4q_error_V])),summary_relative,illegal,negative, ...
    string(pass_text(passed)),'VariableNames',{'run_id','timestamp','scenario', ...
    'case_match_rate','vector_match_rate','duration_structure_match_rate', ...
    'duration_max_abs_error_s','current_max_abs_error_A','U3_max_abs_error_V', ...
    'U4_max_abs_error_V','summary_max_relative_error','illegal_commands', ...
    'negative_durations','pass_fail'});
end

function [errors,structure]=duration_compare(a,b,tolerance)
n=numel(a); errors=zeros(n,1); structure=false(n,1);
for k=1:n
    av=parse_numbers(a(k)); bv=parse_numbers(b(k));
    if numel(av)~=numel(bv), errors(k)=Inf; continue; end
    errors(k)=max(abs(av-bv));
    structure(k)=isequal(av>tolerance,bv>tolerance);
end
end
function values=parse_numbers(value)
values=str2double(split(string(value),';')).';
end
function [d,q]=actual_exceedance(L,s)
n=height(L); id2=[L.id_A(3:end);NaN;NaN]; iq2=[L.iq_A(3:end);NaN;NaN];
d=max(0,abs(L.id_ref_A-id2)-sqrt(s.Jd_limit_A2));
q=max(0,abs(L.iq_ref_A-iq2)-sqrt(s.Jq_limit_A2));
end
function values=relative_error_vector(R,N)
rb=[sqrt(mean(R.id_A.^2)) sqrt(mean(R.iq_A.^2)) ...
    mean(abs(R.torque_Nm)) mean(R.switching_actions_applied)];
nb=[sqrt(mean(N.id_A.^2)) sqrt(mean(N.iq_A.^2)) ...
    mean(abs(N.torque_Nm)) mean(N.switching_actions_applied)];
values=abs(nb-rb)./max(abs(rb),eps);
end
function value=pass_text(condition)
if condition, value="PASS"; else, value="FAIL"; end
end
