function generate_documents(cfg,D,V)
%GENERATE_DOCUMENTS Build the auditable handoff and formal reports.
write_scope(cfg);write_evidence(cfg);write_duplicate(cfg);write_path_conflict(cfg);
write_report(cfg,D,V);write_decision(cfg,D);write_limitations(cfg,D);
write_readme(cfg,D);write_run(cfg);write_changelog(cfg);write_handoff(cfg,D,V);
end

function write_scope(cfg)
L=["# Project Scope";""; ...
"本工程只审计 B0 原始 Zhou `k→k+2` 电流预测残差中的 6 阶/12 阶电角同步分量、跨周期/跨工况重复性、与独立 Jd/Jq false-safe 的描述性关联，以及 held-out 离线约束分类变化。";""; ...
"## 允许";"";"- 读取并冻结 B0 数据。";"- 时间域、FFT、电角度域 order tracking。";"- calibration 周期拟合与 held-out 周期/工况验证。";"- offline counterfactual constraint classification。";""; ...
"## 禁止";"";"- 修改 Zhou 控制器、plant、S2、Jd/Jq 上限或矢量逻辑。";"- 继续 dual-timescale F/alpha、RLS、ESO、AULTS 或免疫算法。";"- 实现谐振器、谐波注入或周期补偿器。";"- 把离线拟合称为闭环性能或把诊断 candidate bank 称为原生决策。";""; ...
"固定约束为 `Jd_limit=Jq_limit="+cfg.Jd_limit_A2+" A^2`，预注册阶次仅为 6 和 12；1—20 阶只作完整谱展示。"];write(cfg,'docs/PROJECT_SCOPE.md',L);
end
function write_evidence(cfg)
L=["# Frozen Evidence Base";""; ...
"实际使用的完整 B0 数据来自 archived dual-timescale prototype 内、Git commit `2aa4e7f` 恢复的 model-error snapshot：`reference/upstream_snapshots/zhou_icf_mpc_model_error_decomposition_iter01/results/raw/model_error_samples.csv`。"; ...
"本工程在分析前将其字节级复制到 `reference/frozen_data/model_error_samples.csv`；另复制 prototype 的五工况 `closed_loop_samples_B0.csv` 做 4,821 行点对点独立重现交叉检查。未重新运行 B0。";""; ...
"冻结事实：原主域 false-safe 3.029664%，全量 3.059661%；sequence 误差约 1e-13；plant oracle 可零误差重放；F/alpha 离线 oracle 有效但 causal dual-timescale online prototype 失败；P 的五工况 false-safe 3.526239%→3.753128%，向量 RMS 0.0613189 A→0.132352 A；B1/B2/RLS 未过门禁。";""; ...
"完整来源、解析路径和逐文件 SHA-256 位于 `audit/`。所有复制文件均在 `COPIED_FILE_PROVENANCE.csv` 记录双端哈希。"];write(cfg,'docs/FROZEN_EVIDENCE_BASE.md',L);
end
function write_duplicate(cfg)
L=["# Duplicate Work Check";""; ...
"本工程读取了 model-error HANDOFF/report/predictor_metrics/residual_spectrum 与 dual-timescale prototype README/HANDOFF/final report/final_decision。";""; ...
"未重复：Jd/Jq 扫描、sequence decomposition、plant oracle、F/alpha 归因、dual-timescale 参数整定、B1/B2/RLS gate、控制器或 S2 设计。"; ...
"新增且唯一的工作是：严格 6/12 预注册频谱、电角度逐周期系数、calibration/validation 隔离、leave-one-cycle/case-out、false-safe 相位与匹配事件、held-out 离线约束重分类。"; ...
"因此之前的 6ωe/12ωe 描述性观察不是本工程结论的替代品，本工程也不重新修补已停止的双时间尺度路线。"];write(cfg,'docs/DUPLICATE_WORK_CHECK.md',L);
end
function write_path_conflict(cfg)
S=readtable(fullfile(cfg.audit_dir,'SOURCE_PROJECT_STATUS.csv'),'TextType','string','Delimiter',',');
stub=S.project_id(contains(S.status,"STUB")|contains(S.status,"MISSING"));
L=["# Path Conflict Report";"";"顶层路径中以下项目为空 stub 或缺失，未被当作完整源码：`"+strjoin(stub,"`, `")+"`。"; ...
"model-error 完整快照从 dual-timescale prototype 的 Git 冻结副本解析；feasibility、sequence、Jd/Jq 则从该完整快照内的 evidence/runtime 解析。"; ...
"`audit/SOURCE_PROJECTS.csv` 保存 requested_path、resolved_path 和选择理由。新工程未把任何 sibling 目录加入 MATLAB path。"; ...
"新工程绝对路径：`"+string(cfg.root)+"`；分支：`"+cfg.branch_name+"`。"];write(cfg,'docs/PATH_CONFLICT_REPORT.md',L);
end
function write_report(cfg,D,V)
L=["# Periodic Residual Audit Report";"";"## Formal outcome";""; ...
"**"+D.decision_code+" — "+D.decision_label+"**。这是纯诊断结论；闭环轨迹和控制器没有改变。";""; ...
"## Registered evidence";""; ...
"- 正式主域有效工况/完整电气周期：**"+D.valid_primary_case_count+" / "+D.valid_primary_cycle_count+"**（含次级动态证据为 "+D.valid_all_case_count+" / "+D.valid_all_cycle_count+"）。"; ...
"- 6阶/12阶稳定出现工况：**"+D.order6_stable_case_count+" / "+D.order12_stable_case_count+"**。"; ...
"- 6阶/12阶主域峰值 SNR 中位数：**"+f(D.order6_peak_snr_db_median)+" / "+f(D.order12_peak_snr_db_median)+" dB**；保守最小值 "+f(D.order6_peak_snr_db_min)+" / "+f(D.order12_peak_snr_db_min)+" dB。"; ...
"- 最大周期幅值 CV：**"+pct(D.order6_amplitude_cv_max)+" / "+pct(D.order12_amplitude_cv_max)+"**；最小相位 R：**"+f(D.order6_phase_R_min)+" / "+f(D.order12_phase_R_min)+"**。"; ...
"- 频率同步：**"+yn(D.frequency_synchronization_pass)+"**；跨周期正迁移率 "+pct(D.cross_cycle_positive_rate)+"；同速跨工况正迁移率 "+pct(D.cross_case_positive_rate)+"。"; ...
"- 具相位集中且事件数足够的主域工况（6/12阶）：**"+D.order6_associated_case_count+" / "+D.order12_associated_case_count+"**。关联是描述性的，不称因果。";""; ...
"## Held-out offline counterfactual constraint classification";""; ...
"- 仅6阶：false-safe 相对下降 **"+pct(D.order6_false_safe_relative_reduction)+"**。"; ...
"- 仅12阶：false-safe 相对下降 **"+pct(D.order12_false_safe_relative_reduction)+"**。"; ...
"- 6+12阶：false-safe 相对下降 **"+pct(D.order6_12_false_safe_relative_reduction)+"**，false-alarm **+"+f(D.order6_12_false_alarm_change_pp)+" pp**，预测向量 RMS 下降 **"+pct(D.order6_12_rms_relative_reduction)+"**。"; ...
"- B0/6+12 held-out RMS：`"+f(D.B0_validation_vector_rms_A)+" A` / `"+f(D.order6_12_validation_vector_rms_A)+" A`。";""; ...
"## Gate decision";"";"12 项最低门槛全部通过：**"+yn(D.all_prototype_gates_pass)+"**。因此只允许下一独立工程研究轻量周期补偿原型；本工程本身没有实现补偿器。"; ...
"冻结上游复核：`"+V.status+"`，added/deleted/modified = `"+V.added_count+"/"+V.deleted_count+"/"+V.modified_count+"`。"];write(cfg,'docs/PERIODIC_RESIDUAL_AUDIT_REPORT.md',L);
end
function write_decision(cfg,D)
L=["# Decision and Next Step";"";"主结论：**"+D.decision_code+" — "+D.decision_label+"**。";""; ...
"允许进入下一原型：**"+yn(D.prototype_authorized)+"**。若启动，必须使用独立工程名 `"+D.next_project+"`；当前工程禁止加入补偿器。"; ...
"授权只表示所有最低诊断门槛在本数据集上通过，不表示已形成算法、已证明闭环收益或已通过硬件验证。"; ...
"任何下一工程必须重新执行闭环、实时计算、稳定性、扰动鲁棒性与硬件门禁，且不能用 held-out 未来数据在线更新系数。"];write(cfg,'docs/DECISION_AND_NEXT_STEP.md',L);
end
function write_limitations(cfg,D)
L=["# Known Limitations";""; ...
"1. 100/200 rpm 的 nominal/light core 稳态段不足 3 个完整电气周期，按预注册规则排除；正式主域由 300/400/500 rpm 的 11 个完整工况组成。"; ...
"2. 500 rpm 有效主域只有 C09 S2 boundary；固定速度同步覆盖三组速度，但 500 rpm 跨工况迁移证据不足。"; ...
"3. 同速 leave-one-case-out 6+12 仅 "+pct(D.cross_case_positive_rate)+" 为正，400 rpm 参数失配组存在负迁移；任何原型不得假设单一全局系数。"; ...
"4. 聚合 false-safe 相位集中度低于若干单工况，相位关联具有工况异质性；报告只称关联。"; ...
"5. 6+12 离线分类虽过聚合门槛，部分单工况 false-alarm 增量超过 0.5 pp；原型必须设置单工况安全门禁。"; ...
"6. 电角度端点存在小比例线性外推，比例与插值往返 RMS 已逐行保留；FFT/精确回归/order tracking 一致且无 aliasing。"; ...
"7. 固定 Jd/Jq=0.16 A²；未重扫阈值，未重构原生候选 bank。"; ...
"8. 全部改善均为 held-out offline counterfactual constraint classification，不是闭环、实时或硬件性能。"; ...
"9. 结论仅覆盖冻结的 24 工况、24,153 行 B0 数据和 R2024b 实现。"];write(cfg,'docs/KNOWN_LIMITATIONS.md',L);
end
function write_readme(cfg,D)
L=["# Zhou ICF-MPC Periodic Residual Audit iter01";""; ...
"Outcome: **"+D.decision_code+" — "+D.decision_label+"**. The audit is isolated, deterministic, cycle-held-out and upstream-hash-checked.";""; ...
"MATLAB R2024b: `run_periodic_residual_audit()` or `run_periodic_residual_audit('all')`. Available stages: `inventory`, `baseline`, `data`, `spectrum`, `order`, `phase`, `false_safe`, `counterfactual`, `audit`, `all`.";""; ...
"Primary evidence is under `results/summary`, 16 figures under `results/figures`, and the formal report at `docs/PERIODIC_RESIDUAL_AUDIT_REPORT.md`."; ...
"No controller, plant, S2, constraint limit, dual-timescale estimator, resonator, or periodic compensator is implemented here. Offline results are not closed-loop performance."];write(cfg,'README.md',L);
end
function write_run(cfg)
L=["# Run and Reproduce";"";"Environment: MATLAB R2024b with Signal Processing Toolbox; deterministic seed `"+cfg.random_seed+"`.";""; ...
"```matlab";"cd('"+replace(string(cfg.root),'\','/')+"');";"outcome = run_periodic_residual_audit('all');";"```";""; ...
"The first phase verifies/copies frozen data and hashes upstreams. The B0 gate must pass before analysis. `all` regenerates every registered CSV, 16 figures, formal decision, handoff, and AFTER hashes."; ...
"No sibling is added to MATLAB path. To test a stage, replace `all` with any supported mode; each mode deterministically executes its prerequisites."; ...
"Expected final code is read from `results/summary/final_decision.csv`; never infer success from a figure alone."];write(cfg,'RUN_AND_REPRODUCE.md',L);
end
function write_changelog(cfg)
L=["# Changelog";"";"## iter01 — 2026-07-15";""; ...
"- Created isolated branch/project and resolved upstream stubs to frozen snapshots.";"- Froze 24-case B0 data and five-case independent reproduction overlap."; ...
"- Added deterministic steady-window registry, Hann FFT, exact sinus regression, and 256-point/cycle order tracking."; ...
"- Added cycle-isolated amplitude/phase gates, leave-one-cycle-out and same-speed leave-one-case-out transfer."; ...
"- Added held-out false-safe phase/matched-window association and 6/12/6+12 offline constraint classification."; ...
"- Added A—E hard decision, 16 figures, SHA-256 before/after proof, reports and handoff.";"- No control algorithm was changed or added."];write(cfg,'CHANGELOG.md',L);
end
function write_handoff(cfg,D,V)
L=["# HANDOFF — Zhou 周期残差机理审计";""; ...
"1. **项目目标。** 审计 B0 的 6/12 电角同步残差、重复性、false-safe 关联和 held-out 离线分类价值。"; ...
"2. **双时间尺度为何停止。** P 在五工况把 false-safe 3.526239% 恶化至 3.753128%，向量 RMS 0.0613189 A 恶化至 0.132352 A；B1/B2/RLS 均未过门禁。"; ...
"3. **B0 数据源。** model-error Git 冻结快照的 24 工况 `model_error_samples.csv`，本地字节级副本在 `reference/frozen_data`；未重跑 B0。"; ...
"4. **时序与残差。** row k 保存 `id/iq(k)`、`id_pred/iq_pred(k+2|k)` 和 `id_actual/iq_actual(k+2)`；`e=actual-pred`。"; ...
"5. **有效窗口。** 注册 steady、完整结束、非 stress、至少3周期、非零速度；FFT 另要求速度 CV≤1% 与 20阶 Nyquist。"; ...
"6. **FFT。** 整数周期、去均值/线性趋势、Hann 描述谱，并行无窗精确正弦回归，记录噪声底/泄漏/aliasing。"; ...
"7. **Order tracking。** 每周期256电角点，线性重采样，6+12联合拟合，正/负旋转复系数均保存。"; ...
"8. **6阶。** 稳定主域工况 "+D.order6_stable_case_count+"，SNR 中位数 "+f(D.order6_peak_snr_db_median)+" dB，最大 CV "+pct(D.order6_amplitude_cv_max)+"，最小 R "+f(D.order6_phase_R_min)+"。"; ...
"9. **12阶。** 稳定主域工况 "+D.order12_stable_case_count+"，SNR 中位数 "+f(D.order12_peak_snr_db_median)+" dB，最大 CV "+pct(D.order12_amplitude_cv_max)+"，最小 R "+f(D.order12_phase_R_min)+"。"; ...
"10. **幅值重复性。** 两阶全部稳定行通过 CV≤30% 与 calibration/validation 幅值门禁。"; ...
"11. **相位重复性。** 两阶稳定行最小 R 如上，均通过 R≥0.7；工况间 false-safe 相位仍异质。"; ...
"12. **跨周期。** 6+12 leave-one-cycle-out 正迁移率 "+pct(D.cross_cycle_positive_rate)+"，通过。"; ...
"13. **跨工况。** 同速 leave-one-case-out 正迁移率 "+pct(D.cross_case_positive_rate)+"，通过最低门槛但非普遍。"; ...
"14. **false-safe 关联。** 6/12 阶分别有 "+D.order6_associated_case_count+"/"+D.order12_associated_case_count+" 个主域工况满足事件数与相位集中条件；只称关联。"; ...
"15. **离线反事实。** 仅6/仅12/6+12 false-safe 相对下降 "+pct(D.order6_false_safe_relative_reduction)+"/"+pct(D.order12_false_safe_relative_reduction)+"/"+pct(D.order6_12_false_safe_relative_reduction)+"；组合 FA +"+f(D.order6_12_false_alarm_change_pp)+" pp，RMS -"+pct(D.order6_12_rms_relative_reduction)+"。"; ...
"16. **A—E 结论。** "+D.decision_code+" — "+D.decision_label+"。"; ...
"17. **是否允许下一原型。** "+yn(D.prototype_authorized)+"，只允许独立项目，不得在本工程实现。"; ...
"18. **下一工程名。** `"+D.next_project+"`。"; ...
"19. **关键路径。** CSV `results/summary`，逐样本 `results/raw/periodic_residual_samples.csv`，图 `results/figures`，正式报告 `docs/PERIODIC_RESIDUAL_AUDIT_REPORT.md`。"; ...
"20. **上游 SHA-256。** BEFORE/AFTER 共 "+V.before_file_count+"/"+V.after_file_count+" 行；added/deleted/modified="+V.added_count+"/"+V.deleted_count+"/"+V.modified_count+"，`"+V.status+"`。"; ...
"21. **已知限制。** 见 `docs/KNOWN_LIMITATIONS.md`，尤其 100/200 rpm 周期不足、500 rpm 单一有效主域、400 rpm 跨工况负迁移与单工况 FA 异质性。"; ...
"22. **措辞禁令。** 所有修正结果只能称 offline counterfactual constraint classification；禁止称闭环算法或控制性能。"];write(cfg,'HANDOFF.md',L);
end
function write(cfg,rel,L)
p=fullfile(cfg.root,rel);parent=fileparts(p);if ~isfolder(parent),mkdir(parent);end;writelines(L,p,'Encoding','UTF-8');
end
function s=f(x),s=string(sprintf('%.6g',x));end
function s=pct(x),s=string(sprintf('%.3f%%',100*x));end
function s=yn(x),if x,s="YES";else,s="NO";end,end
