function inventory(cfg)
%INVENTORY Locate requested upstreams, classify stubs, freeze hashes/data.
rng(cfg.random_seed, 'twister');

[projects, status] = locate_projects(cfg);
zhou_periodic.write_table(projects, fullfile(cfg.audit_dir, 'SOURCE_PROJECTS.csv'));
zhou_periodic.write_table(status, fullfile(cfg.audit_dir, 'SOURCE_PROJECT_STATUS.csv'));

fprintf('Phase 0: hashing %d resolved upstream projects...\n', height(projects));
before = hash_projects(projects);
zhou_periodic.write_table(before, fullfile(cfg.audit_dir, 'SOURCE_SHA256_BEFORE.csv'));

provenance = freeze_selected_files(cfg);
zhou_periodic.write_table(provenance, fullfile(cfg.audit_dir, 'COPIED_FILE_PROVENANCE.csv'));

pending = table("PENDING_AFTER_FINALIZATION", height(before), NaN, NaN, NaN, ...
    'VariableNames', {'status','before_file_count','after_file_count', ...
    'added_count','deleted_count'});
pending.modified_count = NaN;
pending.unchanged_count = NaN;
zhou_periodic.write_table(pending, ...
    fullfile(cfg.audit_dir, 'FROZEN_UPSTREAM_VALIDATION.csv'));

write_selection_doc(cfg, projects, status, provenance);
end

function [P, S] = locate_projects(cfg)
requested = [ ...
    "zhou_icf_mpc_model_error_decomposition_iter01"; ...
    "zhou_icf_mpc_dual_timescale_design_iter01"; ...
    "zhou_icf_mpc_dual_timescale_prototype_iter01"; ...
    "zhou_icf_mpc_ipmsm_probe_iter01"; ...
    "zhou_icf_mpc_ipmsm_feasibility_control_iter01"; ...
    "zhou_icf_mpc_sequence_decomposition_iter01"; ...
    "zhou_icf_mpc_constraint_audit_v1"];
ids = ["model_error";"dual_design";"dual_prototype";"ipmsm_probe"; ...
    "s2_feasibility";"sequence_decomposition";"jd_jq_audit"];
reqPaths = strings(size(requested));
for k = 1:numel(requested), reqPaths(k) = fullfile(cfg.parent, requested(k)); end

resolved = reqPaths;
reason = repmat("direct non-empty project", size(requested));
resolved(1) = string(cfg.model_error_snapshot);
reason(1) = "top-level stub; complete Git-frozen snapshot restored in prototype";
resolved(5) = fullfile(cfg.model_error_snapshot, 'reference', ...
    'upstream_snapshots', 's2_feasibility');
reason(5) = "top-level stub; frozen evidence plus executable +zhou_feasibility in model-error snapshot";
resolved(6) = fullfile(cfg.model_error_snapshot, 'reference', ...
    'upstream_snapshots', 'sequence_decomposition');
reason(6) = "top-level stub; frozen evidence plus executable +zhou_sequence in model-error snapshot";
constraintNested = fullfile(cfg.parent, 'baseline_zhou-main', ...
    'baseline_zhou-main', 'zhou_icf_mpc_constraint_audit_v1');
if isfolder(constraintNested) && count_files(constraintNested) > 0
    resolved(7) = constraintNested;
    reason(7) = "auto-located nested complete project";
else
    resolved(7) = fullfile(cfg.model_error_snapshot, 'reference', ...
        'upstream_snapshots', 'jd_jq_audit');
    reason(7) = "requested and nested paths are stubs; resolved to model-error frozen jd_jq evidence snapshot";
end

P = table(ids, requested, reqPaths, resolved, reason, ...
    'VariableNames', {'project_id','requested_name','requested_path', ...
    'resolved_path','selection_reason'});

reqExists = false(height(P),1); reqFiles = zeros(height(P),1);
resExists = false(height(P),1); resFiles = zeros(height(P),1);
resBytes = zeros(height(P),1); state = strings(height(P),1);
for k = 1:height(P)
    reqExists(k) = isfolder(P.requested_path(k));
    if reqExists(k), reqFiles(k) = count_files(P.requested_path(k)); end
    resExists(k) = isfolder(P.resolved_path(k));
    if resExists(k)
        [resFiles(k), resBytes(k)] = count_files(P.resolved_path(k));
    end
    if ~reqExists(k), state(k) = "MISSING_REQUESTED";
    elseif reqFiles(k) == 0, state(k) = "EMPTY_STUB";
    else, state(k) = "NONEMPTY_DIRECT";
    end
    if resExists(k) && resFiles(k) > 0
        state(k) = state(k) + "_RESOLVED_COMPLETE";
    elseif ~resExists(k)
        state(k) = state(k) + "_UNRESOLVED";
    end
end
S = table(ids, reqExists, reqFiles, resExists, resFiles, resBytes, state, ...
    'VariableNames', {'project_id','requested_exists','requested_file_count', ...
    'resolved_exists','resolved_file_count','resolved_bytes','status'});
assert(all(S.resolved_exists & S.resolved_file_count > 0), ...
    'One or more required upstream projects could not be resolved.');
end

function [n, bytes] = count_files(path)
d = dir(fullfile(path, '**', '*'));
d = d(~[d.isdir]);
n = numel(d);
if n == 0, bytes = 0; else, bytes = sum([d.bytes]); end
end

function T = hash_projects(P)
project_id = strings(0,1); relative_path = strings(0,1);
absolute_path = strings(0,1); bytes = zeros(0,1); sha256 = strings(0,1);
for p = 1:height(P)
    root = char(P.resolved_path(p));
    d = dir(fullfile(root, '**', '*'));
    d = d(~[d.isdir]);
    [~,ix] = sort(lower(string(fullfile({d.folder}, {d.name}))));
    d = d(ix);
    for k = 1:numel(d)
        f = fullfile(d(k).folder, d(k).name);
        project_id(end+1,1) = P.project_id(p); %#ok<AGROW>
        relative_path(end+1,1) = replace(string(f), string(root)+filesep, ""); %#ok<AGROW>
        absolute_path(end+1,1) = string(f); %#ok<AGROW>
        bytes(end+1,1) = d(k).bytes; %#ok<AGROW>
        sha256(end+1,1) = zhou_periodic.sha256_file(f); %#ok<AGROW>
    end
end
T = table(project_id, relative_path, absolute_path, bytes, sha256);
end

function T = freeze_selected_files(cfg)
model = cfg.model_error_snapshot;
proto = cfg.prototype_project;
src = [ ...
    string(cfg.source_model_error_csv); ...
    string(cfg.source_prototype_b0_csv); ...
    fullfile(model,'HANDOFF.md'); ...
    fullfile(model,'docs','MODEL_ERROR_DECOMPOSITION_REPORT.md'); ...
    fullfile(model,'docs','TIMING_ALIGNMENT_AUDIT.md'); ...
    fullfile(model,'results','summary','predictor_metrics.csv'); ...
    fullfile(model,'results','summary','residual_spectrum.csv'); ...
    fullfile(model,'results','summary','case_classification.csv'); ...
    fullfile(model,'results','summary','baseline_comparison.csv'); ...
    fullfile(model,'config','model_error_parameters.m'); ...
    fullfile(model,'src','+zhou_model_error','decompose_simulation.m'); ...
    fullfile(proto,'README.md'); ...
    fullfile(proto,'HANDOFF.md'); ...
    fullfile(proto,'docs','FINAL_PROTOTYPE_REPORT.md'); ...
    fullfile(proto,'docs','BASELINE_REPRODUCTION_REPORT.md'); ...
    fullfile(proto,'results','summary','final_decision.csv')];
dst = [ ...
    string(cfg.frozen_model_error_csv); ...
    string(cfg.frozen_prototype_b0_csv); ...
    fullfile(cfg.reference_dir,'model_error','HANDOFF.md'); ...
    fullfile(cfg.reference_dir,'model_error','MODEL_ERROR_DECOMPOSITION_REPORT.md'); ...
    fullfile(cfg.reference_dir,'model_error','TIMING_ALIGNMENT_AUDIT.md'); ...
    fullfile(cfg.reference_dir,'model_error','predictor_metrics.csv'); ...
    fullfile(cfg.reference_dir,'model_error','residual_spectrum.csv'); ...
    fullfile(cfg.reference_dir,'model_error','case_classification.csv'); ...
    fullfile(cfg.reference_dir,'model_error','baseline_comparison.csv'); ...
    fullfile(cfg.reference_dir,'model_error','model_error_parameters.m'); ...
    fullfile(cfg.reference_dir,'model_error','decompose_simulation.m'); ...
    fullfile(cfg.reference_dir,'dual_prototype','README.md'); ...
    fullfile(cfg.reference_dir,'dual_prototype','HANDOFF.md'); ...
    fullfile(cfg.reference_dir,'dual_prototype','FINAL_PROTOTYPE_REPORT.md'); ...
    fullfile(cfg.reference_dir,'dual_prototype','BASELINE_REPRODUCTION_REPORT.md'); ...
    fullfile(cfg.reference_dir,'dual_prototype','final_decision.csv')];
source_sha256 = strings(numel(src),1); destination_sha256 = strings(numel(src),1);
byte_identical = false(numel(src),1); bytes = zeros(numel(src),1);
for k = 1:numel(src)
    assert(isfile(src(k)), 'Required frozen source is absent: %s', src(k));
    parent = fileparts(dst(k)); if ~isfolder(parent), mkdir(parent); end
    source_sha256(k) = zhou_periodic.sha256_file(src(k));
    if ~isfile(dst(k)) || zhou_periodic.sha256_file(dst(k)) ~= source_sha256(k)
        [ok,msg] = copyfile(src(k), dst(k), 'f');
        assert(ok, 'Failed to copy %s: %s', src(k), msg);
    end
    destination_sha256(k) = zhou_periodic.sha256_file(dst(k));
    byte_identical(k) = source_sha256(k) == destination_sha256(k);
    info = dir(src(k)); bytes(k) = info.bytes;
end
assert(all(byte_identical), 'One or more frozen copies failed SHA-256 validation.');
T = table(src, dst, bytes, source_sha256, destination_sha256, byte_identical, ...
    'VariableNames', {'source_path','destination_path','bytes','source_sha256', ...
    'destination_sha256','byte_identical'});
end

function write_selection_doc(cfg, P, S, C)
stubIds = S.project_id(contains(S.status,"STUB") | contains(S.status,"MISSING"));
L = ["# Executable Source Selection";""; ...
    "The audit consumes no live sibling code. It freezes selected evidence and data into `reference/` before analysis.";""; ...
    "## Resolution";""];
for k = 1:height(P)
    L(end+1) = "- **"+P.project_id(k)+"**: requested `"+P.requested_path(k)+ ...
        "`; resolved `"+P.resolved_path(k)+"`; "+P.selection_reason(k)+"."; %#ok<AGROW>
end
L = [L;"";"Empty or missing requested paths were not treated as source code: `"+ ...
    strjoin(stubIds, "`, `")+"`.";"";"## Selected executable/timing evidence";""; ...
    "- The complete model-error snapshot restored at Git commit `2aa4e7f` supplies the 24-case aligned P0 data and timing implementation."; ...
    "- `decompose_simulation.m` and `TIMING_ALIGNMENT_AUDIT.md` freeze the original `k -> k+2` semantics."; ...
    "- The prototype B0 export supplies an independently reproduced overlap check for five cases."; ...
    "- No controller, plant, S2, Jd/Jq limit, or dual-timescale estimator is copied as modifiable runtime.";""; ...
    "## Frozen-copy gate";""; ...
    "Copied files: **"+height(C)+"**; byte-identical SHA-256 checks: **"+nnz(C.byte_identical)+"/"+height(C)+"**."];
writelines(L, fullfile(cfg.docs_dir,'EXECUTABLE_SOURCE_SELECTION.md'), 'Encoding','UTF-8');
end
