function [pass, results] = run_unit_tests(project)
%RUN_UNIT_TESTS Execute the complete mandatory validation test suite.

if nargin < 1
    project = struct();
end
root = fileparts(fileparts(mfilename('fullpath')));
restoredefaultpath;
paths = {root, fullfile(root,'config'), fullfile(root,'src'), ...
    fullfile(root,'experiments'), fullfile(root,'estimators'), ...
    fullfile(root,'tests'), fullfile(root,'tests','unit')};
for k = 1:numel(paths)
    if isfolder(paths{k})
        addpath(paths{k});
    end
end

expected = { ...
    'test_project_isolation.m', ...
    'test_strict_iter11_p0_regression.m', ...
    'test_ipmsm_equation_signs.m', ...
    'test_ipmsm_torque_components.m', ...
    'test_frame_patch_inheritance.m', ...
    'test_axis_specific_alpha.m', ...
    'test_common_alpha_mode.m', ...
    'test_negative_id_reference.m', ...
    'test_no_negative_duration_matrix.m', ...
    'test_no_illegal_command_matrix.m', ...
    'test_selected_queued_applied_alignment.m', ...
    'test_constraint_metric_identity.m', ...
    'test_thd_steady_state_window.m', ...
    'test_F_algebraic_causality.m', ...
    'test_basic_ESO_causality.m', ...
    'test_oracle_not_used_online.m', ...
    'test_U3_U4_accuracy.m', ...
    'test_RK4_switch_boundary_convergence.m', ...
    'test_summary_schema.m', ...
    'test_no_external_runtime_dependency.m'};
unit_root = fullfile(root,'tests','unit');
for k = 1:numel(expected)
    assert(isfile(fullfile(unit_root,expected{k})), ...
        'ZhouValidation:MissingUnitTest', ...
        'Required unit test is missing: %s',expected{k});
end

suite = testsuite(unit_root,'IncludeSubfolders',false);
assert(numel(suite) >= numel(expected), ...
    'ZhouValidation:IncompleteUnitSuite', ...
    'Expected at least %d tests, discovered %d.',numel(expected),numel(suite));
results = run(suite);
pass = ~isempty(results) && all([results.Passed]);

log_dir = fullfile(root,'logs');
if ~isfolder(log_dir), mkdir(log_dir); end
fid = fopen(fullfile(log_dir,'unit_test_log.txt'),'w','n','UTF-8');
assert(fid>=0,'ZhouValidation:UnitLogOpen','Cannot create unit-test log.');
cleanup = onCleanup(@() fclose(fid)); %#ok<NASGU>
run_id = "unit_test";
if isstruct(project) && isfield(project,'run_id')
    run_id = string(project.run_id);
end
fprintf(fid,'run_id: %s\n',run_id);
fprintf(fid,'tests: %d total, %d passed, %d failed, %d incomplete\n\n', ...
    numel(results),nnz([results.Passed]),nnz([results.Failed]), ...
    nnz([results.Incomplete]));
for k = 1:numel(results)
    fprintf(fid,'[%s] passed=%d failed=%d incomplete=%d duration=%.9g s\n', ...
        results(k).Name,results(k).Passed,results(k).Failed, ...
        results(k).Incomplete,results(k).Duration);
    if results(k).Failed || results(k).Incomplete
        fprintf(fid,'%s\n',diagnostic_report(results(k)));
    end
end
clear cleanup;
assert(pass,'ZhouValidation:UnitTestsFailed', ...
    'One or more mandatory unit tests failed; see logs/unit_test_log.txt.');
end

function report = diagnostic_report(result)
try
    report = result.Details.DiagnosticRecord.Report;
catch
    report = evalc('disp(result.Details)');
end
end
