function decision=generate_reports(project,data,tests_pass,test_count)
%GENERATE_REPORTS Write derivation, audits, decision, final report and handoff.
arguments
    project struct
    data struct
    tests_pass (1,1) logical=false
    test_count (1,1) double=0
end
root=project.root;
P=paired_metrics(data.A2);
propA1=data.A1(data.A1.strategy=="proposed_feasibility_aware",:);
radA1=data.A1(data.A1.strategy=="radial_hex_projection",:);
origA1=data.A1(data.A1.strategy=="original_zhou",:);
mainProp=[data.A1(data.A1.strategy=="proposed_feasibility_aware",:); ...
    data.A2(data.A2.strategy=="proposed_feasibility_aware",:)];
fallback_fraction=sum(mainProp.fallback_cycles)/sum(mainProp.trace_rows);
predicted_rate=min([mainProp.predicted_d_constraint_satisfaction_rate; ...
    mainProp.predicted_q_constraint_satisfaction_rate]);
a4prop=data.A4(data.A4.strategy=="proposed_feasibility_aware",:);
a4orig=data.A4(data.A4.strategy=="original_zhou",:);
algorithm_gate=data.p0_gate&&data.p1_gate&&data.A1_gate&&data.A2_gate&&data.A3_gate;
performance_degraded=P.maximum_engineering_relative_change>project.thresholds.engineering_relative_change || ...
    P.feasibility_layer_overhead_fraction_max>project.thresholds.engineering_relative_change;
if ~tests_pass || ~algorithm_gate
    code="E";title="几何/数值/回归失败，当前方案不成立";
elseif performance_degraded
    code="D";title="算法合法但性能或计算量出现工程量级恶化";
elseif fallback_fraction==0
    code="A";title="S2保持原独立约束并消除非法命令，跨工况无工程量级恶化";
elseif fallback_fraction<1 && predicted_rate>=1-1e-12
    code="B";title="S2有效，但部分工况需要S3约束放宽";
else
    code="C";title="只能通过普遍约束放宽维持合法";
end
decision=struct('code',code,'title',title,'tests_pass',tests_pass, ...
    'test_count',test_count,'fallback_fraction',fallback_fraction, ...
    'predicted_constraint_satisfaction_rate',predicted_rate, ...
    'performance',P,'algorithm_gate',algorithm_gate);

write_derivation();write_intersection();write_decision();write_final();write_handoff();write_changelog();write_readme();

    function write_derivation()
        fid=open_md(fullfile(root,'ALGORITHM_DERIVATION.md'));c=onCleanup(@()fclose(fid)); %#ok<NASGU>
        fprintf(fid,['# Feasibility-Control Algorithm Derivation\n\n## 1. Frozen quantities\n\n' ...
            '`Fhat`, alpha, Jd/Jq, motor parameters, rectangle construction, Case 1/2, switching sequence structure and selected/pending/applied delay are unchanged.\n\n' ...
            '## 2. Sets\n\n`R={u: |(ud-ucd)/hd|<=1, |(uq-ucq)/hq|<=1}`. ' ...
            '`H` is the convex hull of the six active vectors. `point_in_hexagon` uses six half spaces and never reads `controller.legal`.\n\n' ...
            '## 3. S1 radial baseline\n\nFor an outside center, the ray from zero to `uc` is intersected with the limiting hexagon half space. ' ...
            'Membership in R is checked independently; S1 is only an engineering comparison.\n\n' ...
            '## 4. S2 nearest feasible intersection point\n\nThe rectangle is clipped by all six H half spaces. In normalized dq coordinates, ' ...
            '`z=[(ud-ucd)/hd,(uq-ucq)/hq]`, S2 projects the origin onto the convex polygon R∩H and minimizes `z_d^2+z_q^2`. ' ...
            'The returned point is transformed back to alpha-beta and synthesized by the original sector/barycentric three-vector structure.\n\n' ...
            '## 5. S3 minimum violation\n\nIf R∩H is empty, the same normalized projection is performed over H. ' ...
            'Its objective equals `Jd/Jd_limit+Jq/Jq_limit`; per-axis ratios and violations are logged. ' ...
            'Independent dense edge enumeration cross-checks the optimizer.\n\n' ...
            '## 6. Exact degeneration\n\nCase 1/2 are returned untouched. For Case 3, independent half-space membership is evaluated; ' ...
            'if the center lies in H, the original command struct is returned without changing reference, vectors, duties, durations, sequence or switching actions.\n\n' ...
            'No `max(d0,0)`, duty renormalization, hidden voltage clipping, alpha/F/J modification, MTPA or motor change is used.\n']);
    end

    function write_intersection()
        A=data.intersection_audit;S=data.intersection_summary;
        fid=open_md(fullfile(root,'INTERSECTION_AUDIT.md'));c=onCleanup(@()fclose(fid)); %#ok<NASGU>
        fprintf(fid,['# Original-Illegal-Cycle Intersection Audit\n\n- run_id: `%s`\n' ...
            '- original illegal selected cycles: `%d`\n- R∩H nonempty and S2-preservable: `%d/%d = %.6f`\n' ...
            '- intersection area: `%.12g V^2`\n- S2 nearest offset: `%.12g V`\n' ...
            '- radial offset: `%.12g V`\n- radial point inside R: `%s`\n' ...
            '- S2 Jd/Jq: `[%.12g, %.12g] A^2` versus limits `[%.12g, %.12g] A^2`\n' ...
            '- S2 duties: `[%.17g, %.17g, %.17g]`, sum `%.17g`\n\n' ...
            'Answer to the mandatory pre-control question: **%.2f%%** of original illegal cycles can be completed by a point in R∩H without relaxing Jd/Jq. ' ...
            'Therefore S2 remains the primary method.\n'],project.run_id,S.original_illegal_cycles, ...
            S.S2_preservable_cycles,S.original_illegal_cycles,S.S2_preservable_fraction, ...
            A.intersection_area_V2(1),A.nearest_offset_V(1),A.radial_offset_V(1),token(A.radial_inside_rectangle(1)), ...
            A.nearest_Jd_A2(1),A.nearest_Jq_A2(1),project.base.Jd_limit_A2,project.base.Jq_limit_A2, ...
            A.nearest_d0(1),A.nearest_d1(1),A.nearest_d2(1),A.nearest_duty_sum(1),100*S.S2_preservable_fraction);
    end

    function write_decision()
        fid=open_md(fullfile(root,'FEASIBILITY_CONTROL_DECISION.md'));c=onCleanup(@()fclose(fid)); %#ok<NASGU>
        fprintf(fid,['# Feasibility-Control Decision\n\n## %s. %s\n\n' ...
            '- run_id: `%s`\n- tests: `%d`, gate `%s`\n- frozen P0/P1 regression: `%s`\n' ...
            '- original-illegal S2-preservable fraction: `%.6f`\n- main-campaign fallback fraction: `%.9g`\n' ...
            '- minimum predicted Jd/Jq satisfaction rate: `%.9g`\n' ...
            '- maximum paired THD/torque-ripple/switching engineering change in original-feasible A2 cases: `%.9g`\n' ...
            '- feasibility-layer share of proposed A2 execution time, mean/max: `[%.9g, %.9g]`\n' ...
            '- proposed A4 admissions: `%d/%d PASS`; original: `%d/%d PASS`\n\n' ...
            'The decision uses every registered row. Failed S0 rows remain FAIL and are not removed from averages.\n'], ...
            code,title,project.run_id,test_count,token(tests_pass),token(data.p0_gate&&data.p1_gate), ...
            data.intersection_summary.S2_preservable_fraction,fallback_fraction,predicted_rate, ...
            P.maximum_engineering_relative_change,P.feasibility_layer_overhead_fraction_mean, ...
            P.feasibility_layer_overhead_fraction_max,nnz(a4prop.run_status=="PASS"),height(a4prop), ...
            nnz(a4orig.run_status=="PASS"),height(a4orig));
    end

    function write_final()
        fid=open_md(fullfile(root,'FINAL_FEASIBILITY_CONTROL_REPORT.md'));c=onCleanup(@()fclose(fid)); %#ok<NASGU>
        fprintf(fid,['# Zhou ICF-MPC IPMSM Explicit Voltage-Feasibility Control\n\n' ...
            '## Executive result\n\nDecision: **%s. %s**. Proposed completes the frozen 500 rpm/20 A/48 V/5 ms case with zero illegal commands and zero negative dwell.\n\n' ...
            '## Frozen regression\n\nFormal P0 100/300/500 rpm independent closed loops pass pointwise. ' ...
            'P1 retains selected illegal at 4.4 ms and applied illegal at 4.5 ms with the frozen reference and duties.\n\n' ...
            '## Set audit\n\nThe original illegal sample has R∩H area `%.9g V^2`; S2-preservable ratio is `%.2f%%`. ' ...
            'S2 offset `%.9g V` is smaller than radial `%.9g V`, and both happen to remain in R for this sample.\n\n' ...
            '## A1 original failure\n\nS0 is FAIL and has no steady THD/torque metrics. S1 and proposed both finish 0.2 s. ' ...
            'Proposed fallback ratio is `%.9g`, predicted d/q satisfaction is `[%.9g, %.9g]`, actual engineering violation rates are `[%.9g, %.9g]`. ' ...
            'Its steady THD is `%.9g%%`, torque ripple `%.9g Nm`, switching actions `%g`; average/p95/max host execution times are `[%.9g, %.9g, %.9g] s`.\n\n' ...
            '## A2 paired six-condition matrix\n\nProposed passes `%d/%d`; S1 passes `%d/%d`; S0 passes `%d/%d`. ' ...
            'Across all S0-feasible paired rows, proposed returns the original command and maximum engineering relative change is `%.9g`.\n\n' ...
            'The feasibility layer accounts for mean/max `[%.9g, %.9g]` of proposed A2 host execution time, below the preregistered 10%% engineering-change threshold.\n\n' ...
            '## A3 boundary revalidation\n\nProposed passes `%d/%d` points and modifies zero commands in every original-feasible point. ' ...
            'The original FAIL rows are retained explicitly.\n\n' ...
            '## A4 negative-id admission\n\nProposed passes `%d/%d` probes with aggregate fallback fraction `%.9g`; S0 passes `%d/%d`. ' ...
            'This is an admission probe only and does not introduce MTPA.\n\n' ...
            '## S3 status\n\nNo registered main or admission operating point required S3; its correctness is established by synthetic empty-intersection tests and independent dense edge enumeration, not by claiming an observed fallback benefit.\n\n' ...
            '## Timing scope\n\nExecution times are MATLAB host measurements after excluding the first 10%% of cycles. They are comparative evidence, not an embedded real-time certification.\n\n' ...
            '## Boundaries\n\nNo Vdc/ramp change is presented as the algorithm, and no F, alpha, J, motor, MTPA, duty clipping or silent sample deletion is used.\n'], ...
            code,title,data.intersection_audit.intersection_area_V2(1),100*data.intersection_summary.S2_preservable_fraction, ...
            data.intersection_audit.nearest_offset_V(1),data.intersection_audit.radial_offset_V(1), ...
            propA1.fallback_fraction,propA1.predicted_d_constraint_satisfaction_rate, ...
            propA1.predicted_q_constraint_satisfaction_rate,propA1.actual_d_constraint_violation_rate, ...
            propA1.actual_q_constraint_violation_rate,propA1.steady_thd_percent,propA1.torque_ripple_Nm, ...
            propA1.switching_actions,propA1.execution_time_average_s,propA1.execution_time_p95_s, ...
            propA1.execution_time_max_s,nnz(data.A2.strategy=="proposed_feasibility_aware" & data.A2.run_status=="PASS"), ...
            nnz(data.A2.strategy=="proposed_feasibility_aware"), ...
            nnz(data.A2.strategy=="radial_hex_projection" & data.A2.run_status=="PASS"), ...
            nnz(data.A2.strategy=="radial_hex_projection"), ...
            nnz(data.A2.strategy=="original_zhou" & data.A2.run_status=="PASS"), ...
            nnz(data.A2.strategy=="original_zhou"),P.maximum_engineering_relative_change, ...
            P.feasibility_layer_overhead_fraction_mean,P.feasibility_layer_overhead_fraction_max, ...
            nnz(data.A3.strategy=="proposed_feasibility_aware" & data.A3.run_status=="PASS"), ...
            nnz(data.A3.strategy=="proposed_feasibility_aware"), ...
            nnz(a4prop.run_status=="PASS"),height(a4prop),sum(a4prop.fallback_cycles)/sum(a4prop.trace_rows), ...
            nnz(a4orig.run_status=="PASS"),height(a4orig));
    end

    function write_handoff()
        fid=open_md(fullfile(root,'EXPERIMENT_HANDOFF.md'));c=onCleanup(@()fclose(fid)); %#ok<NASGU>
        fprintf(fid,['# Experiment Handoff\n\n- project: `%s`\n- run_id: `%s`\n- decision: **%s**\n' ...
            '- rerun: `run_all_feasibility_control`\n- frozen packages: `+zhou_ipmsm`, `+zhou_iter11_ref`\n' ...
            '- new package: `+zhou_feasibility`\n\nRead `SOURCE_COPY_REPORT.md`, `PATH_ISOLATION_AUDIT.md`, ' ...
            '`INTERSECTION_AUDIT.md`, the four comparison CSV files, `TEST_REPORT.md`, then the final report.\n'], ...
            root,project.run_id,code);
    end
    function write_changelog()
        fid=open_md(fullfile(root,'CHANGELOG.md'));c=onCleanup(@()fclose(fid)); %#ok<NASGU>
        fprintf(fid,['# Changelog\n\n## 1.0.0 — %s\n\n- Copied two frozen execution namespaces without core edits.\n' ...
            '- Added independent H membership, convex R∩H clipping, normalized polygon projection, S2/S3 and three-vector synthesis.\n' ...
            '- Added S0/S1/proposed closed-loop comparison, frozen regression, 12-condition matrix, 72-point boundary comparison and negative-id admission.\n' ...
            '- Added tests, plots, reports and SHA256 audit manifests.\n'],project.timestamp);
    end
    function write_readme()
        fid=open_md(fullfile(root,'README.md'));c=onCleanup(@()fclose(fid)); %#ok<NASGU>
        fprintf(fid,['# Zhou ICF-MPC IPMSM Feasibility Control Iteration 01\n\n' ...
            'Independent explicit voltage-feasibility control project. Frozen controller packages remain byte-identical.\n\n' ...
            '- formal run_id: `%s`\n- decision: **%s**\n- one-command rerun: `run_all_feasibility_control`\n' ...
            '- primary method: S2 nearest point in R∩H\n- fallback: S3 minimum normalized violation in H\n\n' ...
            'Start with `ALGORITHM_DERIVATION.md`, `INTERSECTION_AUDIT.md`, `TEST_REPORT.md`, and `FINAL_FEASIBILITY_CONTROL_REPORT.md`.\n'], ...
            project.run_id,code);
    end
end

function P=paired_metrics(A)
prop=A(A.strategy=="proposed_feasibility_aware",:);orig=A(A.strategy=="original_zhou",:);
deltas=[];ratios=[];
for k=1:height(prop)
    match=orig.speed_rpm==prop.speed_rpm(k)&orig.id_ref_A==prop.id_ref_A(k)& ...
        orig.iq_ref_A==prop.iq_ref_A(k)&orig.motor_model==prop.motor_model(k)& ...
        orig.dc_bus_V==prop.dc_bus_V(k)&orig.reference_ramp_s==prop.reference_ramp_s(k);
    if nnz(match)~=1||orig.run_status(match)~="PASS",continue;end
    base=[orig.steady_thd_percent(match),orig.torque_ripple_Nm(match),orig.switching_actions(match)];
    candidate=[prop.steady_thd_percent(k),prop.torque_ripple_Nm(k),prop.switching_actions(k)];
    deltas(end+1,:)=abs(candidate-base)./max(abs(base),eps); %#ok<AGROW>
    ratios(end+1)=prop.execution_time_average_s(k)/max(orig.execution_time_average_s(match),eps); %#ok<AGROW>
end
if isempty(deltas),maximum=Inf;else,maximum=max(deltas,[],'all');end
layer_fraction=prop.feasibility_layer_time_average_s./prop.execution_time_average_s;
P=struct('paired_legal_rows',size(deltas,1),'maximum_engineering_relative_change',maximum, ...
    'execution_time_ratio_mean',mean(ratios),'execution_time_ratio_max',max(ratios), ...
    'feasibility_layer_overhead_fraction_mean',mean(layer_fraction), ...
    'feasibility_layer_overhead_fraction_max',max(layer_fraction));
end
function fid=open_md(path_value)
fid=fopen(path_value,'w','n','UTF-8');assert(fid>=0,'ZhouFeasibility:ReportOpen','Cannot open %s',path_value);
end
function s=token(v),if v,s='PASS';else,s='FAIL';end,end
