function U=discover_upstreams(project)
parent=fileparts(project.root);
U=[ ...
struct('name',"ipmsm_probe",'path',fullfile(parent,'zhou_icf_mpc_ipmsm_probe_iter01'),'evidence',{{'FINAL_IPMSM_PROBE_REPORT.md','src/+zhou_ipmsm/+controller/icf_mpc_step.m'}}); ...
struct('name',"s2_feasibility",'path',fullfile(parent,'zhou_icf_mpc_ipmsm_feasibility_control_iter01'),'evidence',{{'FINAL_FEASIBILITY_CONTROL_REPORT.md','src/+zhou_feasibility/rectangle_hexagon_intersection.m'}}); ...
struct('name',"robust_residual",'path',fullfile(parent,'zhou_icf_mpc_ipmsm_robust_constraint_iter01'),'evidence',{{'FINAL_ROBUST_CONSTRAINT_REPORT.md','RESIDUAL_ALIGNMENT_AUDIT.md'}}); ...
struct('name',"sequence_decomposition",'path',fullfile(parent,'zhou_icf_mpc_sequence_decomposition_iter01'),'evidence',{{'HANDOFF.md','docs/SEQUENCE_DECOMPOSITION_REPORT.md','results/raw/sample_decomposition.csv'}}); ...
struct('name',"jd_jq_audit",'path',fullfile(parent,'baseline_zhou-main','baseline_zhou-main','zhou_icf_mpc_constraint_audit_v1'),'evidence',{{'results/summary/all_constraint_cases.csv','src/+zhou_constraint/run_baseline_gate.m'}})];
for k=1:numel(U),assert(isfolder(U(k).path),'ZhouModelError:UpstreamMissing');for e=1:numel(U(k).evidence),assert(isfile(fullfile(U(k).path,strrep(U(k).evidence{e},'/',filesep))),'ZhouModelError:EvidenceMissing');end,end
end
