function result=run_baseline_gate(project)
%RUN_BASELINE_GATE Execute the ten minimal, deterministic prerequisite checks.
assert(project.model_error.Jd_limit_A2==.16&&project.model_error.Jq_limit_A2==.16, ...
    'ZhouModelError:BaselineConstraintDrift');
S=sequence_scenarios(project);
nom=run_case(S(1));neg=run_case(S(5));nonS2=run_case(S(8));boundary=run_case(S(9));fs=run_case(S(7));
deg=S(1);deg.scenario_id="BL_Ld_equals_Lq";deg.name=deg.scenario_id;deg.motor_model="P0";deg.alpha_mode="axis_specific";deg=run_case(deg);
rep2=run_case(S(1));rep3=run_case(S(1));
Dnom=zhou_sequence.decompose_simulation(project,nom);Dfs=zhou_sequence.decompose_simulation(project,fs);

delta12=repeat_delta(nom,rep2);delta13=repeat_delta(nom,rep3);repeat_delta_max=max(delta12,delta13);
sequence_gap=max(hypot(Dnom.ed_sequence_ul,Dnom.eq_sequence_ul));
plant_gap=max(hypot(Dnom.ed_model_plant,Dnom.eq_model_plant));
false_safe_rate=mean(Dfs.false_safe_d|Dfs.false_safe_q);
checks=[ ...
    row("accepted_IPMSM_nominal",nom.completed&&~nom.illegal_event.occurred, ...
        sprintf('completed=%d illegal=%d',nom.completed,nom.illegal_event.occurred),"complete and legal"); ...
    row("Ld_equals_Lq_degeneration",deg.completed&&deg.plant_motor.Ld_H==deg.plant_motor.Lq_H, ...
        sprintf('Ld=%.9g Lq=%.9g',deg.plant_motor.Ld_H,deg.plant_motor.Lq_H),"P0 complete with Ld=Lq"); ...
    row("negative_id_case",neg.completed&&neg.scenario.id_ref_A<0, ...
        sprintf('id_ref=%.9g completed=%d',neg.scenario.id_ref_A,neg.completed),"negative-id complete"); ...
    row("independent_alpha_d_q",nom.trace.alpha_d(1)~=nom.trace.alpha_q(1), ...
        sprintf('alpha_d=%.12g alpha_q=%.12g',nom.trace.alpha_d(1),nom.trace.alpha_q(1)),"axis-specific and unequal"); ...
    row("S2_nontrigger",nnz(nonS2.trace.S2_used)==0, ...
        sprintf('S2_cycles=%d',nnz(nonS2.trace.S2_used)),"zero S2 cycles"); ...
    row("S2_boundary_trigger",nnz(boundary.trace.S2_used)>0, ...
        sprintf('S2_cycles=%d',nnz(boundary.trace.S2_used)),">0 S2 cycles"); ...
    row("representative_false_safe",false_safe_rate>0, ...
        sprintf('aligned_joint_false_safe_rate=%.12g',false_safe_rate),">0 in frozen representative"); ...
    row("sequence_term_floating_point",sequence_gap<=project.sequence.ultralocal_identity_tolerance_A, ...
        sprintf('max_sequence_gap_A=%.17g',sequence_gap),sprintf('<=%.3g A',project.sequence.ultralocal_identity_tolerance_A)); ...
    row("plant_oracle_replay",plant_gap<=project.model_error.plant_replay_tolerance_A, ...
        sprintf('max_plant_gap_A=%.17g',plant_gap),sprintf('<=%.3g A',project.model_error.plant_replay_tolerance_A)); ...
    row("three_run_repeatability",repeat_delta_max<=project.model_error.repeatability_tolerance, ...
        sprintf('max_numeric_delta=%.17g',repeat_delta_max),sprintf('<=%.3g',project.model_error.repeatability_tolerance))];
T=struct2table(checks,'AsArray',true);T.Jd_limit_A2=repmat(.16,height(T),1);T.Jq_limit_A2=repmat(.16,height(T),1);
writetable(T,fullfile(project.dirs.summary,'baseline_comparison.csv'));
write_report(project,T,sequence_gap,plant_gap,repeat_delta_max);
result=struct('passed',nnz(T.pass),'failed',nnz(~T.pass),'checks',height(T), ...
    'sequence_gap_max_A',sequence_gap,'plant_gap_max_A',plant_gap, ...
    'representative_false_safe_rate',false_safe_rate,'repeatability_max_delta',repeat_delta_max);
assert(result.failed==0,'ZhouModelError:BaselineGateFailure','Baseline gate failed %d/%d checks.',result.failed,result.checks);

    function simulation=run_case(scenario)
        simulation=zhou_robust.run_robust_case(project,scenario,"C0_original_feasibility_control",struct(),struct());
    end
end

function s=row(name,pass,observed,requirement)
s=struct('check',string(name),'pass',logical(pass),'observed',string(observed),'requirement',string(requirement));
end

function value=repeat_delta(a,b)
vars=["id_A","iq_A","id_pred_k2_A","iq_pred_k2_A","Fd_hat","Fq_hat","reference_alpha_V","reference_beta_V"];
assert(height(a.trace)==height(b.trace),'ZhouModelError:RepeatabilityLength');value=0;
for name=vars,value=max(value,max(abs(a.trace.(name)-b.trace.(name)),[],'omitnan'));end
assert(all(a.trace.selected_sequence_vector_ids==b.trace.selected_sequence_vector_ids));
assert(all(a.trace.selected_sequence_durations_s==b.trace.selected_sequence_durations_s));
end

function write_report(project,T,sequence_gap,plant_gap,repeat_delta)
fid=fopen(fullfile(project.dirs.docs,'BASELINE_REPRODUCTION_REPORT.md'),'w');assert(fid>0);clean=onCleanup(@()fclose(fid)); %#ok<NASGU>
fprintf(fid,'# Baseline Reproduction Report\n\n');
fprintf(fid,'Result: **%d/%d checks passed**. Fixed independent limits are `Jd_limit = Jq_limit = 0.16 A^2`.\n\n',nnz(T.pass),height(T));
fprintf(fid,'| Check | Pass | Observation | Requirement |\n|---|---:|---|---|\n');
for k=1:height(T),fprintf(fid,'| %s | %d | %s | %s |\n',T.check(k),T.pass(k),T.observed(k),T.requirement(k));end
fprintf(fid,'\nThe local frozen runtime was executed for nominal IPMSM, Ld=Lq degeneration, negative-id, S2 non-trigger, S2 boundary, and known false-safe cases. The nominal case was executed three times.\n\n');
fprintf(fid,'Strict two-period alignment gave maximum average-vs-piecewise-UL gap `%.17g A`, plant replay gap `%.17g A`, and three-run numeric delta `%.17g`. No result was taken from the 608-point Jd/Jq scan.\n',sequence_gap,plant_gap,repeat_delta);
end
